### ISSUE TITLE
Video doesn't start [rPi4/LE]

### ISSUE THREAD

**Issue by Thorwald89** [Sandmann79/xbmc#374] opened 2019-12-01 11:33 UTC
**Addon used**
- [x] Amazon VOD (plugin.video.amazon-test)

**Prime Video Account (select one)**
- [x] primevideo.com

**System Setup (please provide the following information):**
- Hardware: RaspberryPI 4
- OS Version: libreelec 
- Kodi Version 18.4

**Describe the bug**
When I start some videos, the screen is block

**Comment by Varstahl** [comment] 2019-12-01 12:43
You forgot to provide the full logs. More info on the Wiki/FAQ page, if you don't know where to find them.

**Comment by gmanic** [comment] 2019-12-01 21:24
If I may chime in. On my setup (LE 9.2, latest Addon from repo, just updated), I can select a Video and the screen stays blank, but hyperiond is showing video-activity - the led strips light as if a video is running. The following shows up in the logs:

`2019-12-01 19:49:18.996 T:2508215152  NOTICE: [Amazon VOD] Starting Playback: 0.0/6890.00048828
`
`2019-12-01 19:49:18.997 T:2508215152  NOTICE: [Amazon VOD] postURL: https://atv-ps-eu.amazon.de/cdp/usage/UpdateStream?asin=&deviceTypeID=\<someid\>&firmware=1&deviceID=\<someotherid\>&marketplaceID=\<somemoreotherid\>&format=json&version=1&gascEnabled=false&subtitleFormat=TTMLv2&event=START&timecode=0.0
`
`2019-12-01 19:49:19.120 T:2374120304  NOTICE: Creating audio stream (codec id: 86018, channels: 2, sample rate: 48000, no pass-through)
`
`2019-12-01 19:49:19.830 T:2499822448 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
`
`2019-12-01 19:49:27.480 T:2499822448 WARNING: Previous line repeats 74 times.
`
`2019-12-01 19:49:27.480 T:2499822448   ERROR: CMMALPool::GetBuffer - failed pool:0x906d69c0 omvb:(nil) mmal:(nil) timeout:500
`
`2019-12-01 19:49:27.480 T:2499822448   ERROR: CAddonVideoCodec::GetFrameBuffer Failed to allocate buffer
`

[https://pastebin.com/2aD9tPgw](https://pastebin.com/2aD9tPgw)

The last two lines are then repeated until the pi4 is rebooted, it is non responsive on the UI (not shown).

Trust this helps.

**Comment by Varstahl** [comment] 2019-12-01 21:26
```
WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
WARNING: Previous line repeats 74 times.
  ERROR: CMMALPool::GetBuffer - failed pool:0x906d69c0 omvb:(nil) mmal:(nil) timeout:500
```
The data stream times out. There's a networking problem between you and the servers. Maybe a faulty network stack?

**Comment by gmanic** [comment] 2019-12-01 21:32
On the rpi4 side? TVheadend via local network on DVB-S2 streams runs fine. Other than that, Internet runs pretty well speed/ping wise. And I wouldn't assume Amazons HW to be underpowered. :smile:

**Comment by Varstahl** [comment] 2019-12-01 21:37
Not sure, there's not enough log to go around. Generally speaking, if video playback starts it's off our addon responsibility, so you must look into either network or configurations somewhere between Kodi, InputStream.Adaptive and the O/S.

If you have audio, but blank video, that can pretty much be caused by an undecryptable video stream, so you might have to possible disable "Override HDCP" in IS.A, or however the option was called.

Other possibilities for things going wrong might include static routes and VPNs.

**Comment by gmanic** [comment] 2019-12-01 21:44
OK, thx for your help an hints, will check some (logs and more), might take some time (days), though. Time's just too tight.
Side note: audio is as blank as video.

**Comment by gmanic** [comment] 2019-12-07 12:55
Re-Checked all installation and found out that for whatever reason inputstream.adaptive was empty. De-installed that addon, reinstalled and here we go. Amazon VOD works again.

Thanks to Varstahl for the right hints.

**Comment by gmanic** [comment] 2019-12-07 13:56
Well, not all done, yet. After watching for about an hour, I wanted to pause the movie. Screen went black and that's it. Reboot required. Still searching, will report back.

**Comment by gmanic** [comment] 2019-12-07 14:20
Logs shows only the following warning after pressing pause on the remote. No more usable, reboot required.

`
2019-12-07 15:08:14.140 T:2605433712 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
`
`
2019-12-07 15:10:24.888 T:2586452848 WARNING: Previous line repeats 258 times.
`

**Comment by Varstahl** [comment] 2019-12-07 14:22
Hardware/OS issue, can't really help you there. Also, stop hijacking the issue please? :)

**Comment by gmanic** [comment] 2019-12-07 14:28
OK. Was not aware that following up on the issue would be hijacking. Sry. Will open new issue.

**Comment by Varstahl** [comment] 2019-12-07 14:33
Well, unless you're the same user or having the same problem as the OP, it is a bit of hijacking. @gmanic in your case since it's not an addon fault, don't bother opening a new one 'cause I would have to close it.

In regard to the op it's almost a week with no updates, so I guess I'll close this. @Thorwald89 feel free to reopen if you have logs to provide.

**Closed by Varstahl** 2019-12-07 14:33 UTC
Labels: need info
