### ISSUE TITLE
Search option not working

### ISSUE THREAD

**Issue by bhaskarndas** [Sandmann79/xbmc#546] opened 2021-02-28 16:22 UTC
**Addon used**
- [x] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 

**Account type**
- [x] primevideo.com
- [ ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: Raspberry Pi 2
- OS version: 18.8

- Kodi version number: Leia 18.8

**Upload Logs**

**Describe the bug**

Whenever I search for movie I am receiving the following error message:
"Amazon Vod error. Check log for error message"
And the search doesn't happen.

[kodi.log](https://github.com/Sandmann79/xbmc/files/6057184/kodi.log)

**Comment by DevilBlackDeath** [comment] 2021-02-28 16:40
Hmmm, sounds similar to mine. Can you access the Movie and All list in your watchlist section ? (not a dev, but if it's the same error, could help them to know it)

**Comment by Sandmann79** [comment] 2021-02-28 17:43
After checking the log it seems to be duplicate of #544.

**Comment by bhaskarndas** [comment] 2021-02-28 18:25
> Hmmm, sounds similar to mine. Can you access the Movie and All list in your watchlist section ? (not a dev, but if it's the same error, could help them to know it)

No, I cannot and yes it looks like similar to issues #545 #544

**Comment by DevilBlackDeath** [comment] 2021-03-01 12:43
> After checking the log it seems to be duplicate of #544.
> This has been fixed with [366e63b](https://github.com/Sandmann79/xbmc/commit/366e63ba316d589561a860ad2ef6d52c2e8a3022).
> But it needs some time to merge, before it's avaible in the next release.

Glad to know ! Just gonna wait patiently for the update then, thanks ;)

**Comment by pivoj13** [comment] 2021-03-03 15:50
I am facing the same/similar issue - cannot browse movie catalog, cannot use search (seems it works for TVshows), can browse and play TVshows.

I tried the fix described in 366e63b above: manually edited primevideo.py (I am on Kodi 18.9). Added described 3 rows two times (I found "details = state['detail']" in two position in the file so I added described 3 rows in both positions). Deleted  .pvcp, .pvdp as well.
Now I can use at least My watchlist - when I add movie in my mobile phone app I can see it in this category and can play it on Kodi from here. Browsing Movies categories still does not work (starts loading pages but crashes).
Best regards.

rpi3B+, Libreelec 9.2.6 RPi2.arm, Kodi 18.9 Leia, Amazon account activated on amazon.de, but works on primevideo.com in browser on pc (do not understand account type).

**Comment by pivoj13** [comment] 2021-03-03 16:01
Just one additional comment - movie search seems to work as well but not fully.
Search "borat" crashes with addon error. Search "borat movie" works and gives playable result.

**Comment by Paco8** [comment] 2021-03-06 07:40
Try replacing primevideo.py with the file in the attached zip.

[primevideo.zip](https://github.com/Sandmann79/xbmc/files/6094946/primevideo.zip)

**Comment by bhaskarndas** [comment] 2021-03-06 14:24
> Try replacing primevideo.py with the file in the attached zip.
> 
> [primevideo.zip](https://github.com/Sandmann79/xbmc/files/6094946/primevideo.zip)

Thanks it has worked... But I don't know if it is a bug or issue with the system. 

Whenever the movie starts, there is no sound. Is anyone else facing the same issue. I am using RPI2 and Kodi Leia. This is happening after adding the primevideo.py file.

**Comment by pivoj13** [comment] 2021-03-06 17:38
To solve some no sound issues I had to enable "audio descriptions" in language menu in addon settings on rpi3b+. You can try (no idea why it works).

**Comment by staffa007** [comment] 2021-03-06 20:37
> Try replacing primevideo.py with the file in the attached zip.
> 
> [primevideo.zip](https://github.com/Sandmann79/xbmc/files/6094946/primevideo.zip)

Hi Paco, I have the same issues and I kindly ask you how do I change the file on a rpi 4?

**Comment by bhaskarndas** [comment] 2021-03-07 04:33
After updating the primevideo.py the issue has resolved. So closing this issue.

**Closed** 2021-03-07 04:32 UTC
Labels: broken, primevideo
