### ISSUE TITLE
Amazon plugin crashes on Kodi when loading watchlist

### ISSUE THREAD

**Issue by t3chn1ca** [Sandmann79/xbmc#585] opened 2021-09-25 08:58 UTC
Thanks for taking time and supporting this plugin, Please find below an issue seen on Kodi.
Running on OSMC, Kodi Matrix on Pi4.

Reproductions steps:
- Start Amazon VOD plugin 
- Complete login
- Open watchlist or do a search with a keyword, both results in same traceback

```
Addon used
    Amazon VOD (plugin.video.amazon-test)
    Browser Launcher (plugin.program.browser.launcher)
    Addon version: v0.9.4+matrix.1

Account type

    primevideo.com

System Setup (please provide the following information):

    Hardware: Pi 4
    OS version: 5.10.32-1-osmc
    Kodi version number: 19.1
```

**Error log:**
```
2021-09-25 08:51:37.915 T:784     ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--                 
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!                                                                    
                                                   Error Type: <class 'KeyError'>                                                                                      
                                                   Error Contents: 'parent'                                                                                            
                                                   Traceback (most recent call last):                                                                                  
                                                     File "/home/osmc/.kodi/addons/plugin.video.amazon-test/default.py", line 5, in <module>                           
                                                       EntryPoint()                                                                                                    
                                                     File "/home/osmc/.kodi/addons/plugin.video.amazon-test/resources/lib/startup.py", line 63, in EntryPoint          
                                                       g.pv.Route(verb, path)                                                                                          
                                                     File "/home/osmc/.kodi/addons/plugin.video.amazon-test/resources/lib/primevideo.py", line 281, in Route           
                                                       elif 'browse' == verb: g.pv.Browse(path)                                                                        
                                                     File "/home/osmc/.kodi/addons/plugin.video.amazon-test/resources/lib/primevideo.py", line 468, in Browse          
                                                       node, breadcrumb = self._TraverseCatalog(path)                                                                  
                                                     File "/home/osmc/.kodi/addons/plugin.video.amazon-test/resources/lib/primevideo.py", line 249, in _TraverseCatalog
                                                       self._LazyLoad(node[nodeName], pathList[0:1 + i])                                                         
                                                     File "/home/osmc/.kodi/addons/plugin.video.amazon-test/resources/lib/primevideo.py", line 1215, in _LazyLoad
                                                       bUpdatedVideoData |= AddSeason(breadcrumb[-1], o, bCacheRefresh, title, iu)                              
                                                     File "/home/osmc/.kodi/addons/plugin.video.amazon-test/resources/lib/primevideo.py", line 794, in AddSeason
                                                       parent = self._videodata[self._videodata['urn2gti'][urn]]['parent']                                 
                                                   KeyError: 'parent'                                                                                                         
                                                   -->End of Python script error report<--                                                                 
```

**Comment by Sandmann79** [comment] 2021-09-29 18:37
Duplicate of #531

**Closed by Sandmann79** 2021-09-29 18:37 UTC
