### ISSUE TITLE
'AS WE SEE IT' series video links do not parse correctly.

### ISSUE THREAD

**Issue by nubjub** [Sandmann79/xbmc#619] opened 2022-03-11 19:15 UTC
**Addon used**
- [X] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 0.9.5~beta3

**Account type**
- [ ] primevideo.com
- [X] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: x86-64 + NVidia
- OS version: debian (devuan)
- Kodi version number: 19.3

**Upload Logs**

https://pastebin.com/UcTUnAxd

**Describe the bug**

When selecting the show 'AS WE SEE IT' no videos are offered, probably a failure to parse some new format the links are in.
I don't consider this a very serious bug, it's just one series after all. I just thought; I'm on the beta version of the addon (it didn't offer videos on any other versions of the addon either), and everything else is working fine. This is an amazon original, it seems likely there will be more videos with whatever is going on here.

**Comment by Sandmann79** [comment] 2022-03-12 07:19
Duplicate of #607
That's a common bug with the old api. 
By enabling the Web Api feature at addon settings, this issue should gone.

For more information, look at the issue mentioned above.

**Closed by Sandmann79** 2022-03-12 07:19 UTC
