### ISSUE TITLE
cannot access watchlist in amazon plugin - Login failure in addon settings 

### ISSUE THREAD

**Issue by trivialist123** [Sandmann79/xbmc#372] opened 2019-11-28 23:02 UTC
**Addon used**
- [ ] Amazon VOD (plugin.video.amazon-test)
- [x] Amazon (plugin.video.amazon)
- [ ] Browser Launcher (plugin.program.browser.launcher)
- Addon Version [2.0.6]

**Prime Video Account (select one)**
- [ ] primevideo.com
- [x] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: [RPi 4]
- OS Version: [LibreElec(official) 9.2.0]
- Kodi Version [18.5]

**Describe the bug**
The Addon was working for a couple of days and then suddenly stopped.
Now, after setting up username and password in Addon Settings and then accessing the Watchlist it says "Login Failure" and doesn't load the watchlist.

kodi.log: 
NOTICE: [Amazon] Args: {'url': 'watchlist', 'page': '1', 'sitemode': 'ListMenu', 'mode': 'appfeed', 'name': 'Watchlist'}
ERROR: GetDirectory - Error getting plugin://plugin.video.amazon/?mode=appfeed&name=Filme&opt&page=1&sitemode=ListCont&url=%2fgp%2fvide>
ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.amazon/?mode=appfeed&name=Filme&opt&page=1&sitemode=ListCont&url=%2fgp%2fvid>
ERROR: /storage/.kodi/addons/script.module.beautifulsoup4/lib/bs4/element.py:16: UserWarning: The soupsieve package is not installed. 
'The soupsieve package is not installed. CSS selectors cannot be used.'

**Comment by Sandmann79** [comment] 2019-11-29 05:16
Duplicate of #352.

**Closed by Sandmann79** 2019-11-29 05:16 UTC
