### ISSUE TITLE
amazon prime can not play movie

### ISSUE THREAD

**Issue by riker65** [Sandmann79/xbmc#63] opened 2018-01-19 12:03 UTC
Hava an error watching amazon prime.
was running perfect the other day.?

error saying;: can not play file in osmc kodie 18

08:58:35.900 T:1192223488   ERROR: AddOnLog: InputStream Adaptive: Unable to find license;hdcpEnforcementResolutionPixels in JSON string
08:58:35.900 T:1192223488   ERROR: AddOnLog: InputStream Adaptive: License update not successful (no keys)
08:58:35.900 T:1192223488   ERROR: AddOnLog: InputStream Adaptive: Initialize failed (SingleSampleDecrypter)
08:58:35.901 T:1192223488   ERROR: CVideoPlayer::OpenInputStream - error opening [https://11s3.lvlt.dash.eu.aiv-cdn.net/d/2$-KMwuKNJa_7DAA7PPefFNnejsrA~/prod/d43c/8fce/63b7/4770-834b-8285b1f00171/8a5c8234-ed4a-4dff-ae68-b4262420da04_corrected.mpd]

**Comment by RobbesU** [comment] 2018-01-19 15:52
Hi riker, see previous [query](https://github.com/Sandmann79/xbmc/issues/62). Issue occurred 3 days ago and appears due to change (by Amazon) in the widevine engine.

**Comment by sindbard** [comment] 2018-01-19 17:04
I wrote yesterday, i have the same Problem

Here is my log:
17:14:46.744 T:1789916048  NOTICE: PVR Manager: Starting
17:14:46.756 T:1641018256  NOTICE: PVR Manager: Started
17:14:46.769 T:1789916048  NOTICE: Start - EPG thread started
17:14:48.256 T:1819534224  NOTICE: [plugin.video.youtube] Startup: detected Krypton (Kodi-18.0), setting DASH_SUPPORT_BUILTIN = False, DASH_SUPPORT_ADDON = True
17:14:57.018 T:1597997968  NOTICE: VNCServer SimKey: keys:35 ext:415 but:16 rel:0 abs:2 m_deviceType:d bits:101110
17:16:18.430 T:1942924448  NOTICE: NFS is idle. Closing the remaining connections.
17:20:36.319 T:1838150544   ERROR: GetDirectory - Error getting
17:20:37.756 T:1556083600   ERROR: Previous line repeats 6 times.
17:20:37.756 T:1556083600  NOTICE: [Amazon VOD] {}
17:20:37.756 T:1556083600  NOTICE: [Amazon VOD] Version: 0.4.7
17:20:37.756 T:1556083600  NOTICE: [Amazon VOD] Unicode support: False
17:20:41.110 T:1556083600  NOTICE: [Amazon VOD] {'page': '1', 'mode': 'Search', 'cat': 'Browse'}
17:20:52.847 T:1556083600  NOTICE: [Amazon VOD] getURL: https://atv-ps-eu.amazon.de/cdp/catalog/Search?firmware=fmw:17-app:2.0.45.1210&deviceTypeID=A2M4YX06LWP8WI&deviceID=b6e02224f77ac4ee29d543f291b46958a95c896ab64f8a2493174f5d&format=json&version=2&formatVersion=3&marketplaceId=A1PA6795UKMFR9&IncludeAll=T&AID=1&searchString=juras&OfferGroups=B0043YVHMY&NumberOfResults=40&StartIndex=0&Detailed$
17:20:55.767 T:1547694992  NOTICE: [Amazon VOD] {'mode': 'checkMissing'}
17:20:55.767 T:1547694992  NOTICE: [Amazon VOD] Starting Fanart Update
17:20:55.768 T:1547694992  NOTICE: [Amazon VOD] searching fanart for JURASSIC PARK at tmdb.com
17:20:56.025 T:1547694992  NOTICE: [Amazon VOD] searching fanart for JURASSIC PARK 2 - VERGESSENE WELT at tmdb.com
17:20:56.276 T:1547694992  NOTICE: [Amazon VOD] searching fanart for JURASSIC PARK III at tmdb.com
17:20:56.529 T:1547694992  NOTICE: [Amazon VOD] searching fanart for BETTY ANNE WATERS at tmdb.com
17:20:56.792 T:1547694992  NOTICE: [Amazon VOD] searching fanart for LIVE DIE REPEAT: EDGE OF TOMORROW at tmdb.com
17:20:57.367 T:1547694992  NOTICE: [Amazon VOD] searching fanart for THE GIRLFRIEND EXPERIENCE at thetvdb.com
17:20:57.858 T:1556083600  NOTICE: [Amazon VOD] {'asin': 'B00FYUQ9IS', 'name': 'Jurassic Park', 'mode': 'PlayVideo', 'selbitrate': '0', 'trailer': '0', 'adult': '0'}
17:20:57.883 T:1556083600  NOTICE: [Amazon VOD] getURL: https://www.amazon.de/gp/deal/ajax/getNotifierResources.html
17:20:58.069 T:1556083600  NOTICE: [Amazon VOD] getURL: https://www.amazon.de/gp/video/streaming/player-token.json?callback=onWebToken_423
17:20:58.231 T:1556083600  NOTICE: [Amazon VOD] getURL: https://atv-ps-eu.amazon.de/cdp/catalog/GetPlaybackResources?asin=B00FYUQ9IS&deviceTypeID=AOAGZA014O5RE&firmware=1&deviceID=b6e02224f77ac4ee29d543f291b46958a95c896ab64f8a2493174f5d&marketplaceID=A1PA6795UKMFR9&format=json&version=1&resourceUsage=ImmediateConsumption&consumptionType=Streaming&deviceDrmOverride=CENC&deviceStreamingTechnology$
17:20:58.493 T:1556083600  NOTICE: [Amazon VOD] Using Host: Cloudfront
17:20:58.493 T:1556083600  NOTICE: [Amazon VOD] checkURL: https://d1l0nb3g075aoz.cloudfront.net/dm/2$-KMwuKNJa_7DAA7PPefFNnejsrA~/5c4e/81a5/109b/4533-9d03-d1e0b5831ba5/dbabf7c9-dd2f-4b1b-8ef7-626ea6d39976_corrected.mpd
17:20:58.867 T:1547694992  NOTICE: [Amazon VOD] getURL: https://atv-ps-eu.amazon.de/cdp/catalog/GetASINDetails?firmware=fmw:17-app:2.0.45.1210&deviceTypeID=A2M4YX06LWP8WI&deviceID=b6e02224f77ac4ee29d543f291b46958a95c896ab64f8a2493174f5d&format=json&version=2&formatVersion=3&marketplaceId=A1PA6795UKMFR9&IncludeAll=T&AID=1&ASINList=B01H44XKSI
17:20:59.086 T:1547694992  NOTICE: [Amazon VOD] searching fanart for FLAVOURS OF SCOTLAND at thetvdb.com
17:20:59.113 T:1556083600  NOTICE: [Amazon VOD] getURL: https://d1l0nb3g075aoz.cloudfront.net/dm/2$-KMwuKNJa_7DAA7PPefFNnejsrA/5c4e/81a5/109b/4533-9d03-d1e0b5831ba5/dbabf7c9-dd2f-4b1b-8ef7-626ea6d39976_corrected.mpd
17:20:59.455 T:1547694992  NOTICE: [Amazon VOD] searching fanart for FLAVOURS OF SCOTLAND at tmdb.com
17:20:59.679 T:1547694992  NOTICE: [Amazon VOD] getURL: https://atv-ps-eu.amazon.de/cdp/catalog/GetASINDetails?firmware=fmw:17-app:2.0.45.1210&deviceTypeID=A2M4YX06LWP8WI&deviceID=b6e02224f77ac4ee29d543f291b46958a95c896ab64f8a2493174f5d&format=json&version=2&formatVersion=3&marketplaceId=A1PA6795UKMFR9&IncludeAll=T&AID=1&ASINList=B01IU7KJJ6
17:20:59.888 T:1547694992  NOTICE: [Amazon VOD] searching fanart for TASTING NOTES at thetvdb.com
17:21:00.232 T:1547694992  NOTICE: [Amazon VOD] searching fanart for TASTING NOTES at tmdb.com
17:21:00.463 T:1547694992  NOTICE: [Amazon VOD] getURL: https://atv-ps-eu.amazon.de/cdp/catalog/GetASINDetails?firmware=fmw:17-app:2.0.45.1210&deviceTypeID=A2M4YX06LWP8WI&deviceID=b6e02224f77ac4ee29d543f291b46958a95c896ab64f8a2493174f5d&format=json&version=2&formatVersion=3&marketplaceId=A1PA6795UKMFR9&IncludeAll=T&AID=1&ASINList=B01M9E5O2F
17:21:00.678 T:1547694992  NOTICE: [Amazon VOD] searching fanart for EMMAS WELT at thetvdb.com
17:21:01.026 T:1547694992  NOTICE: [Amazon VOD] searching fanart for EMMAS WELT at tmdb.com
17:21:01.033 T:1556083600  NOTICE: [Amazon VOD] https://d1l0nb3g075aoz.cloudfront.net/dm/2$-KMwuKNJa_7DAA7PPefFNnejsrA/5c4e/81a5/109b/4533-9d03-d1e0b5831ba5/dbabf7c9-dd2f-4b1b-8ef7-626ea6d39976_corrected.mpd
17:21:01.048 T:1556083600  NOTICE: [Amazon VOD] Using inputstream.adaptive Version:999.2.1.11
17:21:01.146 T:1556083600  NOTICE: [Amazon VOD] Checking AudioTrack
17:21:01.181 T:1942924448  NOTICE: VideoPlayer::OpenFile: https://d1l0nb3g075aoz.cloudfront.net/dm/2$-KMwuKNJa_7DAA7PPefFNnejsrA/5c4e/81a5/109b/4533-9d03-d1e0b5831ba5/dbabf7c9-dd2f-4b1b-8ef7-626ea6d39976_corrected.mpd
17:21:01.182 T:1506309008  NOTICE: Creating InputStream
17:21:01.266 T:1547694992  NOTICE: [Amazon VOD] getURL: https://atv-ps-eu.amazon.de/cdp/catalog/GetASINDetails?firmware=fmw:17-app:2.0.45.1210&deviceTypeID=A2M4YX06LWP8WI&deviceID=b6e02224f77ac4ee29d543f291b46958a95c896ab64f8a2493174f5d&format=json&version=2&formatVersion=3&marketplaceId=A1PA6795UKMFR9&IncludeAll=T&AID=1&ASINList=B01MS1XNME
17:21:01.346 T:1556083600  NOTICE: [Amazon VOD] Player Starting: 0.0/0.0
17:21:01.485 T:1547694992  NOTICE: [Amazon VOD] searching fanart for MODEL RAILWAY LAYOUT : CLUB FERROVIAIRE DE FRANCHE-COMTÃ© at tmdb.com
17:21:02.600 T:1547694992  NOTICE: [Amazon VOD] Finished Fanart Update
17:21:02.717 T:1556083600  NOTICE: [Amazon VOD] Player Caching: 0.0/0.0
17:21:02.741 T:1556083600  NOTICE: [Amazon VOD] Player Resuming: 0.0/0.0
17:21:02.742 T:1556083600  NOTICE: [Amazon VOD] Codec: Samplerate:0 Channels:I()R(1)
17:21:02.952 T:1506309008   ERROR: Interface_Filesystem::get_property_values - invalid data (addon='0x61d66430', file='0x61d6a478')
17:21:03.598 T:1506309008   ERROR: AddOnLog: InputStream Adaptive: Unable to load widevine shared library (/storage/.kodi/cdm/libwidevinecdm.so)
17:21:03.598 T:1506309008   ERROR: AddOnLog: InputStream Adaptive: OpenDRMSystem failed
17:21:03.600 T:1506309008   ERROR: CVideoPlayer::OpenInputStream - error opening [https://d1l0nb3g075aoz.cloudfront.net/dm/2$-KMwuKNJa_7DAA7PPefFNnejsrA/5c4e/81a5/109b/4533-9d03-d1e0b5831ba5/dbabf7c9-dd2f-4b1b-8ef7-626ea6d39976_corrected.mpd]
17:21:03.600 T:1506309008  NOTICE: CVideoPlayer::OnExit()
17:21:08.441 T:1942924448 WARNING: CGUIWindowManager - HandleAction - ignoring action 107, because topmost modal dialog closing animation is running

**Comment by Sandmann79** [comment] 2018-01-20 08:18
Duplicate of #62, closing this.

**Closed by Sandmann79** 2018-01-20 08:18 UTC
