### ISSUE TITLE
TV shows empty, some only show like it is a movie and play first episode, error hit refresh

### ISSUE THREAD

**Issue by fjdpina** [Sandmann79/xbmc#303] opened 2019-04-24 23:52 UTC
I having this three problens.
First of all, I'm using Kodi 18.1 in a RPi3B+, retropie 4.4.11, Amazon VOD 0.7.1. The playback is with input stream addon
I'm in Brazil location.
I tried clean the cache and the catalog & videodata /opt/retropie/configs/ports/kodi/userdata/addon_data/plugin.video.amazon-test files
Tried differents fresh install, fresh install in kodi, in the addon, tried older version (I could not make it work).
I see a lot of movies whit no problem.
My problem is with TV shows, like supernatural, it seem like a movie and play only the first episode.
In Tv show like American God, show 2 season, all the seasons are empty inside, when I try to refresh apear a error.
The log is attach
[kodi.log](https://github.com/Sandmann79/xbmc/files/3114564/kodi.log)
https://paste.kodi.tv/okiwumuwaj.kodi

**Comment by Varstahl** [comment] 2019-04-27 18:57
Duplicate of #290, fixed today.

**Comment by fjdpina** [comment] 2019-04-28 21:10
It isn't duplicate, I tried the solution of 290 and still have the problem and apear another problem.
[kodi.log](https://github.com/Sandmann79/xbmc/files/3125496/kodi.log)

**Comment by Varstahl** [comment] 2019-04-29 06:54
You're using pt_BZ, correct?

**Closed** 2019-04-29 07:05 UTC
Labels: bug

**Comment by fjdpina** [comment] 2019-04-29 11:08
Yes, is there any problem with pt_BZ?

**Comment by Varstahl** [comment] 2019-04-29 11:58
There was, they changed some stuff up. Now it should be working, I published a new release version this morning.

**Comment by fjdpina** [comment] 2019-04-29 21:59
Is working now, Thank you very much
