### ISSUE TITLE
Watchlist: Error Contents: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by haggaie** [Sandmann79/xbmc#191] opened 2018-10-16 18:22 UTC
Hi,

When I try to load my TV shows watchlist in the addon, I get the following error in the log:
```
21:13:24.406 T:139775543666432   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'group'
                                            Traceback (most recent call last):
                                              File "/home/haggai/.kodi/addons/plugin.video.amazon-test/default.py", line 5, in <module>
                                                EntryPoint()
                                              File "/home/haggai/.kodi/addons/plugin.video.amazon-test/resources/lib/startup.py", line 83, in EntryPoint
                                                g.pv.Browse(None if 'path' not in args else args['path'])
                                              File "/home/haggai/.kodi/addons/plugin.video.amazon-test/resources/lib/primevideo.py", line 185, in Browse
                                                self._LazyLoad(node, nodeName)
                                              File "/home/haggai/.kodi/addons/plugin.video.amazon-test/resources/lib/primevideo.py", line 640, in _LazyLoad
                                                self._videodata[refUrn]['title'] = Unescape(title.group(1))
                                            AttributeError: 'NoneType' object has no attribute 'group'
                                            -->End of Python script error report<--

```

This happens when parsing this URL: https://www.primevideo.com/detail/0JCABD3LKRM30CSG0FUUHB6DWC/ which as far as I can see doesn't have the classes the code searches for (av-season-single or av-select-trigger). I'd be happy to add some alternative class to the code but I'm not sure what I should be looking for (the show title? season name? season dropdown?)

**Comment by Varstahl** [comment] 2018-10-16 18:49
If you see the av-season whatever, then you're experiencing an older version of PrimeVideo. It's already been reported and the causes are unknown. A probable fix could be reverting to 0.5.7, [instructions here](https://github.com/Sandmann79/xbmc/issues/176#issuecomment-426745485).

**Comment by haggaie** [comment] 2018-10-18 18:53
Thanks. I tried using the version currently on master and it worked.

**Comment by Varstahl** [comment] 2018-10-18 19:01
**OUCH**, you're correct, I forgot to push the updates! :|

I thought 0.5.9 already had all fixes \*facepalm\*

**Comment by timewolf** [comment] 2018-10-18 21:17
even with 0.5.9 i've the same issue...

23:16:54.383 T:6956  NOTICE: [Amazon VOD] Version: 0.5.9
23:16:54.383 T:6956  NOTICE: [Amazon VOD] Unicode filename support: True
23:16:54.384 T:6956  NOTICE: [Amazon VOD] Locale: it-it / Language: en
23:17:00.757 T:6956  NOTICE: [Amazon VOD] postURL: https://atv-ps-eu.primevideo.com/cdp/catalog/GetPlaybackResources?asin=amzn1.dv.gti.56b2af4a-833b-5d9e-32be-368db8e46fab&deviceTypeID=AOAGZA014O5RE&firmware=1&deviceID=f4f5ccbe438b7a2a6e8a64afeaf3d9f08e7c0c89078ed604d4a0c009&marketplaceID=A3K6Y4MI8GDYMT&format=json&version=1&gascEnabled=true&resourceUsage=ImmediateConsumption&consumptionType=Streaming&deviceDrmOverride=CENC&deviceStreamingTechnologyOverride=DASH&deviceProtocolOverride=Https&deviceBitrateAdaptationsOverride=CVBR%2CCBR&audioTrackId=all&videoMaterialType=Feature&desiredResources=CatalogMetadata&titleDecorationScheme=primary-content
23:17:01.169 T:6956   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'group'
                                            Traceback (most recent call last):
                                              File "d:\Users\fabio\AppData\Roaming\Kodi\addons\plugin.video.amazon-test\default.py", line 5, in <module>
                                                EntryPoint()
                                              File "d:\Users\fabio\AppData\Roaming\Kodi\addons\plugin.video.amazon-test\resources\lib\startup.py", line 83, in EntryPoint
                                                g.pv.Browse(None if 'path' not in args else args['path'])
                                              File "d:\Users\fabio\AppData\Roaming\Kodi\addons\plugin.video.amazon-test\resources\lib\primevideo.py", line 185, in Browse
                                                self._LazyLoad(node, nodeName)
                                              File "d:\Users\fabio\AppData\Roaming\Kodi\addons\plugin.video.amazon-test\resources\lib\primevideo.py", line 640, in _LazyLoad
                                                self._videodata[refUrn]['title'] = Unescape(title.group(1))
                                            AttributeError: 'NoneType' object has no attribute 'group'
                                            -->End of Python script error report<--
23:17:01.201 T:6956 WARNING: CPythonInvoker(2, d:\Users\fabio\AppData\Roaming\Kodi\addons\plugin.video.amazon-test\default.py): the python script "d:\Users\fabio\AppData\Roaming\Kodi\addons\plugin.video.amazon-test\default.py" has left several classes in memory that we couldn't clean up. The classes include: class XBMCAddon::xbmcgui::Dialog,class XBMCAddon::xbmcaddon::Addon
23:17:01.207 T:4528   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.amazon-test/?mode=PrimeVideo_Browse&path=root-%2f%2f-Serie%20TV
23:17:01.208 T:4852   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.amazon-test/?mode=PrimeVideo_Browse&path=root-%2f%2f-Serie%20TV) failed
23:17:01.747 T:3324  NOTICE: [Amazon VOD] Version: 0.5.9
23:17:01.747 T:3324  NOTICE: [Amazon VOD] Unicode filename support: True
23:17:01.747 T:3324  NOTICE: [Amazon VOD] Locale: it-it / Language: en
23:17:02.678 T:4852  NOTICE: stop player

**Comment by Varstahl** [comment] 2018-10-18 22:05
Replace primevideo.py with the one from master. I forgot to push the update which I thought was already released with 0.5.9.

**Comment by timewolf** [comment] 2018-10-19 00:17
ok replaced thanks... now it's better, but i cannot playback any video via inputstream
it crash

0:04:38.093 T:18446744072051075968  NOTICE: [Amazon VOD] Service: Start
00:04:38.109 T:18446744072051075968  NOTICE: [Amazon VOD] Service: End
00:04:38.163 T:18446744072051075968 WARNING: CPythonInvoker(1, /mnt/sdcard/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.amazon-test/service.py): the python script "/mnt/sdcard/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.amazon-test/service.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE,N9XBMCAddon7xbmcgui6DialogE
00:04:58.287 T:18446744072114067072   ERROR: GetDirectory - Error getting
00:05:02.134 T:18446744071997526784   ERROR: Previous line repeats 6 times.
00:05:02.134 T:18446744071997526784  NOTICE: [Amazon VOD] Version: 0.5.9
00:05:02.135 T:18446744071997526784  NOTICE: [Amazon VOD] Unicode filename support: False
00:05:02.136 T:18446744071997526784  NOTICE: [Amazon VOD] Locale: en-gb / Language: en
00:05:08.917 T:18446744071997526784  NOTICE: [Amazon VOD] postURL: https://atv-ps-eu.primevideo.com/cdp/catalog/GetPlaybackResources?asin=amzn1.dv.gti.68b2af50-8785-37b2-e65a-1182e11651ca&deviceTypeID=AOAGZA014O5RE&firmware=1&deviceID=6d8a426a9743b13a7fb7391521d8bcf2f6d602383cd7bd9c22eef106&marketplaceID=A3K6Y4MI8GDYMT&format=json&version=1&gascEnabled=true&resourceUsage=ImmediateConsumption&consumptionType=Streaming&deviceDrmOverride=CENC&deviceStreamingTechnologyOverride=DASH&deviceProtocolOverride=Https&deviceBitrateAdaptationsOverride=CVBR%2CCBR&audioTrackId=all&videoMaterialType=Feature&desiredResources=PlaybackUrls,SubtitleUrls,ForcedNarratives
00:05:13.071 T:18446744071997526784  NOTICE: [Amazon VOD] Using Host: Cloudfront
00:05:13.074 T:18446744071997526784  NOTICE: [Amazon VOD] checkURL: https://s3-dub.cf.dash.row.aiv-cdn.net/dm/2$VezXPyzsfj07e-Qm65WfyuJ14SA~/6886/9b0a/6d31/469b-ad73-2a13f5e28c61/71ca2398-f9e5-4cdd-ac2f-b9c09d28f632_corrected.mpd
00:05:14.653 T:18446744071997526784  NOTICE: [Amazon VOD] Using inputstream.adaptive Version: 2.2.27
00:05:14.776 T:18446744072116945664  NOTICE: VideoPlayer::OpenFile: plugin://plugin.video.amazon-test/?mode=PrimeVideo_Browse&path=root-%2F%2F-Watchlist-%2F%2F-Serie+TV-%2F%2F-amzn1.dv.gti.dcae96d5-f0ab-159e-44d3-9200e3679084-%2F%2F-0IMOE9I1H3BN74ON17M9XGZFPG-//-0LCR19MSFAH5MOTQY6JBB5KMVE
00:05:14.779 T:18446744072006421248  NOTICE: Creating InputStream
00:05:15.070 T:18446744072006421248   ERROR: AddOnLog: InputStream Adaptive: Key system request: com.widevine.alpha
00:05:24.128 T:18446744072051078528   ERROR: SOCK: Error selecting socket(s)
00:05:24.129 T:18446744072051078528   ERROR: ES: Exception caught while listening for socket
00:05:24.129 T:18446744072051078528  NOTICE: ES: UDP Event server stopped

**Comment by timewolf** [comment] 2018-10-19 08:52
Very strange with the same connection a Windows PC works, 2 different Android boxes no

**Comment by Varstahl** [comment] 2018-10-19 11:30
Update pushed with 0.6.0, e75b735bfc8cccfa9ef9ef05801612d0e49b002d.

**Closed by Varstahl** 2018-10-19 11:30 UTC
