### ISSUE TITLE
404 when trying to view watchlist

### ISSUE THREAD

**Issue by TimMagee** [Sandmann79/xbmc#677] opened 2023-03-24 18:59 UTC
**Addon used**
- [x] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 0.0.6+matrix.1

**Account type**
- [x] primevideo.com
- [ ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: RockPro64
- OS version: LibreElec 11.0.0
- Kodi version number: 29.9.9

**Upload Logs**
https://pastebin.com/wy0TLmEZ

**Describe the bug**
Loading the "Movies" or "Televison" section of the Prime Video addon does not work and throws an error.

I included the relevant log portion.

**Comment by Sandmann79** [comment] 2023-03-24 20:02
Duplicate of #660. The old API has been discontinued by Amazon. Due to changes to drf Amazon website, only the current beta versions of the addon work, which must be installed manually. Download it here:
The old API has been discontinued by Amazon. Due to changes to drf Amazon website, only the current beta versions of the addon work, which must be installed manually. 
Download here: The old API has been discontinued by Amazon. Due to changes to drf Amazon website, only the current beta versions of the addon work, which must be installed manually. Download here: The old API has been discontinued by Amazon. Due to changes to drf Amazon website, only the current beta versions of the addon work, which must be installed manually.
For download see issue #674

**Closed by Sandmann79** 2023-03-24 20:02 UTC
