### ISSUE TITLE
Bought content (Series) not showing up

### ISSUE THREAD

**Issue by hastingdevil81** [Sandmann79/xbmc#257] opened 2019-02-12 08:16 UTC
I configured my account in the Plugin and i can see some of my series that are in the watchlist (mainly the ones that are included in Prime)  but when it comes to series that i bought entire seasons (and that are shown on the amazon firetv stick) i can´t find them neither in the library or in the watchlist or even searching for them (particulary the Game of Thrones seasons)

What is the problem here? will this be fixed?

**Comment by Varstahl** [comment] 2019-02-12 08:34
I'm not aware of any similar problems.

* Are you a primevideo.com user, or amazon.tlds (DE/JP/UK/US)?
* What addon do you have installed?

**Comment by hastingdevil81** [comment] 2019-02-12 08:48
im a amazon (DE) user.
I installed the one through the Sandman Repository, The one that is specialized for Amazon germany

**Comment by Varstahl** [comment] 2019-02-12 08:52
Ok, then I can't really help much. What I know about that plugin is that it runs a scraping in the background, so if something went wrong you can try to select "Rebuild library" through the options, and let it sit there for a few hours unused while it updates the list, then it should work. I'm unsure if it also works in the background while just watching something else.

**Comment by hastingdevil81** [comment] 2019-02-12 08:53
will try and report back  thanks

**Comment by hastingdevil81** [comment] 2019-02-15 09:18
Ok sorry for the wait.
i tried that  and it didn´t work. what i did then was to install the other Amazon VOD plugin. and with that i can see my bought content which is weird. but i´m having issues with freezes/stutter/ black screen but audio in the middle of an episode f.e.

**Comment by Varstahl** [comment] 2019-02-18 18:00
You're not the first user reporting issues with the amazon addon, but since I don't have access to amazon.tlds accounts I can't test it. Also, Amazon VOD is reportedly working for a lot of users now that the other addon is kind of failing. And, again, you're not the first to report freezes/stutters with Amazon VOD, although that is weird since it should be about the same as the other addon.

The only one who could answer this questions is Sandmann, but he's currently unavailable.

**Comment by bread-on-toast** [comment] 2019-11-19 22:29
I can confirm that this is an issue. Paid TV content won't show up. Not even when searching for Videos outside the Watchlist. (amazon.de, germany, pluginversion 2.0.4)

**Comment by Sandmann79** [comment] 2019-11-20 11:29
@bread-on-toast this addon doesn't displaing paid content, except already bought content, which is avaible through Amazon library. To See it, you have to use the most recent Version 2.0.5, there are some fixed regarding the Database Update included. After updating start the Database Update and wait till finished.

**Comment by Varstahl** [comment] 2020-05-07 17:15
Closing this as the addon's deprecated by now.

**Closed by Varstahl** 2020-05-07 17:15 UTC
Labels: amazon.tld
