### ISSUE TITLE
Amazon VOD - 404 Errors

### ISSUE THREAD

**Issue by cow-crash** [Sandmann79/xbmc#662] opened 2022-12-08 14:28 UTC
**Addon used**
- [x] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 0.9.6

**Account type**
- [x] primevideo.com
- [ ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: raspberry pi 3
- OS version: libreelec 9.2.8
- Kodi version number: 18.9 leia

**Upload Logs**
https://paste.kodi.tv/uxunaxixey.kodi

**Describe the bug**

With web.api disabled i've seen all my watchlist entries until few days ago. Now i get an error (shown in the given log) on opening the 'series'  entry in watchlist. Opening another entry  like '/films/all movies'  shows '..' (empty list). Few days ago i've seen many film entries there. For the serie ' periphals' i've seen all episodes there.
With web.api enabled i find most film and series, but for serie 'periphals' only the first 3 episodes are shown (must ge 8).
Has amazon changed something in their layout, that the 'non web.api' part cannot process?
Could it fixed?
best regards
Holger

**Comment by agausmann** [comment] 2022-12-09 03:03
I think this is related to #660

**Comment by alexlancaster** [comment] 2022-12-10 06:16
This is the same issue as #660.  I was also able to access videos with the webapi setting up to a few days ago.  now it stopped working completely for anything. I think Amazon is messing around with things behind the scenes.

**Comment by cow-crash** [comment] 2022-12-10 08:52
> 

On my raspberry app with enabled web.api is still functional

**Comment by Sandmann79** [comment] 2023-03-04 15:01
Duplicate of #660. Closing

**Closed by Sandmann79** 2023-03-04 15:01 UTC
