### ISSUE TITLE
Unable tu play video: exceptions.KeyError in primevideo.py

### ISSUE THREAD

**Issue by hansipet** [Sandmann79/xbmc#221] opened 2018-12-26 14:39 UTC
When using the Amazon VOD plugin I get allways the following error. This is a log file for windows. But I have tried it on different devices and I get allways this error. I have an Amazon Prime Account in Italy.

15:20:05.468 T:10512   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: u'Action \u2013 '
                                            Traceback (most recent call last):
                                              File "C:\Users\hansi\AppData\Roaming\Kodi\addons\plugin.video.amazon-test\default.py", line 5, in <module>
                                                EntryPoint()
                                              File "C:\Users\hansi\AppData\Roaming\Kodi\addons\plugin.video.amazon-test\resources\lib\startup.py", line 83, in EntryPoint
                                                g.pv.Browse(None if 'path' not in args else args['path'])
                                              File "C:\Users\hansi\AppData\Roaming\Kodi\addons\plugin.video.amazon-test\resources\lib\primevideo.py", line 181, in Browse
                                                node = node[n]
                                            KeyError: u'Action \u2013 '
                                            -->End of Python script error report<--
[kodi.log](https://github.com/Sandmann79/xbmc/files/2710390/kodi.log)

**Comment by Varstahl** [comment] 2018-12-26 16:52
Il problema dovrebbe essere risolto da un bel pezzo. 
* Da quanto hai il problema?
* Versione di Kodi?
* Versione di Amazon VOD?
* Versione di Win?
* Provato a cancellare i *.pv?p da `%AppData%\Kodi\userdata\addon_data\plugin.video.amazon-test`?

**Comment by hansipet** [comment] 2018-12-26 17:10
I use Kodi 18.0-RC3. It is a fresh installation

plugin.video.amazon-test v0.6.3 installed
repository.kodinerds v6.0.0 installed
repository.sandmann79.plugins v1.0.2 installed

Win 10.0.17134

I have canceled the *.pv files

**Comment by Varstahl** [comment] 2018-12-26 18:58
Hmm, come to think of it there's something wrong. Do you have a VPN? Are you not in Italy right now?

**Comment by hansipet** [comment] 2018-12-27 13:55
I have no vpn.maybe one special thing is,that as language I have set german

**Comment by Varstahl** [comment] 2018-12-27 15:11
That sholdn't be the issue, although I received another complaint so I'm investigating further.

Could you kindly attach your `%AppData%\Kodi\userdata\addon_data\plugin.video.amazon-test\PVCatalog[ID].pvcp` to a reply in here? Thanks in advance.

**Comment by Varstahl** [comment] 2018-12-27 15:52
@redcloverphoenix, @hansipet I'm unable to reproduce your problem in any way, shape or form. I even tried to break my own code, but the damned thing still works. I need you two to open up a browser, go to
[https://www.primevideo.com/storefront/movie/](https://www.primevideo.com/storefront/movie/), save the file as html and attach it here. Everything should be fixed, I can't seem to break it, I must find what's causing the issues, I'm at a complete loss.

**Comment by hansipet** [comment] 2018-12-27 16:40
Here are the files. 
[files.zip](https://github.com/Sandmann79/xbmc/files/2712905/files.zip)

**Comment by redcloverphoenix** [comment] 2018-12-27 16:40
How can I open up a browser? I’m using OSMC on a RaspberryPi and the video plays fine if I search for the title then play it. It brings up this error if I try to play the title from browsing different categories.

**Comment by Varstahl** [comment] 2018-12-27 16:45
@redcloverphoenix doesn't have to be on OSMC, you can load up the website from your computer, it doesn't matter where.

@hansipet thanks for the files, I'll take a look asap.

**Comment by redcloverphoenix** [comment] 2018-12-27 17:03
Sure. 
[movie.zip](https://github.com/Sandmann79/xbmc/files/2712930/movie.zip)

**Comment by Varstahl** [comment] 2018-12-27 17:41
@redcloverphoenix after you load the page, I need you to scroll down to load the entire categories list. There are a lot of things dynamically loaded that are missing from that html. Sorry about that, I forgot to mention.

The good news is, you're both experiencing the same problem:

![hansipet](https://user-images.githubusercontent.com/284077/50489237-cc966280-0a06-11e9-837e-f933d5386221.jpg)

The bad news is, I still have absolutely no idea why, or how.

The other good news is, if I receive a complete file from @redcloverphoenix I might figure it out. @hansipet data was useful, but since it's amazon.tld it's outside of my expertise.

**Comment by redcloverphoenix** [comment] 2018-12-27 19:04
[movie.zip](https://github.com/Sandmann79/xbmc/files/2713125/movie.zip)
So this?

**Comment by Varstahl** [comment] 2018-12-27 19:31
Hmmm… when you open the html it's still missing content.

![74375c87-3060-44d9-b132-141ceaaab2a4](https://user-images.githubusercontent.com/284077/50492148-4255fa80-0a16-11e9-9873-0fc177d39be5.png)

At times like this I hate amazon's frontends :\

**Comment by Varstahl** [comment] 2018-12-28 13:58
I ask your pardon, you're absolutely right, I was working on multiple things yesterday and got confused. But the point still stands in the sense that neither of your files has the "broken" categories in them.

I don't know why is that, but I can't find the problem without the problematic part.

**Comment by hansipet** [comment] 2018-12-28 15:33
No problem,maybe I can check it a little bit,but my python knowledge is not big..

**Comment by Varstahl** [comment] 2018-12-28 15:46
Sure thing. My code is quite "unfriendly", but everything you need should be in `PrimeVideo.py`. Taking in consideration the code currently in master, the problematic area should be between rows 739 and 805. If we take in consideration just movie categories, its between 740 and 767.

You can probably find a plethora of information if you add right before [line 752](https://github.com/Sandmann79/xbmc/blob/9d3ae584b7a97c1e3b75941219c1db9e7b0a3498/plugin.video.amazon-test/resources/lib/primevideo.py#L752) the following code, right before the NotifyUser call:

```
                        Log(res)
```

Be mindful of the spaces, since it's python they actually count.

The line above should dump to the log file every single movie category from (https://www.primevideo.com/storefront/movie/](https://www.primevideo.com/storefront/movie/). That is, unless I made a mistake again and I've given you the wrong coordinates :p

**Comment by hansipet** [comment] 2018-12-29 06:34
I have found now the cause of the problem. The problem exists only for some categories:
e.g. the category 'root-//-Filme-//-Action \xe2\x80\x93 & Abenteuer-Filme' does not play. The Problem is here a "-". The name of the category is "Action- & Abenteuer-Filme". I think one of the regular expressions has a problem with the "-"

**Comment by Varstahl** [comment] 2018-12-29 13:45
> I think one of the regular expressions has a problem with the "-"

That's by design, although in that case changing it is quite wrong.

> the category 'root-//-Filme-//-Action \xe2\x80\x93 & Abenteuer-Filme' does not play

Wait, wtf. Is it in the logs literally like this `root-//-Filme-//-Action \xe2\x80\x93 & Abenteuer-Filme`?

Can you find me a couple instances of this in the logs? That shouldn't happen…

**Comment by hansipet** [comment] 2018-12-29 15:06
Yes it is 2 times 
 in the log. You can search for "Abenteuer" and "Familienfilme"

[kodi.log](https://github.com/Sandmann79/xbmc/files/2716484/kodi.log)

**Comment by Varstahl** [comment] 2018-12-29 15:18
```
NOTICE: [Amazon VOD] {'path': 'root-//-Filme-//-Kinder \xe2\x80\x93 & Familienfilme', 'mode': 'PrimeVideo_Browse'}
```
Thanks, this should be it. This is wrong. I'll try to figure out why we have this issue in the first place. I'm fairly sure I escape everything by default, so this should never ever happen.

**Comment by Varstahl** [comment] 2018-12-29 16:32
Thank you so much for all the feedback, this annoying bug should now be squashed once and for all.

**Closed** 2018-12-29 16:31 UTC
Labels: bug

**Comment by senorping** [comment] 2019-01-27 15:50
Dear Contributors,

I still have an issue with german Add-On of Prime Video! I tried manually updating the shared library object. Literally, I tried every proposed solution I found here. So far everything didn't work. However, I attached the full log file to this comment. I am not sure whether this is the right thread. However, when I search for "Amazon" in the log file, it points out that there are errors after calling a function in defaults.py
Help is much appreciated. If it's the wrong thread, plase point me to right one.

Sicerly Hannes aka senorping

16:00:07.739 T:1511265024  NOTICE: [Amazon] ASINS to Remove: [u'B077XNS6X5,B077XL2DPN,B077XPV2L4,B078CY5RG2']
16:00:17.662 T:1511265024  NOTICE: [Amazon] TV Shows Update:
                                            4 Shows added
                                            5 Seasons added, 1 Removed
                                            100 Episodes added, 19 Removed
16:01:55.854 T:1511265024  NOTICE: [Amazon] getURL: https://www.amazon.de/gp/video/video-library/tv/?ie=UTF8&sort=DATE_ADDED_DESC
16:01:56.759 T:1511265024  NOTICE: [Amazon] ASINS to Remove: [u'B01M0K6K7P,B01LXB2T9R,B01M1751KJ,B01M0VJHXJ', u'B00ERNKF2O,B00ERNKFVA,B00ERNKG1O,B00ERNKG4Q', u'B0791LPNPP,B0791L3HXY,B0791LP6JR,B0791LVMJY', u'B0791L42RP,B0791LGKD4,B0791M92W6,B0791M9CGJ', u'B00ERL7NHG,B00ERL7O9S,B00ERL7P9C,B00ERL7Q32']
16:02:01.409 T:1511265024  NOTICE: [Amazon] getURL: https://atv-ps-eu.amazon.de/cdp/catalog/Browse?firmware=fmw:17-app:2.0.45.1210&deviceTypeID=A2M4YX06LWP8WI&deviceID=34a47c216cfc53d398feaabce7089abfb6073d22b9735568e1786440&format=json&StartIndex=0&NumberOfResults=140&ContentType=TVEpisode&RollUpToSeason=T&OrderBy=Title&SeasonASIN=B0776TXQTC,&IncludeBlackList=T&HideNum=T&AID=1&IncludeNonWeb=T&IncludeAll=T&version=2
**16:02:02.088 T:1511265024   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.amazon/default.py", line 52, in <module>
                                                modes()
                                              File "/home/osmc/.kodi/addons/plugin.video.amazon/default.py", line 49, in modes
                                                exec 'sitemodule.%s()' % var.args.get('sitemode')
                                              File "<string>", line 1, in <module>
                                              File "/home/osmc/.kodi/addons/plugin.video.amazon/resources/lib/appfeed.py", line 352, in updateAll
                                                tvresult = tv.addTVdb(False, cj=cj)
                                              File "/home/osmc/.kodi/addons/plugin.video.amazon/resources/lib/tv.py", line 420, in addTVdb
                                                addTVdb(False, 'full', cj)
                                              File "/home/osmc/.kodi/addons/plugin.video.amazon/resources/lib/tv.py", line 352, in addTVdb
                                                season_size = int(title['childTitles'][0]['size'])
                                            IndexError: list index out of range
                                            -->End of Python script error report<--**
16:11:21.891 T:1528296192  NOTICE: ES: Client  from ::ffff:192.168.178.28 timed out
16:15:26.394 T:1925843456   ERROR: SMBDirectory->GetDirectory: Unable to open directory : 'smb://freidis-macbook.fritz.box/'
                                            unix_err:'1' error : 'Operation not permitted'
16:15:28.840 T:1925843456   ERROR: GetDirectory - Error getting smb://freidis-macbook.fritz.box/
16:15:42.115 T:1486099200   ERROR: SMBDirectory->GetDirectory: Unable to open directory : 'smb://freidis-macbook.fritz.box/'
                                            unix_err:'1' error : 'Operation not permitted'
16:15:43.588 T:1925843456   ERROR: GetDirectory - Error getting smb://freidis-macbook.fritz.box/
16:15:43.588 T:1925843456   ERROR: CGUIDialogFileBrowser::GetDirectory(smb://freidis-macbook.fritz.box/) failed
16:16:03.503 T:1486099200   ERROR: SMBDirectory->GetDirectory: Unable to open directory : 'smb://FREIDIS-MACBOOK/'
                                            unix_err:'1' error : 'Operation not permitted'
16:16:05.744 T:1925843456   ERROR: GetDirectory - Error getting smb://FREIDIS-MACBOOK/
16:16:05.744 T:1925843456   ERROR: CGUIDialogFileBrowser::GetDirectory(smb://FREIDIS-MACBOOK/) failed
16:16:55.113 T:1486099200   ERROR: SMBDirectory->GetDirectory: Unable to open directory : 'smb://FREIDIS-MACBOOK/'
                                            unix_err:'1' error : 'Operation not permitted'
16:16:57.078 T:1925843456   ERROR: GetDirectory - Error getting smb://FREIDIS-MACBOOK/
16:16:57.078 T:1925843456   ERROR: CGUIDialogFileBrowser::GetDirectory(smb://FREIDIS-MACBOOK/) failed
16:18:20.966 T:1925843456   ERROR: Control 18 in window 10129 has been asked to focus, but it can't
16:19:46.285 T:1905259264   ERROR: GetDirectory - Error getting
16:19:49.729 T:1696854784   ERROR: Previous line repeats 6 times.
16:19:49.729 T:1696854784  NOTICE: [Amazon] Args: {}
16:19:49.936 T:1696854784  NOTICE: [Amazon] Version: 2.0.1
16:19:49.936 T:1696854784  NOTICE: [Amazon] Unicode filename support: False
16:19:56.642 T:1477710592  NOTICE: [Amazon] Args: {'url': 'watchlist', 'page': '1', 'sitemode': 'ListMenu', 'mode': 'appfeed', 'name': 'Watchlist'}
16:20:02.117 T:1469321984  NOTICE: [Amazon] Args: {'url': '/gp/video/watchlist/movie/', 'page': '1', 'sitemode': 'ListCont', 'mode': 'appfeed', 'name': 'Movies'}
16:20:03.297 T:1469321984  NOTICE: [Amazon] getURL: https://www.amazon.de/gp/video/watchlist/movie/?ie=UTF8&sort=DATE_ADDED_DESC
16:20:07.180 T:1494487808   ERROR: CCurlFile::Stat - Failed: HTTP response code said error(22) for http://s3.amazonaws.com/sgp-catalog-images/region_DE/tobis-tobis0050201-Full-Image_GalleryBackground-de-DE-1472678653453._V1_.jpg
16:20:10.989 T:1469321984  NOTICE: [Amazon] Args: {'asin': 'B00FYUJN9U', 'sitemode': 'PLAYVIDEO', 'name': 'Robin Hood', 'mode': 'play', 'trailer': '0', 'adult': '0'}
16:20:33.979 T:1469321984  NOTICE: [Amazon] No Inputstream Addon found or activated
16:20:34.178 T:1925843456   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.amazon/?asin=B00FYUJN9U&sitemode=PLAYVIDEO&mode=play&adult=0&name=Robin+Hood&trailer=0]
16:20:51.217 T:1925843456  NOTICE: stop all

[Logs2019-01-27.txt](https://github.com/Sandmann79/xbmc/files/2800201/Logs2019-01-27.txt)

**Comment by Varstahl** [comment] 2019-01-28 01:39
It is absolutely not the correct thread, as it is both the wrong addon and not PrimeVideo (which refers to primevideo.com, while germany streams from amazon.de). I see a number of issues in the log, but since it's not the code I maintain it's difficult to pinpoint the causes. You can open a new issue with your problem, where people might help you, and also in the meanwhile to check it's not a problem with your end you could try to install the "Amazon VOD" addon from the same repository. It has some less features but works with german accounts as well.
