### ISSUE TITLE
Age restrictions… - Error.

### ISSUE THREAD

**Issue by hevet** [Sandmann79/xbmc#593] opened 2021-11-02 07:47 UTC
I get an error when I try to select age restrictions in the options. Log below.

**Addon used**
- [x] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 0.9.4

**Account type**
- [ ] primevideo.com
- [x] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: PC
- OS version: Windows 10 21H1
- Kodi version number: 18.9

```
Error Type: <type 'exceptions.IndexError'>
Error Contents: string index out of range
Traceback (most recent call last):
    File "C:\Users\jacek\AppData\Roaming\Kodi\addons\plugin.video.amazon-test\default.py", line 5, in <module>
    EntryPoint()
    File "C:\Users\jacek\AppData\Roaming\Kodi\addons\plugin.video.amazon-test\resources\lib\startup.py", line 94, in EntryPoint
    AgeRestrictions().Settings()
    File "C:\Users\jacek\AppData\Roaming\Kodi\addons\plugin.video.amazon-test\resources\lib\ages.py", line 44, in Settings
    _AgeSettings(getString(30018).split('…')[0]).doModal()
    File "C:\Users\jacek\AppData\Roaming\Kodi\addons\plugin.video.amazon-test\resources\lib\ages.py", line 51, in __init__
    self.age_list = [age[0] for age in AgeRestrictions().Ages]
IndexError: string index out of range
-->End of Python script error report<--
```

**Comment by Varstahl** [comment] 2021-11-02 08:53
Strange, are you using Portuguese by any chance?

**Comment by hevet** [comment] 2021-11-02 08:59
No, I use Polish.

**Comment by Varstahl** [comment] 2021-11-02 09:03
Ok then, that's weird, it should work with Polish. Amazon could've changed something, we'll have to look into that.

**Comment by Trillyy** [comment] 2022-05-23 08:36
Hi @Varstahl, I can confirm the same error happening with Italian Prime, I'm restricted to kid account and can't change it in the settings (it crashes on 'Limiti di età...'). The error log is the same in the post, so I avoid posting it here again

Hardware: PC (Intel Celeron N3450 @ 1.10Ghz)
OS version: LibreElec 10.0.2
Kodi version number: 19.4 I think

This issue happened in the last day or so, since I was using your wonderful extension 3-4 days ago without any issues

**Comment by Sandmann79** [comment] 2024-05-05 19:46
Agerestriction feature isn't available anymore. Closing

**Closed by Sandmann79** 2024-05-05 19:46 UTC
Labels: bug
