### ISSUE TITLE
Amazon VOD fails to load after upgrade to 0.9.9 - Exception TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by antibarbie** [Sandmann79/xbmc#711] opened 2023-10-25 20:48 UTC
**Addon used**
- [X] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 0.9.9

**Account type**
- [X] primevideo.com  (amazon.FR)
- [ ] amazon.(com/co.uk/de/jp) 

**System Setup (please provide the following information):**
- Hardware: Kodi / Raspberry pi 4
- OS version: LibreElec 9.2.8
- Kodi version number: 18.9

**Upload Logs**

**Describe the bug**

The plugin won't open, and throws an exception in the log.

[kodi.log](https://github.com/Sandmann79/xbmc/files/13170551/kodi.log)
[logfiles_20231025-211534.zip](https://github.com/Sandmann79/xbmc/files/13170564/logfiles_20231025-211534.zip)

**Comment by antibarbie** [comment] 2023-10-25 21:02
Interesting stuff there (and the actual html page was saved in the zip I think) : 

```
2023-10-25 21:14:46.519 T:2437268288   DEBUG: CPythonInvoker(41, /storage/.kodi/addons/plugin.video.amazon-test/default.py): start processing
2023-10-25 21:14:46.537 T:2437268288   DEBUG: -->Python Interpreter Initialized<--
2023-10-25 21:14:46.537 T:2437268288   DEBUG: CPythonInvoker(41, /storage/.kodi/addons/plugin.video.amazon-test/default.py): the source file to load is "/storage/.kodi/addons/plugin.video.amazon-test/default.py"
2023-10-25 21:14:46.539 T:2437268288   DEBUG: CPythonInvoker(41, /storage/.kodi/addons/plugin.video.amazon-test/default.py): setting the Python path to /storage/.kodi/addons/plugin.video.amazon-test:/storage/.kodi/addons/script.module.beautifulsoup4/lib:/storage/.kodi/addons/script.module.certifi/lib:/storage/.kodi/addons/script.module.chardet/lib:/storage/.kodi/addons/script.module.idna/lib:/storage/.kodi/addons/script.module.inputstreamhelper/lib:/storage/.kodi/addons/script.module.kodi-six/libs:/storage/.kodi/addons/script.module.mechanicalsoup/lib:/storage/.kodi/addons/script.module.pyautogui/lib:/storage/.kodi/addons/script.module.pyxbmct/lib:/storage/.kodi/addons/script.module.requests/lib:/storage/.kodi/addons/script.module.six/lib:/storage/.kodi/addons/script.module.urllib3/lib:/usr/lib/python27.zip:/usr/lib/python2.7:/usr/lib/python2.7/plat-linux2:/usr/lib/python2.7/lib-tk:/usr/lib/python2.7/lib-old:/usr/lib/python2.7/lib-dynload:/usr/lib/python2.7/site-packages:/usr/lib/python2.7/site-packages/gtk-2.0
2023-10-25 21:14:46.539 T:2437268288   DEBUG: CPythonInvoker(41, /storage/.kodi/addons/plugin.video.amazon-test/default.py): entering source directory /storage/.kodi/addons/plugin.video.amazon-test
2023-10-25 21:14:46.539 T:2437268288   DEBUG: CPythonInvoker(41, /storage/.kodi/addons/plugin.video.amazon-test/default.py): instantiating addon using automatically obtained id of "plugin.video.amazon-test" dependent on version 2.24.0 of the xbmc.python api
2023-10-25 21:14:46.618 T:3011736960   DEBUG: ------ Window Init (DialogBusy.xml) ------
2023-10-25 21:14:47.152 T:2437268288   DEBUG: CAddonSettings[plugin.video.amazon-test]: loading setting definitions
2023-10-25 21:14:47.152 T:2437268288   DEBUG: CAddonSettings[plugin.video.amazon-test]: trying to load setting definitions from old format...
2023-10-25 21:14:47.157 T:2437268288   DEBUG: CAddonSettings[plugin.video.amazon-test]: loading setting values
2023-10-25 21:14:47.159 T:2437268288   DEBUG: CSettingsManager: requested setting (register_device) was not found.
2023-10-25 21:14:47.159 T:2437268288   DEBUG: CAddonSettings[plugin.video.amazon-test]: failed to find definition for setting register_device. Creating a setting on-the-fly...
2023-10-25 21:14:47.217 T:2437268288  NOTICE: [Amazon VOD] startup.py:44 Requested {}
2023-10-25 21:14:48.740 T:2437268288  NOTICE: [Amazon VOD] startup.py:69 Version: 0.9.9
2023-10-25 21:14:48.740 T:2437268288  NOTICE: [Amazon VOD] startup.py:70 Unicode filename support: False
2023-10-25 21:14:48.741 T:2437268288  NOTICE: [Amazon VOD] startup.py:71 Locale: en-us / Language: fr
2023-10-25 21:14:48.753 T:2437268288  NOTICE: [Amazon VOD] network.py:113 getURL: https://www.primevideo.com
2023-10-25 21:14:50.736 T:2661045056   DEBUG: PushCecKeypress - received key d8 duration 0
2023-10-25 21:14:50.752 T:3011736960   DEBUG: HandleKey: menu (0xd8) pressed, action is Back
2023-10-25 21:14:50.784 T:3011736960   DEBUG: ------ Window Deinit (DialogBusy.xml) ------
2023-10-25 21:14:50.784 T:2022687552   DEBUG: WaitOnScriptResult- cancelling plugin Amazon VOD (id=41)
2023-10-25 21:14:50.784 T:3011736960   DEBUG: ------ Window Init (DialogBusy.xml) ------
2023-10-25 21:14:50.918 T:2661045056   DEBUG: PushCecKeypress - received key d8 duration 182
2023-10-25 21:14:51.162 T:2022687552   DEBUG: CPythonInvoker(41, /storage/.kodi/addons/plugin.video.amazon-test/default.py): trigger Monitor abort request
2023-10-25 21:14:51.778 T:2437268288  NOTICE: [Amazon VOD] logging.py:57 Saved Log with filename “html-2.log”
2023-10-25 21:14:51.784 T:2437268288  NOTICE: [Amazon VOD] network.py:205 Download Time: 3.02911186218
2023-10-25 21:14:51.873 T:2437268288   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: 'NoneType' object is not callable
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/default.py", line 7, in <module>
                                                EntryPoint()
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/startup.py", line 72, in EntryPoint
                                                _g.pv.BrowseRoot()
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/web_api.py", line 296, in BrowseRoot
                                                if not self.BuildRoot():
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/web_api.py", line 305, in BuildRoot
                                                home = GrabJSON(self._g.BaseUrl + ('' if self._g.UsePrimeVideo else '/gp/video/storefront'))
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/network.py", line 535, in GrabJSON
                                                j = do(url, postData)
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/network.py", line 483, in do
                                                m = json.loads(Unescape(m))
                                              File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
                                              File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
                                              File "/usr/lib/python2.7/json/decoder.py", line 380, in raw_decode
                                              File "/usr/lib/python2.7/json/decoder.py", line 36, in errmsg
                                            TypeError: 'NoneType' object is not callable
                                            -->End of Python script error report<--
2023-10-25 21:14:51.873 T:2437268288   DEBUG: onExecutionDone(41, /storage/.kodi/addons/plugin.video.amazon-test/default.py)
```

**Comment by Sandmann79** [comment] 2023-10-26 09:05
Duplicate of #709
This has nothing to do with the update, it is rather a change at Amazon. The old version does not work either.
Btw. Amazon.fr redirects to primevideo.com when Prime Video is selected on the homepage.

**Closed** 2023-10-26 09:06 UTC

**Comment by antibarbie** [comment] 2023-10-26 10:02
Ok, was just guess / a shot in the dark, as both happened to me at the same time

I saw the source code of the last version and realize this could probably not be the cause of the problem.

(or course, it could have been the fact that the plugin was updated or installed, and some initialization code would fail)
