### ISSUE TITLE
5.1 support 

### ISSUE THREAD

**Issue by Krobar** [Sandmann79/xbmc#127] opened 2018-05-28 21:29 UTC
A lot of streams for series (e.g. Black Sails) have 5.1 in the Samsung app but not in this add on. Kodi info shows the same series as Dolby but I only ever get stereo with no other streams to choose. Some films do work as 5.1 eac3, it seems like there is more than 1 type of 5.1 and they aren't all supported. Do series such as Black Sails season 4 play in 5.1 for others?

**Comment by Krobar** [comment] 2018-05-28 21:32
Forgot to mention I'm using Adaptive Stream.

**Comment by Varstahl** [comment] 2018-05-28 22:12
It is my understanding that the currently "firmware" we're using for Amazon only provides support for stereo tracks and up to 1080p. With some reverse engineer of the android apks it should be in theory possible to unlock both multi-channel audio tracks and 4K resolutions, the problem is that I haven't found the time and nobody else stepped forward so… in theory, maybe?

Also I might be wrong on this, I can't recall off the top of my head, but IS.A also only supported stereo tracks up until the last time I checked. So it might be a little bit of both.

**Comment by Sandmann79** [comment] 2018-05-29 05:27
@Krobar Did you disable DRM check & switch audio track at settings? The last option is not needed anymore at newer Kodi builds and will be removed in the next addon version.

@Varstahl That's right - in combination with cookie authentication and the web devicetypeid, we're getting at least only stereo/1080p tracks. By slightly modifying the mpd url it's possible to get more audio tracks, including eac3, but it seems to not work for all countries. You can post the mpd url here, and i can look into it, maybe there is an better modifier to get all tracks. I know that's not a good solution, but unfortunately all other devicetypeid, that i've been tested, doesn't work for playback.
Decompiling the apks doesn't really help, the url parameters don't work with our request.

**Comment by Varstahl** [comment] 2018-05-29 08:54
> Decompiling the apks doesn't really help, the url parameters don't work with our request.
Ah. that's a shame.

I'm still hell bent set on sniffing my 4k TV traffic though. There must be something we could do, hopefully.

**Comment by Krobar** [comment] 2018-05-29 21:26
Just tried with the DRM option changed but it didn't help. BTW: Great work on the add-on

**Comment by Animizio** [comment] 2018-05-31 14:31
Got the same error..only getting stereo Sound. Tried drm and without.

**Comment by natethomas** [comment] 2018-06-05 16:37
For those of you only getting stereo, I hesitate to ask, but did you check audio stream during playback and see if there was an available 5.1 stream? It's possible the default stream is stereo and the alt audio stream is 5.1.

**Comment by Varstahl** [comment] 2018-08-02 10:31
Dolby Digital 5.1 is working correctly, tested on Amazon VOD 0.5.5, and 0.5.6. Closing the issue.

**Comment by dhleong** [comment] 2019-02-14 17:13
@Varstahl Do you happen to know what change fixed 5.1 support?

**Comment by Varstahl** [comment] 2019-02-14 17:32
I don't think it was a particular fix on our side. It was around the time of 41f643eef4d44c0aff2b8e4c07f8696e097d4444, and over the course of the summer several changes to IS.A allowed playback for 5.1 DD+. As far as I remember of course, it's almost one year ago. It could have very well been the removal of `validAudioTrack` that fixed it, the only thing I know for sure is that it was working on August, and it's still working today.

**Comment by dhleong** [comment] 2019-02-14 17:57
Interesting, so the manifests returned by Amazon still say they're just `"stereo"` for you?

**Comment by Varstahl** [comment] 2019-02-14 18:08
No, I just tested a movie out of curiosity, I have both AC3 stereo and DD+ 5.1 audio, with DD+ selected by default. There have been differences across regions and servers, so I won't declare that DD+ works __everywhere__ but I'm fairly sure nothing's wrong on our end of the bargain. Also, if I remember correctly, not every language has DD+, some just have stereo tracks.

Of course, I'm only talking about what IS.A is reporting, I'm not able to test if it's actually surround or not at this very moment.

**Comment by dhleong** [comment] 2019-02-14 18:26
I mean specifically the `audioQuality` key in the response to `GetPlaybackResources`; does that just say `"stereo"` or does it have different values for you? Or, is it just in the MPDs referenced in that doc where the different audio tracks live?

I have a JVM implementation that I initially based on this project some time ago, so I'm not actually sure what IS.A is.

Thanks for your help!

**Comment by Varstahl** [comment] 2019-02-15 08:02
Picture me surprised. I checked back out of paranoia the GPR results and the MPDs, both return stereo only tracks, while [InputStream.Adaptive](https://github.com/peak3d/inputstream.adaptive) reports DD+. What the hell's going on here? :|

**Comment by Varstahl** [comment] 2019-02-15 08:07
Triple checked sniffing Kodi's traffic, all audio tracks are reported as stereo, so the "fake" DD+ must have been introduced for some reason. Gotta check this again…

**Comment by Varstahl** [comment] 2019-02-18 19:04
@dhleong I investigated this a bit:

```
<AdaptationSet audioTrackId="de-de_dialog_0" contentType="audio" group="1" lang="de" maxBandwidth="128000" mimeType="audio/mp4" minBandwidth="128000">
<Representation audioSamplingRate="48000" bandwidth="128000" codecs="mp4a.40.2" id="audio_deu_3=128000"><AudioChannelConfiguration value="2"/><BaseURL>_audio_82.mp4</BaseURL>

<AdaptationSet audioTrackId="de-de_dialog_0" contentType="audio" group="1" lang="de" maxBandwidth="32000" mimeType="audio/mp4" minBandwidth="20000">
<Representation audioSamplingRate="24000" bandwidth="20000" codecs="mp4a.40.29" id="audio_deu=20000"><AudioChannelConfiguration value="2"/><BaseURL>_audio_6.mp4</BaseURL>
<Representation audioSamplingRate="24000" bandwidth="32000" codecs="mp4a.40.29" id="audio_deu=32000"><AudioChannelConfiguration value="2"/><BaseURL>_audio_24.mp4</BaseURL>

<AdaptationSet audioTrackId="de-de_dialog_0" contentType="audio" group="1" lang="de" maxBandwidth="64000" mimeType="audio/mp4" minBandwidth="64000">
<Representation audioSamplingRate="24000" bandwidth="64000" codecs="mp4a.40.5" id="audio_deu_1=64000"><AudioChannelConfiguration value="2"/><BaseURL>_audio_42.mp4</BaseURL>

<AdaptationSet audioTrackId="en-us_dialog_0" contentType="audio" group="1" lang="en" maxBandwidth="192000" mimeType="audio/mp4" minBandwidth="96000">
<Representation audioSamplingRate="48000" bandwidth="96000" codecs="mp4a.40.2" id="audio_eng_2=96000"><AudioChannelConfiguration value="2"/><BaseURL>_audio_54.mp4</BaseURL>
<Representation audioSamplingRate="48000" bandwidth="128000" codecs="mp4a.40.2" id="audio_eng_2=128000"><AudioChannelConfiguration value="2"/><BaseURL>_audio_80.mp4</BaseURL>
<Representation audioSamplingRate="48000" bandwidth="192000" codecs="mp4a.40.2" id="audio_eng_2=192000"><AudioChannelConfiguration value="2"/><BaseURL>_audio_100.mp4</BaseURL>

<AdaptationSet audioTrackId="en-us_dialog_0" contentType="audio" group="1" lang="en" maxBandwidth="64000" mimeType="audio/mp4" minBandwidth="20000">
<Representation audioSamplingRate="24000" bandwidth="20000" codecs="mp4a.40.29" id="audio_eng=20000"><AudioChannelConfiguration value="2"/><BaseURL>_audio_8.mp4</BaseURL>
<Representation audioSamplingRate="24000" bandwidth="32000" codecs="mp4a.40.29" id="audio_eng=32000"><AudioChannelConfiguration value="2"/><BaseURL>_audio_18.mp4</BaseURL>
<Representation audioSamplingRate="24000" bandwidth="48000" codecs="mp4a.40.29" id="audio_eng=48000"><AudioChannelConfiguration value="2"/><BaseURL>_audio_32.mp4</BaseURL>
<Representation audioSamplingRate="24000" bandwidth="64000" codecs="mp4a.40.29" id="audio_eng=64000"><AudioChannelConfiguration value="2"/><BaseURL>_audio_48.mp4</BaseURL>

<AdaptationSet audioTrackId="en-us_dialog_0" contentType="audio" group="1" lang="en" maxBandwidth="80000" mimeType="audio/mp4" minBandwidth="48000">
<Representation audioSamplingRate="24000" bandwidth="48000" codecs="mp4a.40.5" id="audio_eng_1=48000"><AudioChannelConfiguration value="2"/><BaseURL>_audio_30.mp4</BaseURL>
<Representation audioSamplingRate="24000" bandwidth="64000" codecs="mp4a.40.5" id="audio_eng_1=64000"><AudioChannelConfiguration value="2"/><BaseURL>_audio_46.mp4</BaseURL>
<Representation audioSamplingRate="24000" bandwidth="80000" codecs="mp4a.40.5" id="audio_eng_1=80000"><AudioChannelConfiguration value="2"/><BaseURL>_audio_50.mp4</BaseURL>

<AdaptationSet audioTrackId="es-es_dialog_0" contentType="audio" group="1" lang="es" maxBandwidth="128000" mimeType="audio/mp4" minBandwidth="128000">
<Representation audioSamplingRate="48000" bandwidth="128000" codecs="mp4a.40.2" id="audio_spa_3=128000"><AudioChannelConfiguration value="2"/><BaseURL>_audio_84.mp4</BaseURL>

<AdaptationSet audioTrackId="es-es_dialog_0" contentType="audio" group="1" lang="es" maxBandwidth="32000" mimeType="audio/mp4" minBandwidth="20000">
<Representation audioSamplingRate="24000" bandwidth="20000" codecs="mp4a.40.29" id="audio_spa=20000"><AudioChannelConfiguration value="2"/><BaseURL>_audio_14.mp4</BaseURL>
<Representation audioSamplingRate="24000" bandwidth="32000" codecs="mp4a.40.29" id="audio_spa=32000"><AudioChannelConfiguration value="2"/><BaseURL>_audio_28.mp4</BaseURL>

<AdaptationSet audioTrackId="es-es_dialog_0" contentType="audio" group="1" lang="es" maxBandwidth="64000" mimeType="audio/mp4" minBandwidth="64000">
<Representation audioSamplingRate="24000" bandwidth="64000" codecs="mp4a.40.5" id="audio_spa_1=64000"><AudioChannelConfiguration value="2"/><BaseURL>_audio_36.mp4</BaseURL>

<AdaptationSet audioTrackId="es-419_dialog_0" contentType="audio" group="1" lang="es" maxBandwidth="128000" mimeType="audio/mp4" minBandwidth="128000">
<Representation audioSamplingRate="48000" bandwidth="128000" codecs="mp4a.40.2" id="audio_spa_3=128000"><AudioChannelConfiguration value="2"/><BaseURL>_audio_68.mp4</BaseURL>

<AdaptationSet audioTrackId="es-419_dialog_0" contentType="audio" group="1" lang="es" maxBandwidth="32000" mimeType="audio/mp4" minBandwidth="20000">
<Representation audioSamplingRate="24000" bandwidth="20000" codecs="mp4a.40.29" id="audio_spa=20000"><AudioChannelConfiguration value="2"/><BaseURL>_audio_2.mp4</BaseURL>
<Representation audioSamplingRate="24000" bandwidth="32000" codecs="mp4a.40.29" id="audio_spa=32000"><AudioChannelConfiguration value="2"/><BaseURL>_audio_16.mp4</BaseURL>

<AdaptationSet audioTrackId="es-419_dialog_0" contentType="audio" group="1" lang="es" maxBandwidth="64000" mimeType="audio/mp4" minBandwidth="64000">
<Representation audioSamplingRate="24000" bandwidth="64000" codecs="mp4a.40.5" id="audio_spa_1=64000"><AudioChannelConfiguration value="2"/><BaseURL>_audio_44.mp4</BaseURL>

<AdaptationSet audioTrackId="fr-fr_dialog_0" contentType="audio" group="1" lang="fr" maxBandwidth="128000" mimeType="audio/mp4" minBandwidth="128000">
<Representation audioSamplingRate="48000" bandwidth="128000" codecs="mp4a.40.2" id="audio_fra_3=128000"><AudioChannelConfiguration value="2"/><BaseURL>_audio_74.mp4</BaseURL>

<AdaptationSet audioTrackId="fr-fr_dialog_0" contentType="audio" group="1" lang="fr" maxBandwidth="32000" mimeType="audio/mp4" minBandwidth="20000">
<Representation audioSamplingRate="24000" bandwidth="20000" codecs="mp4a.40.29" id="audio_fra=20000"><AudioChannelConfiguration value="2"/><BaseURL>_audio_10.mp4</BaseURL>
<Representation audioSamplingRate="24000" bandwidth="32000" codecs="mp4a.40.29" id="audio_fra=32000"><AudioChannelConfiguration value="2"/><BaseURL>_audio_22.mp4</BaseURL>

<AdaptationSet audioTrackId="fr-fr_dialog_0" contentType="audio" group="1" lang="fr" maxBandwidth="64000" mimeType="audio/mp4" minBandwidth="64000">
<Representation audioSamplingRate="24000" bandwidth="64000" codecs="mp4a.40.5" id="audio_fra_1=64000"><AudioChannelConfiguration value="2"/><BaseURL>_audio_34.mp4</BaseURL>

<AdaptationSet audioTrackId="it-it_dialog_0" contentType="audio" group="1" lang="it" maxBandwidth="128000" mimeType="audio/mp4" minBandwidth="128000">
<Representation audioSamplingRate="48000" bandwidth="128000" codecs="mp4a.40.2" id="audio_ita_3=128000"><AudioChannelConfiguration value="2"/><BaseURL>_audio_86.mp4</BaseURL>

<AdaptationSet audioTrackId="it-it_dialog_0" contentType="audio" group="1" lang="it" maxBandwidth="32000" mimeType="audio/mp4" minBandwidth="20000">
<Representation audioSamplingRate="24000" bandwidth="20000" codecs="mp4a.40.29" id="audio_ita=20000"><AudioChannelConfiguration value="2"/><BaseURL>_audio_12.mp4</BaseURL>
<Representation audioSamplingRate="24000" bandwidth="32000" codecs="mp4a.40.29" id="audio_ita=32000"><AudioChannelConfiguration value="2"/><BaseURL>_audio_26.mp4</BaseURL>

<AdaptationSet audioTrackId="it-it_dialog_0" contentType="audio" group="1" lang="it" maxBandwidth="64000" mimeType="audio/mp4" minBandwidth="64000">
<Representation audioSamplingRate="24000" bandwidth="64000" codecs="mp4a.40.5" id="audio_ita_1=64000"><AudioChannelConfiguration value="2"/><BaseURL>_audio_38.mp4</BaseURL>

<AdaptationSet audioTrackId="pt-br_dialog_0" contentType="audio" group="1" lang="pt" maxBandwidth="128000" mimeType="audio/mp4" minBandwidth="128000">
<Representation audioSamplingRate="48000" bandwidth="128000" codecs="mp4a.40.2" id="audio_por_3=128000"><AudioChannelConfiguration value="2"/><BaseURL>_audio_92.mp4</BaseURL>

<AdaptationSet audioTrackId="pt-br_dialog_0" contentType="audio" group="1" lang="pt" maxBandwidth="32000" mimeType="audio/mp4" minBandwidth="20000">
<Representation audioSamplingRate="24000" bandwidth="20000" codecs="mp4a.40.29" id="audio_por=20000"><AudioChannelConfiguration value="2"/><BaseURL>_audio_4.mp4</BaseURL>
<Representation audioSamplingRate="24000" bandwidth="32000" codecs="mp4a.40.29" id="audio_por=32000"><AudioChannelConfiguration value="2"/><BaseURL>_audio_20.mp4</BaseURL>

<AdaptationSet audioTrackId="pt-br_dialog_0" contentType="audio" group="1" lang="pt" maxBandwidth="64000" mimeType="audio/mp4" minBandwidth="64000">
<Representation audioSamplingRate="24000" bandwidth="64000" codecs="mp4a.40.5" id="audio_por_1=64000"><AudioChannelConfiguration value="2"/><BaseURL>_audio_40.mp4</BaseURL>
```

All audio files are reported as stereo, but IS.A (the stream player embedded in Kodi) reports some of these streams as DD+ 5.1. My guess is that it actually checks the codec, and reports 5.1 for one of those codecs and stereo in the other two. Maybe the `.5` is the 6 channels and the `.2x` are the two channels? Or maybe the `.2` is actually the 6 channels, given the bigger bandwidth? Or maybe they're all stereo?

I don't know, I can't really test this at the moment. I might try to download the audio streams and analyse them later.

**Comment by Varstahl** [comment] 2019-02-18 20:23
Thinking back to it, everything is working as intended. Both DD+ and DTS use stereo channels (they just send channels in sequence a couple at a time), so amazon's backend reporting stereo is absolutely correct.

As for the codecs, being encrypted and all, even ffmpeg doesn't help much, but looking at the logs with audio selection:

```
(codec id: 86056, channels: 6, sample rate: 48000, no pass-through)
(codec id: 86018, channels: 2, sample rate: 48000, no pass-through)
(codec id: 86018, channels: 2, sample rate: 48000, no pass-through)
```

So, the two ffmpeg codec ids reported as 86018 are stereos, while the one reported as 86056 is 5+1. I don't really have the necessary software or hardware equipment at the moment to test it out, but you could alter the MPD through a proxy and feed it to Kodi, to detect which of the codecs are actually not stereo.

**Closed by Varstahl** 2019-02-18 20:23 UTC

**Comment by Varstahl** [comment] 2019-02-19 15:16
@dhleong as per my prediction based on bandwidth, judging by the codec from the `<Representation>` tag in the MPD in all my tests mp4a.40.2 are surround, while .29 and .5 are stereo.

**Comment by dhleong** [comment] 2019-02-19 15:20
Thanks for your help @Varstahl !

**Comment by Varstahl** [comment] 2019-02-19 15:40
Np, you're welcome :)

**Comment by Varstahl** [comment] 2019-02-25 18:49
@dhleong forget everything I said. There's something I'm not quite understanding, but inside that very same MPD under certain conditions (still unclear to me), new `AudioChannelConfiguration` appear, possibly protected by Widevine, with the following structure:

`<AudioChannelConfiguration schemeIdUri="urn:dolby:dash:audio_channel_configuration:2011" value="xxxx"/>`

That `xxxx` is `F801` for 5.1, `FE01` for 7.1. I still have no idea how they're made up from thin air, though.

**Comment by Varstahl** [comment] 2019-02-26 09:42
@dhleong I figured it out. When you get the resources manifest with `GetPlaybackResources`, it returns a bunch of data including `playbackUrls.cacheKey`. This cache key will have a `~` on its end. I'm not quite clear of its role, but what's important is that for everything that is not a livestream, if you remove that tilde (or in our codebase _any_ tilde) from the MPD URL, then the manifest itself changes, and you will see a bunch of new Representation with an `ec-3` encoding (although you should find them not by codec but by `schemeIdUri`). Those are the DD+ you're looking for.

```
<AdaptationSet audioTrackId="en-gb_dialog_0" contentType="audio" group="1" lang="en" mimeType="audio/mp4" segmentAlignment="true" subsegmentAlignment="true" subsegmentStartsWithSAP="1">
    <Representation audioSamplingRate="48000" bandwidth="192000" codecPrivateData="<somedata>" codecs="ec-3" id="audio_eng_1=192000">
        <AudioChannelConfiguration schemeIdUri="urn:dolby:dash:audio_channel_configuration:2011" value="F801"/>
```

16 hours of investigation, all to find a superfluous tilde. Feels like the opposite of the C "spot the missing ;" .

**Comment by dhleong** [comment] 2019-02-26 13:23
Wow this is wild. Thanks for your hard work!

**Comment by Varstahl** [comment] 2019-02-26 13:28
No big deal. I was bashing my head on this problem for a different (but similar) issue and thought of sharing the solution.

**Comment by jhahner64** [comment] 2019-06-30 06:43
So please clarify for me as a new user of both kodi and this add on - if I remove the tilde(s) from some part of the code from the repository, once I have decompiled it, I should get 5.1 surround on many more of the tracks. Can I get a dumbed-down method of doing this? Right now, a -very- small percentage of the titles shown on VOD have 5.1 shown as an option, while many of the same titles support surround on my smart tv. Thanks @Varstahl and @dhleong for all of your hard work!

**Comment by Varstahl** [comment] 2019-06-30 12:54
1. you don't actually decompile anything, it's not binary, the sources are all here
2. you don't actually have to alter anything, surround is enabled by default
3. if, as you stated, "some" videos have 5.1 in Kodi then it's working as intended. Everything else is governed by Amazon's server, and you can tinker around as you wish, it ain't gonna change that.

In any case, here you can find the two rows governing this in [playback.py](https://github.com/Sandmann79/xbmc/blob/1626446fa2996bb9f4b01cf7dd308610ef73b3c6/plugin.video.amazon-test/resources/lib/playback.py#L374), and the function that alters MPDs, [_AlterMPD](https://github.com/Sandmann79/xbmc/blob/1626446fa2996bb9f4b01cf7dd308610ef73b3c6/plugin.video.amazon-test/resources/lib/proxy.py#L282). Play away.
