### ISSUE TITLE
Can't play Amazon Prime videos

### ISSUE THREAD

**Issue by pecheronza** [Sandmann79/xbmc#193] opened 2018-10-27 17:23 UTC
Hi,

I installed the Amazon VOD addon a couple of days ago. Everything seems to work fine but videos won't start: it loads for a while and then just says that the video cannot be played, check the log.
I searched through the issues but I couldn't find anything similar.
Both the addon and the system are updated.
This is the log file

```
18:50:29.221 T:1211101952  NOTICE: [Amazon VOD] Version: 0.6.1
18:50:29.222 T:1211101952  NOTICE: [Amazon VOD] Unicode filename support: False
18:50:29.222 T:1211101952  NOTICE: [Amazon VOD] Locale: en-gb / Language: it
18:50:29.369 T:1211101952 WARNING: CPythonInvoker(24, /home/osmc/.kodi/addons/plugin.video.amazon-test/default.py): the python script "/home/osmc/.kodi/addons/plugin.video.amazon-test/default.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE,N9XBMCAddon7xbmcgui6DialogE
18:50:37.943 T:1211101952 WARNING: CPythonInvoker(25, /home/osmc/.kodi/addons/plugin.video.amazon-test/default.py): the python script "/home/osmc/.kodi/addons/plugin.video.amazon-test/default.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE,N9XBMCAddon7xbmcgui6DialogE
18:50:45.689 T:1211101952   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: (u'root-/',)
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.amazon-test/default.py", line 5, in <module>
                                                EntryPoint()
                                              File "/home/osmc/.kodi/addons/plugin.video.amazon-test/resources/lib/startup.py", line 83, in EntryPoint
                                                g.pv.Browse(None if 'path' not in args else args['path'])
                                              File "/home/osmc/.kodi/addons/plugin.video.amazon-test/resources/lib/primevideo.py", line 180, in Browse
                                                node = node[n]
                                            KeyError: (u'root-/',)
                                            -->End of Python script error report<--
18:50:45.837 T:1211101952 WARNING: CPythonInvoker(26, /home/osmc/.kodi/addons/plugin.video.amazon-test/default.py): the python script "/home/osmc/.kodi/addons/plugin.video.amazon-test/default.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon7xbmcgui6DialogE,N9XBMCAddon9xbmcaddon5AddonE
18:50:45.850 T:1436545792   ERROR: GetDirectory - Error getting plugin://plugin.video.amazon-test/?mode=PrimeVideo_Browse&path=root-/
```

What should I do?

Thanks in advance.

**Comment by Varstahl** [comment] 2018-10-28 11:10
That's pretty weird and shouldn't happen.

> ERROR: GetDirectory - Error getting plugin://plugin.video.amazon-test/?mode=PrimeVideo_Browse&path=root-/

There is no chance in hell this should be a thing. Either something changed with Kodi or there are other plugins conflicting. Could you provide a full log, so that I may get an idea of the situation?

**Comment by pecheronza** [comment] 2018-10-28 11:32
[kodi.log](https://github.com/Sandmann79/xbmc/files/2522726/kodi.log)

If for "full log" you mean the whole log file, here it is. If you mean a more complete log I'm afraid you have to explain how to get it, I'm quite the newbie here.

By the way I didn't install any other plugin, the only one is My osmc. As far as I recall I didn't install anything else, the only thing I added to the system is a script that moves files every once in a while.

**Comment by CGarces** [comment] 2018-10-28 11:44
Hi @pecheronza 
OSMC can generate URL with the full logs, please [read this instructions](https://osmc.tv/wiki/general/how-to-submit-a-useful-support-request/), specially the section "Providing diagnostic logs"

**Comment by Varstahl** [comment] 2018-10-28 11:50
I see a number of different problems:

> ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.amazon-test/?mode=PrimeVideo_Browse&path=search-%2F%2F-amzn1.dv.gti.9eb1107b-13c8-4e82-9406-51dfcbede7a2-%2F%2F-0R5LQART2MFFBK75MSR4T8HIPV-//-0T62FC2IG6VIRO012I6U9LLW7S]

> 00:24:40.477 T:1212257024   ERROR: AddOnLog: InputStream Adaptive: Unable to find license;hdcpEnforcementResolutionPixels in JSON string
> 00:24:40.477 T:1212257024   ERROR: AddOnLog: InputStream Adaptive: License update not successful (no keys)
> 00:24:40.477 T:1212257024   ERROR: AddOnLog: InputStream Adaptive: Initialize failed (SingleSampleDecrypter)

> KeyError: (u'root-/',)

The first has been reported by a couple people, it must be some kind of wrong metadata parsing that I need to look further into. The second is related to Kodi, and it (probably? surely?) won't work unless you update to [Kodi Leia](https://forum.kodi.tv/showthread.php?tid=298775).

The third is weird, never happened, and absolutely didn't happen the first time you went through the addon, so for the time I'll just consider it a weird aleatoric event for the moment, since you need a different Kodi build anyway, that's reported working.

> OSMC can generate URL with the full logs

@cgarces Thanks for the hint but for this particular problem so far is not needed :)

**Comment by pecheronza** [comment] 2018-10-28 18:04
Then I guess I'll wait until Leia is stable. I do use the media center (my kids do...) and I'd rather not risk to have to reinstall it.

**Comment by Varstahl** [comment] 2018-10-31 14:42
@santinod could you provide the *.pvcp and *.pvdp cache files? If I take a look at them I might understand what's going on.

**Comment by santinod** [comment] 2018-10-31 19:30
Sorry, no cache files available, as the plugin now aborts with a KeyError.
[kodi.log](https://github.com/Sandmann79/xbmc/files/2536052/kodi.log)

**Comment by Varstahl** [comment] 2018-10-31 19:42
ffs wth is going on :|
that's impossible :|

**Comment by pecheronza** [comment] 2018-11-01 00:51
I realize now it wasn't my files you didn't ask for, but since I'm here there you go.

[plugin.video.amazon-test.zip](https://github.com/Sandmann79/xbmc/files/2536824/plugin.video.amazon-test.zip)

**Comment by Varstahl** [comment] 2018-11-01 10:53
You seemed to have the same issues, so it's good :D

**Comment by Varstahl** [comment] 2018-11-01 12:30
@pecheronza doesn't seem to be anything wrong in your cache files. Weird.

**Comment by pecheronza** [comment] 2018-11-01 12:36
I don't know what to say. I'll wait till the next stable version of Kodi, even if it's weird it doesn't work with the current one.

**Comment by Varstahl** [comment] 2018-11-01 12:55
Still looking into the issue, maybe I can find something.

**Comment by Varstahl** [comment] 2018-11-01 16:57
Looked back at your logs and realised that the inability to playback videos is due to the old Kodi version, so you could probably setup an alternative way through a browser with Kodi (Amazon VOD supports external playback methods).

As for the catalog traversal, while not 100% sure, the possible problems caused by invalid traversals should be fixed with eadb2924859b3d2ea6f87c24989ae7296855cc41, although nobody ever experienced issues with Kodi 18+.

**Closed by Varstahl** 2018-11-01 16:57 UTC
Labels: bug, primevideo

**Comment by stargriv** [comment] 2018-11-30 19:03
Hi @Varstahl
I'm having the same issue, but in my case I'm able to play TV Series and Movies from "Your Watchlist" but not able to play the same titles from "TV Shows" and "Movies" catalogs.
```
dpkg -l | grep mediacenter-osmc | awk '{ print $3 }'
17.8-345
```

```
19:52:36.962 T:1457517296   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: u'Action '
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.amazon-test/default.py", line 5, in <module>
                                                EntryPoint()
                                              File "/home/osmc/.kodi/addons/plugin.video.amazon-test/resources/lib/startup.py", line 83, in EntryPoint
                                                g.pv.Browse(None if 'path' not in args else args['path'])
                                              File "/home/osmc/.kodi/addons/plugin.video.amazon-test/resources/lib/primevideo.py", line 181, in Browse
                                                node = node[n]
                                            KeyError: u'Action '
                                            -->End of Python script error report<--
19:52:37.289 T:1457517296 WARNING: CPythonInvoker(15, /home/osmc/.kodi/addons/plugin.video.amazon-test/default.py): the python script "/home/osmc/.kodi/addons/plugin.video.amazon-test/default.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon7xbmcgui6DialogE,N9XBMCAddon9xbmcaddon5AddonE
19:52:37.303 T:1402557168   ERROR: GetDirectory - Error getting plugin://plugin.video.amazon-test/?%20Adventure%20TV-%2f%2f-amzn1.dv.gti.b6b1606c-c068-3606-e689-c6852cd2ae5e&mode=PrimeVideo_Browse&path=root-%2f%2f-TV%20Shows-%2f%2f-Action%20
19:52:37.305 T:1917489152   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.amazon-test/?%20Adventure%20TV-%2f%2f-amzn1.dv.gti.b6b1606c-c068-3606-e689-c6852cd2ae5e&mode=PrimeVideo_Browse&path=root-%2f%2f-TV%20Shows-%2f%2f-Action%20) failed 
```

**Comment by Varstahl** [comment] 2018-12-01 00:56
@stargriv hard to tell from that snippet alone. You can try to backup/delete the cache files (*.pv?p) from `/home/osmc/.kodi/userdata/addon_data/plugin.video.amazon-test`, restarting Kodi and trying again. As of v0.6 of Amazon VOD we shouldn't encounter this type of problems anymore. If that doesn't work, open a new issue with the full log, and maybe tell me if this is a problem long lasting, or if it's on a brand new installation, and in which country you're in.
