### ISSUE TITLE
No key `siblings` while parsing series

### ISSUE THREAD

**Issue by maiqueg** [Sandmann79/xbmc#365] opened 2019-11-20 21:26 UTC
**Addon used**
- [x] Amazon VOD (plugin.video.amazon-test)
- [ ] Amazon (plugin.video.amazon)
- [ ] Browser Launcher (plugin.program.browser.launcher)
- Addon Version 0.7.8

**Prime Video Account**
- [x] primevideo.com
- [ ] amazon.(com/co.uk/de/jp)

**System Setup:**
- Hardware: Intel i5 3570k, 12gb ram, AMD 270X
- OS Version: Windows 10 x64
- Kodi Version 18.5

**Upload Logs**
kodi.log with debug enabled: [https://pastebin.com/J46Lx1Pu](https://pastebin.com/J46Lx1Pu)

**Describe the bug**
Plugin stopped working on my RaspberryPi3 yesterday. Today, for testing purpose, I've installed Kodi and Amazon VOD plugin on my Windows 10 computer and I still have the same error. I'm able to login to my account, however I get an error when I use search or try to browser the content. If any more details are needed, please let me know.

**Comment by Varstahl** [comment] 2019-11-21 15:54
I'm unable to reproduce the issue in any way. At first I'd say that it's a problem with corrupt video data, but you claim that on a brand new installation with no previous data it breaks as well. It should not be possible. Misconfiguration on some brazilian used servers? I don't know, let's try a few things:

* go to `%appdata%\Kodi\userdata\addon_data\plugin.video.amazon-test` and delete the 2 files `PV*.pv?p`, one is the catalog the other is the video data.
* open kodi, load up the main menu of the addon, go straight to search and use the same `seinfeld` query.

If this works, good, if not:

* close Kodi
* open `%appdata%\Kodi\addons\plugin.video.amazon-test\resources\lib\primevideo.py` with some text editor
* Uncomment lines 797 and 798 https://github.com/Sandmann79/xbmc/blob/fc46c75427429ad583587bd04309ec62ea7b74bf/plugin.video.amazon-test/resources/lib/primevideo.py#L797-L798
* clear the cache files again
* open kodi and perform the same search

After it fails you should se a bunch of `.json` files along with the *.pvcp and *.pvdp files. Zip the JSONs, PVCP and PVDP files and attach the zip in a reply here, so that I may take a look.

**Comment by maiqueg** [comment] 2019-11-21 20:45
Could be a misconfiguration on some brazilian servers, besides I've been using your plugin for months just happen to stop working this week.

I only have a ".pvcp" file. Still didn't work after deleting it.

Here are the json logs from the second step:
[plugin.video.amazon-test.zip](https://github.com/Sandmann79/xbmc/files/3876673/plugin.video.amazon-test.zip)

**Comment by rollnthndr** [comment] 2019-11-29 14:21
Is this just a matter of Amazon changing their API slightly?

**Comment by Varstahl** [comment] 2019-11-29 14:23
So far there was a single case in Brazil, I'm not sure why it's happening but I've collected the data on it. I need to go through with it but I've lacked the time to do it yet, so I can't give an answer to that question.

**Comment by rollnthndr** [comment] 2019-11-29 14:31
The only section I've actually got titles to list is in the Channels sections. Any other area (Movies, TV Shows, Home, etc) all give this error.

**Comment by Varstahl** [comment] 2019-11-29 14:33
It's difficult to debug because the error is geolocalized, happens only for a limited number of people. It also should be impossible to have such an error, so reproducing it requires a lot of manual labor, and I haven't found the necessary time yet.

**Comment by rollnthndr** [comment] 2019-11-29 14:33
No rush here!

**Comment by Vereor** [comment] 2019-11-30 04:54
Looks like the regions include Australia.
Fresh install of Amazon VOD today, never been on the Kodi instance (my first time).
Also getting the  '_if siblings != self._videodata[gti]['siblings']:_' '_KeyError: u'siblings_'.
TV show categories don't display. Movie Categories do, but the folder for each movie is empty.
Let me know if I can contribute anything to the debugging.

**Comment by Varstahl** [comment] 2019-11-30 13:00
Thanks for the report. I should be able to look into it today.

**Comment by rollnthndr** [comment] 2019-12-01 01:15
Tried my VPN using a US portal and still the same issue. Maybe being geolocalized is connected to a customers account and not the internet location?

**Comment by marcusobrien** [comment] 2019-12-01 03:09
Using no VPN. Running the plugin on Kodi and OSMC same result.

2019-12-01 02:28:36.011 T:2598118256   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: u'siblings'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/default.py", line 5, in <module>
                                                EntryPoint()
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/startup.py", line 63, in EntryPoint
                                                elif 'browse' == verb: g.pv.Browse(path)
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/primevideo.py", line 441, in Browse
                                                node, breadcrumb = self._TraverseCatalog(path)
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/primevideo.py", line 361, in _TraverseCatalog
                                                self._LazyLoad(node[nodeName], pathList[0:1 + i])
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/primevideo.py", line 1071, in _LazyLoad
                                                bUpdatedVideoData |= AddSeason(breadcrumb[-1], o, title, img, iu)
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/primevideo.py", line 726, in AddSeason
                                                bUpdatedVideoData |= ParseSinglePage(oid, season, False, url=url)
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/primevideo.py", line 828, in ParseSinglePage
                                                if siblings != self._videodata[gti]['siblings']:
                                            KeyError: u'siblings'
                                            -->End of Python script error report<--
2019-12-01 02:28:36.171 T:2598118256 WARNING: CPythonInvoker(4, /storage/.kodi/addons/plugin.video.amazon-test/default.py): the python script "/storage/.kodi/addons/plugin.video.amazon-test/default.py" has left several classes in memory
2019-12-01 02:28:36.178 T:2622436208   ERROR: GetDirectory - Error getting plugin://plugin.video.amazon-test/pv/browse/root/Watchlist/TV
2019-12-01 02:28:36.188 T:3011223568   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.amazon-test/pv/browse/root/Watchlist/TV) failed

Thanks for all your time on this. Can you show how you debug these types of issues, and I would be like to help out if I can.

Marcus

**Comment by Varstahl** [comment] 2019-12-01 19:59
It really depends on the issue. If it's a problem past login, so just with content management, everything is done and can be checked inside `primevideo.py`, so:

* if there's an error regarding the main menu, I check the function `BuildRoot`;
* if there's a problem on incorrect metadata, I usually check the `Browse` function;
* in a case like this, it's between `_LazyLoad`, `_LazyLoad.AddSeason` and `_LazyLoad.ParseSinglePage`.

This issue is particular a pain because I can't just point to an address to find out what's wrong, there's a lot of static analysis to be made. For example, unless there's something wrong (and there must be), this error shouldn't be happening, because the creation of tv series is done here: https://github.com/Sandmann79/xbmc/blob/6f5f51932e503b4d33589f5a986df74e49d1bc3e/plugin.video.amazon-test/resources/lib/primevideo.py#L820-L823
There shouldn't ever be a season without siblings, yet here we are.

Since amazon uses canary deployments, I can either go modifying code around until it's tested working, or I have to wait until the problem reaches me to be able to fix it.

I'm starting working on this at this very moment, if you want I can describe what I find (if/when I find it).

**Comment by Varstahl** [comment] 2019-12-01 22:54
Ready or not, here we go. It would be helpful for anyone reading this to open the [primevideo.py](https://github.com/Sandmann79/xbmc/blob/6f5f51932e503b4d33589f5a986df74e49d1bc3e/plugin.video.amazon-test/resources/lib/primevideo.py) file referenced in here, to follow along.

<hr/>

By your log we can deduce that the page has never been scraped before, since it doesn't exist in the conversion table of URN=>GTI.
```py
File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/primevideo.py", line 726, in AddSeason
bUpdatedVideoData |= ParseSinglePage(oid, season, False, url=url)
```
https://github.com/Sandmann79/xbmc/blob/6f5f51932e503b4d33589f5a986df74e49d1bc3e/plugin.video.amazon-test/resources/lib/primevideo.py#L724-L726

So, it's a new season and possibly a new TV show. Since it's a `Browse` navigation action,
```py
File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/startup.py", line 63, in EntryPoint
elif 'browse' == verb: g.pv.Browse(path)
```
and not a refresh, we can assume `bCacheRefresh` to be `False`, so the entire section 762-789 is skipped.

It's inconclusive with your limited log if the data is passed on with the function or fetched from a URL since it's missing the verbose logging necessary to debug that portion, but we can notice at least that in row 720 there's a mistake and that the code is actually working by miracle: https://github.com/Sandmann79/xbmc/blob/6f5f51932e503b4d33589f5a986df74e49d1bc3e/plugin.video.amazon-test/resources/lib/primevideo.py#L718-L720
`iu` should be `url` instead, in this case it makes no difference since `iu` is defined in the parent's scope, but still…

Going back to the analysis we know that the `ParseSinglePage` inside `AddSeason` doesn't pass cached data, so url must be a valid url that returns data. Since there are no errors during download, that would be notified, we skip ahead past further initializations and reach 787.

At this point some JSON parsing starts, so I'm taking a look at `20191121_173927007000_12.json` provided by @maiqueg to start the static analysis. If I had live action, this is the point where I would cheaply start using the `Log()` function, logging variables, URLs, and sub keys to my heart's content, but since I can't reproduce the issue, static analysis it is, looking at the data inside the `state` key.

`oid` is either the `gti` of the season, or the text of a section. While I can't know the GTI since it's not logged, there's the URL on top of the JSON file which shows (what I call a) URN, `…/detail/0I5NJESLINJFN8FSOKMH3I3H57/`. The data found inside the JSON file show that the URN `0I5NJESLINJFN8FSOKMH3I3H57` is the equivalent of the GTI `amzn1.dv.gti.32b1c569-bb15-1fc5-7025-476e6d5d478b`, so we're looking at `Um Amor de Família, season 1`. Since we're adding a season, we should be able to assume that we're not inside a show/season already, so oid is not a GTI. `state['self']` contains GTI only, so it's safe to assume the block 816-830 is executed: https://github.com/Sandmann79/xbmc/blob/6f5f51932e503b4d33589f5a986df74e49d1bc3e/plugin.video.amazon-test/resources/lib/primevideo.py#L813-L830

At the time of the error `_videodata[gti]` should be properly initialized, but it isn't. So either:
1. we mistakenly initialized somewhere else, or;
2. there's a hash conflict in Amazon's GTI database.

Armed with patience and the `self._videodata\[[^\]]*\]` regular expression, I'm investigating the former. Only 3 major constructions are present in the code:

https://github.com/Sandmann79/xbmc/blob/6f5f51932e503b4d33589f5a986df74e49d1bc3e/plugin.video.amazon-test/resources/lib/primevideo.py#L739
Sets up the parent TV show, and also comes after the season parsing, unrelated.

https://github.com/Sandmann79/xbmc/blob/6f5f51932e503b4d33589f5a986df74e49d1bc3e/plugin.video.amazon-test/resources/lib/primevideo.py#L822
This, we've seen before. It's a proper initialization, it shouldn't error out.

https://github.com/Sandmann79/xbmc/blob/6f5f51932e503b4d33589f5a986df74e49d1bc3e/plugin.video.amazon-test/resources/lib/primevideo.py#L867
This looks awfully fishy. It should only proc on episodes though. While going through the list inside the JSON dump, the first result in the details is actually a movie. *What the actual f—?!* Search for `"titleType": "[^se]`, results in a list of `MOVIE`, and `SEASON`, because apparently capitalization is hard. Gotta love Amazon for that, they can't even decide between using `True`, `true`, or `1` in their JSONs. So, a number of things could be happening:
1. the season was previously listed somewhere else but with `"titleType" = "SEASON"`;
2. the season parser screwed up somewhere when it found movies inside the episodes details, for reasons unknown;
3. the problem relies somewhere else.

At this point given the limited data available all I can do is try to fix the issues I found with the data provided, (future self, 139d46594f934493406382051d6e06ab73efdaea), ask you to replace the `primevideo.py` file with the one my future self will provide [at this link](https://raw.githubusercontent.com/Sandmann79/xbmc/139d46594f934493406382051d6e06ab73efdaea/plugin.video.amazon-test/resources/lib/primevideo.py), ask you to (at least temporarily) remove the *.pvcp and *.pvdp cache files, restart Kodi and test the changes.

If that doesn't work, I'd have to ask you to go on line 802 and add this code snippet, `Log('{}: {}'.format(gti, self._videodata[gti]))`, have you restart Kodi and provide the new logs post-error. But deep down, I hope we never reach this point. One's hoping…

**Comment by rollnthndr** [comment] 2019-12-02 07:05
If it would help you, I can log things if you have some ideas as to what you want logged. Just tell me where and what and I can send results.

**Comment by Varstahl** [comment] 2019-12-02 12:59
Could you upload the full log somewhere, please?

**Comment by rollnthndr** [comment] 2019-12-02 14:30
[kodi-logs.tar.gz](https://github.com/Sandmann79/xbmc/files/3911703/kodi-logs.tar.gz)

**Comment by maiqueg** [comment] 2019-12-02 21:10
Thanks for the effort, but didn't work yet. 

kodi.log:
[https://pastebin.com/DmcKk9Xx](https://pastebin.com/DmcKk9Xx)

**Comment by Varstahl** [comment] 2019-12-02 21:57
Did you guys delete the *.pvdp cache file from the user data?

**Comment by maiqueg** [comment] 2019-12-02 22:02
I only have one *pvcp file. And yes, I had it deleted.

**Comment by Varstahl** [comment] 2019-12-02 22:04
Ok, then I am completely lost :D
I love that it works, until it doesn't.

**Comment by maiqueg** [comment] 2019-12-02 22:16
:/ 

Well, if you need any additional logs let me know.

**Comment by Varstahl** [comment] 2019-12-02 22:45
A band-aid fix would sort of be easy, but I can't seem to figure out where the data gets corrupted or inappropriately initialized. But I just can't, the logs are inconclusive and I'm stuck. I mean, it's clear that the season appears somewhere else but for reasons it's not initialized properly, so it gets into the misc gti, gets initialized with the data it has, which doesn't include children or ref URLs.

But then I would expect the mediatype not to be `season`, but it is, so what in the…

**Comment by Varstahl** [comment] 2019-12-02 23:12
Can you replace primevideo.py with [this one](https://raw.githubusercontent.com/Sandmann79/xbmc/0f45c7915e624f516c51f9b64317882edf74eded/plugin.video.amazon-test/resources/lib/primevideo.py)? I'm confident this fixes the issue (and that I understood why this was an issue to begin with).

**Comment by maiqueg** [comment] 2019-12-02 23:37
It worked! But a few categories are crashing with a new error.

Example: Series -> Séries adicionadas recentemente (recently added series)
kodi.log
[https://pastebin.com/3JEmY0P9](https://pastebin.com/3JEmY0P9)

**Comment by Varstahl** [comment] 2019-12-03 09:42
BAH, they changed that again? >_>
I need a favour, place `Log('{}'.format(item))` on line 1045 and repost the logs.

**Comment by maiqueg** [comment] 2019-12-03 10:30
Done ;), here they are:
[https://pastebin.com/rQWVYsnf](https://pastebin.com/rQWVYsnf)

**Comment by Varstahl** [comment] 2019-12-03 10:54
```
"faults": [
    {
        "message": "Could not get CoverImage for title."
    }
]
```

Well, at least it's not my fault…

**Comment by Varstahl** [comment] 2019-12-03 11:05
[primevideo.py](https://raw.githubusercontent.com/Sandmann79/xbmc/5f3f20d21cdde8eb53476f4b7d5142fc8e988cca/plugin.video.amazon-test/resources/lib/primevideo.py) you know the deal by now :D

**Comment by maiqueg** [comment] 2019-12-03 12:14
Kinda worked...

I went through a few categories and all of them worked as expected. However, the season lists are not filtered correctly. 

Per example:
https://puu.sh/ELjFl/fcf37e38ab.png

After choosing "The Grand Tour" to select the Season, it displays other TV series and even Movies.

I've deleted pvcp and pvdp caches, but still doesn't work.

PS. I've tested on my laptop, I'm not at home atm.

**Comment by Varstahl** [comment] 2019-12-03 12:35
Oh for fuck's sake, I didn't consider for that to happen, I thought I could cheese it out. So basically you're getting all the proper content plus everything that gets listed under the suggestions. Gotta scratch that and find a way in between.

**Comment by rollnthndr** [comment] 2019-12-03 12:50
I tested mine and getting the same results @maiqueg is getting with the 'corrupted' lists.

**Comment by Varstahl** [comment] 2019-12-05 20:07
[primevideo.py](https://raw.githubusercontent.com/Sandmann79/xbmc/3f48d22b4a6faae0fe7d465207137dbc7b96f2ad/plugin.video.amazon-test/resources/lib/primevideo.py)

It should be enough to just delete the pvcp while keeping the video metadata, with this one. I'm 90% sure this should fix the last of the problems with content display. 60% of the times it works all the times, after all.

**Comment by demod-au** [comment] 2019-12-06 10:54
Working great now.  All suggested/random titles are gone.

**Comment by maiqueg** [comment] 2019-12-06 12:29
Thank you @Varstahl . It's also working here.

I've left you a tip for your coffee addiction ;)

**Comment by Varstahl** [comment] 2019-12-06 12:40
Yay, more coffee :D

**Closed** 2019-12-06 12:41 UTC
Labels: primevideo
