### ISSUE TITLE
Random stream disruption during playback on PC

### ISSUE THREAD

**Issue by dommy67** [Sandmann79/xbmc#488] opened 2020-07-23 23:58 UTC
**Addon used**
- [x] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- latest

**Account type**
- [x] primevideo.com
- [ ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: Dell T3400 Core 2 Quad cpu @2.4 Ghz , Nvidia GT 710 1920x1080@60Hz
- OS version: Linux Mint 19.3 , kernal 5.4.0-42, nvidia-driver-440p
- Kodi version number: kodi 18.7 Git:20200520-f14f7a84e3

**Upload Logs**

**Describe the bug**

At a random time while watching ( prime video australia ) either a movie or tv series, sometimes  multiple times during the same show, the OSD will appear and either the audio stream will stop and while the video stream continues playing or the video stream will stop and the audio stream continues playing . The only way to correct the issue is to stop the show , restart , then step back to the point were the stream failure occured and continue watching. 
Interestingly enough same issue occurred with the Disney+ plugin for kodi

**Comment by Varstahl** [comment] 2020-07-24 00:08
Sounds like a CDN overload issue, it happens sometimes. The list of streams returned by Amazon has no particular order and/or is using some round-robin, so in most cases we use the first CDN in the list returned.

It shouldn't be too often though, I usually experience this issue half a dozen times a year, on average.

**Comment by dommy67** [comment] 2020-07-26 22:01
Unfortunately,  I experience this disruption daily , sometimes the occurrences occur within in minutes.

Are there any settings that I can adjust that might change the occurrence of this problem? 

Rgrds Peter

**Comment by Varstahl** [comment] 2020-07-27 09:36
It's tough to say, haven't heard of similar issues before. You might try capping the bandwidth in InputStream.Adaptive

![image](https://user-images.githubusercontent.com/284077/88526843-bd213600-cffc-11ea-9efd-d16d90775d78.png)

As a test you could select `Manual` in the `Stream selection` option in IS.A, playback a video, and manually pick the resolution/bitrate that works best for you. Since Amazon uses a stronger version of Widevine than some of their competitors (Netflix included) it might need more power under the hood to decode and show things, it might be unable to currently decode 1.5 mbps.

**Comment by empanadablues** [comment] 2020-08-24 19:16
> At a random time while watching ( prime video australia ) either a movie or tv series, sometimes multiple times during the same show, the OSD will appear and either the audio stream will stop and while the video stream continues playing or the video stream will stop and the audio stream continues playing . The only way to correct the issue is to stop the show , restart , then step back to the point were the stream failure occured and continue watching.
> Interestingly enough same issue occurred with the Disney+ plugin for kodi

Same issue for me in a Raspberry Pi 4 2 Gb on RaspberryPiOS (formerly raspbian) Buster. I'll upload logs and more info, but the symptons are exactly the same.

**Comment by empanadablues** [comment] 2020-08-27 15:33
I'm pretty sure that it isn't an Amazon VOD bug.
Even not being an Amazon VOD bug, it's related, so I let all this info here which could be useful for anyone across the net.

The problem let this info on the kodi log ($HOME/.kodi/temp/kodi.log)
`2020-08-27 16:14:39.155 T:2108887248  **NOTICE: CVideoPlayerAudio::Process - stream stalled**
2020-08-27 16:14:51.013 T:2176028880   **ERROR: CCurlFile::FillBuffer - Failed: Timeout was reached(28)**
2020-08-27 16:14:51.013 T:2176028880   ERROR: CCurlFile::Open failed with code 0 for https://ipv4-c038-mad001-ix.1.oca.nflxvideo.net/?o=AQNTygOTYnV8v0pqRck1wsQTzbRAIcVrw5ePsmsm2qgGkYqhQsoC4YLQQKnbous6ZQkwjo_kv2h_LzIWZ7Ly7JxqDKufZf18beCaTVdf_qsOnlplIS9HVVSjjLCigeyCbcvyYJRliBDlC8qXiDv4YPRLfO-XNfP67UGS6Kk&v=5&e=1598579242&t=-zv67vyQi5KVP-gkhTQ-mGP1ar8:
2020-08-27 16:14:51.528 T:2231460048 WARNING: **CRenderManager::WaitForBuffer - timeout waiting for buffer**`

The same problem occurs with netflix, so it's clear the problem must be a common element, probably inputstream and/or libwidevine and/or a network issue.
Making the search 'NOTICE: CVideoPlayerAudio::Process - stream stalled' it appears a lot of results, always related to inputstream and/or libwidevine and/or perhaps, some kind of bandwith/network issue.
My home connection is a 15 Mbps aDSL, with a good router. Never any issue, lost connection, etc . Using wifi 5G wich reports 270 Mbps local bandwith. No more wifi 5g wireless networks collating. 
Max resolution in InputStream 720p.
Not impossible but not very likely a network/bandwith in my opinion. 

I tried an agressive kodi cache config in $HOME/.kodi/userdata/advancedsettings.xml (150Mb and a 6x readfactor):
<advancedsettings>
<cache>
  <memorysize>157286400</memorysize> 
  <buffermode>1</buffermode>  
  <readfactor>6.0</readfactor>
</cache>
</advancedsettings>
The problems were much less...but didn't dissapear. 
Now I'm trying with 300Mb and a 8x readfactor. It seems it doesn't fail no more, but too early to say

**Comment by Varstahl** [comment] 2020-08-27 17:55
The problem with this type of streams is that they're heavily reliant on network stability, ie. no traffic spikes/[buffer bloats](https://www.bufferbloat.net/projects/bloat/wiki/). The moment where there is an issue anywhere on the route from your PC to the servers, the video buffers.

Since the problem is less with aggressive caching, the problem seems to be logically relative to network instability. The more it caches, the less the chances of stream disruption.

Buffer bloat's a bitch, I've only recently fixed the issues I was having with it on a gigabit connection, on a 15mbit would be even worse. If to that you add the lack of data do decrypt on the fly, it makes it even more noticeable.

**Comment by dommy67** [comment] 2020-08-28 08:26
I just had a look at my kodi log file and found the "stream stalled"
message as well

But when I tried to modify the $HOME/.kodi/userdata/advancedsettings.xml file
it didn't exist, I'm using the latest version 1.8 on a linux box , do I
need to create it ?

Rgrds Peter

**Comment by empanadablues** [comment] 2020-08-28 09:15
> I just had a look at my kodi log file and found the "stream stalled" message as well But when I tried to modify the $HOME/.kodi/userdata/advancedsettings.xml file it didn't exist, I'm using the latest version 1.8 on a linux box , do I need to create it ? Rgrds Peter
> […](#)
Yes. This file doesn't exists by default. 
Just copy the text that I posted above (obviusly adjusting with the valuses you want) and save it with the full correct pathname, and restart kodi.
By the way, in my pi4 with 300 Mb and 8 readfactor it still fails sometimes, so I'll increase a bit more (400 Mb and 10). Perhaps you could go a bit further, because I suppose your machine will have more RAM than my pi 4.
Regards, Miguel

**Comment by empanadablues** [comment] 2020-08-28 10:48
Now I'm trying this settings (the 300 Mb and 8 readfactor didn't resolve completely). 
Like yesterday, too early to say if problems disappear.
`<advancedsettings>
<network>
  <curlclienttimeout>60</curlclienttimeout>  
  <curllowspeedtime>240</curllowspeedtime>  
  <curlretries>2</curlretries>             
</network>
<cache>
  <memorysize>419430400</memorysize>  
  <buffermode>1</buffermode>  
  <readfactor>10</readfactor> 
</cache>
</advancedsettings>`

The libwidevine.so library could be relevant also. 
The version used can be checked in the InputStream helper. Mine currently is 4.10.1679.0 (from Chrome OS HANA 13099.02.0). 
I have been using Kodi for some years (first with pi 3 B, the pi 3B+), and I remember long periods with Netflix and Amazon VOD running smoothly , and suddenly, this problem appeared from the dark. 
I'm not completely sure because until one year ago I had a bad router who hanged frequently, and the Wifi G it's also a band who has problems of interferences with other local wireless networks (even taking care about using the less used channel), but more than a year ago I have a good router, the pi 4 supports perfectly wifi 5G (not the pi 3) that never fails, and the connection is quite good even thought it not the fastest in the world, but, the speed is always the same.
 
Today I tried to update the libwidevine.so library, but the last Chrome OS version has the same version than the previous. 

The Chrome OS versions that you have backed up in your .kodi directory (the default configuration in InputStream helper is store the last 4 libwidevine versions):
`ls -1 $HOME/.kodi/userdata/addon_data/script.module.inputstreamhelper/backup*
13020.67.0
13020.87.0
13099.02.0
13099.102.0`

It seems that this library it's not updated so frequently than the Chrome OS itself. My last 4 downloaded Chrome OS images downloaded by InputStream helper wer bundled with the same libwidevine.so library (the 4.10.1679.0).
This can be checked easily with 
`ls -l /home/pi/.kodi/userdata/addon_data/script.module.inputstreamhelper/backup*/* |grep libwidevine
-rwxr--r-- 1 pi pi 7297324 jun 21 17:16 libwidevinecdm.so
-rwxr--r-- 1 pi pi 7297324 ago 17 15:59 libwidevinecdm.so
-rwxr--r-- 2 pi pi 7297324 ago 28 10:51 libwidevinecdm.so
-rwxr--r-- 2 pi pi 7297324 ago 28 10:51 libwidevinecdm.so`
The fifth column is the size. It's clear that all the files are the exactly the same.

**Comment by dommy67** [comment] 2020-08-28 11:44
Went Googling after I sent my email query found this wiki page
https://kodi.wiki/view/HOW-TO:Modify_the_video_cache
Which explains howto modify the cache as well as what it all means.
So I'll be playing around with this tomorrow.
Thanks for the extra info Miguel, as I'm running kodi on a pc the libraries
are different .

Rgrds Peter

**Comment by dommy67** [comment] 2020-08-29 01:22
This mornings effort:
checked my libwidevinecdm.so version , there is only one, 4.10.1582.2
added my version of "advancedsettings.xml" to userdata with the following
details
<advancedsettings version="1">
  <cache>
    
    <buffermode>2</buffermode>
    <memorysize>20971520</memorysize>
    <readfactor>4</readfactor>
  </cache>
</advancedsettings>
The version number is to silence a nagg line about no version number
I'm only buffering the streams input hence buffermode = 2, I see no reason
to buffer anything else as i've not had problems playing local videos.

I tried this on an episode of Midsomer Murder , i'm showing my age here,
the stream died after 1 hour and 19 minutes so I've changed the readfactor
to 8 and have restarted the same episode

Rgrds Peter

**Comment by dommy67** [comment] 2020-08-29 03:41
Same video failed in roughly the same place except this time there is no 'stream failed' message only 'CCurlFile::FillBuffer - Failed'
so I'm going to try adding the <network> section from @empandablues last post and try again
```
<advancedsettings version="3">
  <network>
    <curlclienttimeout>60</curlclienttimeout>
    <curllowspeedtime>240</curllowspeedtime>
    <curlretries>2</curlretries>
  </network>
  <cache>
    <!--- The three settings will go in this space, between the two cache tags. --->
    <buffermode>2</buffermode>
    <memorysize>20971520</memorysize>
    <readfactor>8</readfactor>
  </cache>
</advancedsettings>
```

**Comment by dommy67** [comment] 2020-09-01 01:00
Tried several variations of the settings in advancedsettings eventually stopping at 1,500MB,32
```
<advancedsettings version="2.5">
  <network>
    <curlclienttimeout>60</curlclienttimeout>
    <curllowspeedtime>240</curllowspeedtime>
    <curlretries>2</curlretries>
  </network>
  <cache>
    <!--- The three settings will go in this space, between the two cache tags. --->
    <buffermode>1</buffermode>
    <memorysize>524288000</memorysize>
    <readfactor>32</readfactor>
  </cache>
</advancedsettings>
```
This gave me 70 minutes of stream time with no break. Tried again the next day after a restart of the PC got 2 minutes before failure and then 35 minutes at which point I stopped .

interestingly enough , same day but later streamed a 100 minute movie no problems at all. Which leads me to the theory that streams marked as movies generally don't fail but streams marked as tv series do fail and often. Just a thought

**Comment by empanadablues** [comment] 2020-09-02 16:59
I have almost resolved my problems. I'm pretty sure that, at least in my case were local network problems (and I suspect that in the majority of the cases you can find on the internet, too). 
Wifi problems actually. 
I have been using wifi5G, which is suffering random problems, perhaps interferences, but I'm not sure about the reason.
When received the pi4 I switched to wifi5G (which at least in my pi3 it's not well supported), in the hope that it'll end some wifi random problems...but it's even worse. Even my laptops disconnect sometimes from the wifi5G to regain acces to wifiG automatically. There is a big mess with a lot of wifi networks interfering between all of them. Wifi5G was supposed to reduce those problems with higher frequency (so higher bandwith) and less radio lenght signal (inherent to the higher frequency at same power)...but it seems that the theory it's not well achieved in the practice.
If you have the oporttunity, try ethernet cable , at least for diagnosis.

**Comment by dommy67** [comment] 2020-09-20 23:38
Out of curiosity I installed Fedora 32 then the flatpak version of Kodi - their latest is 18.7 - added Amazon VOD testing , Netflix and MythTv -- All works correctly . I have no dropout issues with Amazon VOD.

**Comment by Varstahl** [comment] 2020-09-21 07:26
Thanks for the confirmation. Closing this thread as it's abundantly clear the issues are not related to the addon per se.

**Closed by Varstahl** 2020-09-21 07:26 UTC
Labels: invalid
