### ISSUE TITLE
Accessing Watchlist (error)

### ISSUE THREAD

**Issue by jpdev123** [Sandmann79/xbmc#507] opened 2020-09-20 12:56 UTC
**Addon used**
- [X] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 

**Account type**
- [X] primevideo.com
- [ ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware:
- OS version:
- Kodi version number:

LibreELEC (official): 9.2.5 (RPi4.arm),  Kodi 18.8

**Upload Logs**

**Describe the bug**

```
2020-09-20 14:14:20.876 T:1991701360  NOTICE: [Amazon VOD] Version: 0.8.8
2020-09-20 14:14:20.876 T:1991701360  NOTICE: [Amazon VOD] Unicode filename support: False
2020-09-20 14:14:20.877 T:1991701360  NOTICE: [Amazon VOD] Locale: en-us / Language: pl
2020-09-20 14:14:24.795 T:1991701360   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: u'filters'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/default.py", line 5, in <module>
                                                EntryPoint()
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/startup.py", line 63, in EntryPoint
                                                elif 'browse' == verb: g.pv.Browse(path)
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/primevideo.py", line 310, in Browse
                                                node, breadcrumb = self._TraverseCatalog(path)
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/primevideo.py", line 206, in _TraverseCatalog
                                                self._LazyLoad(node[nodeName], pathList[0:1 + i])
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/primevideo.py", line 1015, in _LazyLoad
                                                for f in wl['filters']:
                                            KeyError: u'filters'
                                            -->End of Python script error report<--
2020-09-20 14:14:25.287 T:1991701360 WARNING: CPythonInvoker(95, /storage/.kodi/addons/plugin.video.amazon-test/default.py): the python script "/storage/.kodi/addons/plugin.video.amazon-test/default.py"
2020-09-20 14:14:25.301 T:2027930480   ERROR: GetDirectory - Error getting plugin://plugin.video.amazon-test/pv/browse/root/Watchlist
```

**Comment by Varstahl** [comment] 2020-09-25 17:13
Confirmed in some cases such as Kids profile. Investigating.

**Comment by Varstahl** [comment] 2020-09-25 17:53
@jpdev123 can you confirm that when you accessed your watchlist it was empty?

**Comment by jpdev123** [comment] 2020-09-26 07:56
My watchlist was/is not empty.

**Comment by Varstahl** [comment] 2020-09-26 08:20
Ok, then try to access the watchlist with the following nightlies:
Leia: [plugin.video.amazon-test-0.8.9~beta.zip](https://github.com/Sandmann79/xbmc/files/5286389/plugin.video.amazon-test-0.8.9.beta.zip)
Matrix: [plugin.video.amazon-test-0.8.9~beta+matrix.1.zip](https://github.com/Sandmann79/xbmc/files/5286390/plugin.video.amazon-test-0.8.9.beta%2Bmatrix.1.zip)

If it still doesn't work, open "Settings > Miscellaneous" and enable "Dump JSON replies" and try to access the watchlist again. You will find a bunch of JSONs in the same place as the catalog/video data cache files. ZIP them up and attach them to a reply, so that I can take a look.

Note: if you enable JSON replies but it still doesn't output any, you might need to restart Kodi.

**Comment by jpdev123** [comment] 2020-09-26 09:39
Installation of Leia-0.8.9 beta.zip did not work/install on my Leia Kodi 18.8. I have manually replaced files in .kodi/addons/plugin.video.amazon-test and it did not crashed but my watchlist was empty. Next I have replaced files in plugin.video.amazon-test with version 0.8.8 and it works now but the watchlist is empty too. On my APV account I have 4 profiles how can I select one?

**Comment by jpdev123** [comment] 2020-09-26 10:07
Ok, I did refresh on my watchlist and it crashed (0.8.8), watchlist on my 1st created APV profile (default?) was empty.
I've added one movie to it on default profile and it works now. How can I select one profile by name?

**Comment by Varstahl** [comment] 2020-09-26 12:30
> How can I select one profile by name?

It's coming with 0.8.9 shortly, I've just implemented the feature, you can test it by manually installing the updates from the current nightly zip I've provided above or just waiting a few days for the release.

Since both issues are effectively solved, I'm closing this issue.

**Closed by Varstahl** 2020-09-26 12:30 UTC
Labels: bug, primevideo
