### ISSUE TITLE
Bug in Kodi 18 for x64  in Windows 10 x64

### ISSUE THREAD

**Issue by Ninoh-FOX** [Sandmann79/xbmc#98] opened 2018-03-08 13:10 UTC
Hi, the addon inputstream helper install well widevine in Kodi 18 for x32 and all works fine, but, if I install the kodi 18 for x64, when I reinstall widevine, the playback stream video fail.

this is the log file from kodi x32 system:

[kodi x32.log](https://github.com/Sandmann79/xbmc/files/1793232/kodi.x32.log)

and this is the log file from kodi x64 system:

[kodi x64.log](https://github.com/Sandmann79/xbmc/files/1793237/kodi.x64.log)

I tried uninstall python 2.7 for x86 and reinstall python 2.7 for x64 and reinstall pip scripts (crypto, cryptodome/x, etc...) but only work for me the version x32.

**Comment by Varstahl** [comment] 2018-03-08 14:29
The problem is not with the addon and not with widevine as far as I can tell. A few excerpts:
```
01:06:24.201 T:8612   ERROR: CCurlFile::FillBuffer - Failed: SSL connect error(35)
01:06:24.201 T:8612   ERROR: CRepository: failed read 'https://github.com/alfa-addon/alfa-repo/raw/master/addons.xml.md5'

01:06:24.328 T:10168   ERROR: CCurlFile::FillBuffer - Failed: SSL connect error(35)
01:06:24.781 T:4880  NOTICE: [plugin.video.quasar] [GIN] 2018/03/07 - 01:06:24 | 200 [0m|       2.7578s | ::1 |  [0m GET     /repository/scakemyer/plugin.video.quasar/addons.xml.md5
01:06:24.793 T:10168   ERROR: CCurlFile::FillBuffer - Failed: SSL connect error(35)

01:06:55.547 T:7548  NOTICE: VideoPlayer::OpenFile: https://a98avoddashs3ww-a.akamaihd.net/d/2$L-fumvuiTQF4EAdPpRgG1HUA_UI~/ondemand/dub-dub-iad/834c/3d07/bd9d/4f01-a105-0d68de418e71/a6c88852-cc40-4213-8610-c299f2e3ff1b_corrected.mpd
01:06:55.572 T:9796  NOTICE: Creating InputStream
01:06:55.909 T:9796   ERROR: CCurlFile::FillBuffer - Failed: SSL connect error(35)
```

As far as I remember, there's no difference for Kodi for the x86/x64, but Kodi does come and use its own bundled python interpreter. I'm not sure what's wrong in your setup, but it's clear it's an SSL error of sorts, and **none** of your connections go out, regardless of the addon. If you're using a proxy or some sort of sniffer that changes the SSL certificate, you might be unable to make it work.

Question: after you switch versions, do you also reinstall the addons and repositories? Since the addons require various dependencies that get installed by Kodi, you might have orphaned dependencies.

**Comment by Ninoh-FOX** [comment] 2018-03-08 14:47
No, I not reinstall addons after switch version, because all dependencies is ok.

**Comment by Varstahl** [comment] 2018-03-08 14:59
Well, the problem is with curl or SSL configuration. Apparently there's a problem with [Kodi's x64 packaging](https://forum.kodi.tv/showthread.php?tid=324043): [here's the comment with the fix](https://forum.kodi.tv/showthread.php?tid=324043&pid=2670924#pid2670924); and [here's the most recent version](https://dl.uxnr.de/build/curl/curl_winssl_msys2_mingw64_stc/curl-7.58.0/curl-7.58.0.zip) of the cURL DLL you need to overwrite the one in Kodi's installation.

I'm closing this as it has nothing to do with the addon.

**Closed by Varstahl** 2018-03-08 14:59 UTC
Labels: invalid

**Comment by Ninoh-FOX** [comment] 2018-03-08 15:09
thanks.
