### ISSUE TITLE
Amazon VOD no longer working after installing the latest nightly

### ISSUE THREAD

**Issue by oomek** [Sandmann79/xbmc#105] opened 2018-03-17 15:20 UTC
I'm getting Amazon VOD Error when I try to launch the addon.
Strange that it was working perfectly before, I have no idea what has changed it.

here is the log:
https://paste.ubuntu.com/p/y5cmw8wsJm/

**Comment by Varstahl** [comment] 2018-03-17 18:11
Hmm, as I just noticed, `Error reason: ('Connection aborted.', error(10054, 'An existing connection was forcibly closed by the remote host')) (ConnectionError)` and we don't really manage the connection error in that portion. So by the looks of it, it's either a problem with packet sniffing, some sort of connection error on your end or amazon's end, or simply something just went FUBAR.

I'll flag this as a bug, as we need to handle such connection problems, but it's just that, a connection problem, not something wrong with the addon per se.

I'm not sure why it's failing either, everything seems to be working on my end.

**Comment by oomek** [comment] 2018-03-17 18:32
I've tried reinstalling the addon, but now the same error appears when I try to sign in

**Comment by Varstahl** [comment] 2018-03-18 12:18
Question: are you able to open [this URL](https://na.api.amazonvideo.com/cdp/usage/v2/GetAppStartupConfig?deviceTypeID=A28RQHJKHM2A2W&deviceID=d03436317166468b9966b3dd3b272286&&firmware=fmw%3A22-app%3A3.0.211.123001&version=1&format=json)?

**Comment by Varstahl** [comment] 2018-03-18 12:28
So it should work, I don't see why the addon has problems. The problem you are experiencing with the addon is during a call to that URL, where the server rejects it. I don't really understand why is that.

@Sandmann79 got any ideas on the matter?

**Comment by oomek** [comment] 2018-03-18 12:31
May I ask which kodi version are you running? x86 or x64 ?

**Comment by Varstahl** [comment] 2018-03-18 12:33
Personally I think I'm running 2 x64 versions, one on win for development and testing and the other on debian.

**Comment by oomek** [comment] 2018-03-18 12:39
I'm asking because win64 nightly builds are being packaged with outdated libcurl.dll v7.52.1 which breaks many plugins relying on he https. The fix is to replace the file inside the kodi folder with the libcurl.dll v7.56.1 This fixes the Youtube, scrappers, etc. I'm not sure if Amazon VOD also relies on it, so I wrote it just in case it gives any clue.

**Comment by oomek** [comment] 2018-03-18 13:24
I tried again clean with wiped profile folder, installed repo, Amazon and Amazon VOD addons. 
Amazon addon allows me to log in, but I get infinite spinner when I try to play a movie. Amazon VOD still does not allow me to log in.

**Comment by oomek** [comment] 2018-03-30 11:18
Any news on that topic by any chance?

**Comment by Varstahl** [comment] 2018-03-30 11:47
I am literally unable to reproduce your problem in any way. Both the old build and the latest nightly from two days ago work perfectly fine on both debian and win7 x64.

**Comment by Varstahl** [comment] 2018-04-25 16:39
I've added the log enhancements to the main branch, and even with a clean brand new installation of kodi straight from the nightly builds, I'm unable to reproduce any of the issues you describe, I'm still convinced it's a network/proxy/firewall related issue rather than an issue with the addon itself. Feel free to reopen if you have new information.

**Closed** 2018-04-25 16:43 UTC
Labels: bug, enhancement, invalid

**Comment by oomek** [comment] 2018-04-25 17:03
I've tried 0.5.4 beta. Same thing. Nothing happens when I click on Sign in. I do not have any popup with additional error or any other entries in the log apart from the aforementioned 10054 error. My firewall/defender are disabled. I do not have any additional AV. Firewall on the modem is also off.

**Comment by Varstahl** [comment] 2018-04-25 17:08
Remind me again, what OS and architecture are you on? I've looked back at your logs and nothing screams at addon doing something wrong. Since I think you've told me you've updated from the nightly build, may you try again and post a new log? I'd love to help you fix it and understand the problem, but if it stops at the freaking "connection closed" I can't go much further.

**Comment by oomek** [comment] 2018-04-25 17:12
Windows 10 Pro x64, Asrock J4205-ITX MB with Intel Pentium J4205 CPU
libcurl.dll replaced with the newer version in Kodi's folder to get rid of the ssl errors in video plugins and scrappers.

**Comment by oomek** [comment] 2018-04-25 17:13
As a last resort I'm trying now to flush the DNS

**Comment by Varstahl** [comment] 2018-04-25 17:39
```
18:19:25.764 T:8980  NOTICE: [Amazon VOD] getURL: https://na.api.amazonvideo.com/cdp/usage/v2/GetAppStartupConfig?deviceTypeID=A28RQHJKHM2A2W&deviceID=f70a8cadae662039ecca5b41a84e1479c8e55863fe443d73dab41fcd&firmware=1&version=1&format=json
18:19:26.270 T:8980   ERROR: [Amazon VOD] Error reason: ('Connection aborted.', error(10054, 'An existing connection was forcibly closed by the remote host')) (ConnectionError)
```

I can't understand this for the life of me. I'm also having absolutely no problem with kodi's curl lib version embedded into Kodi's installer. There might be some problems with W10, but I don't have any laying around, I kind of banned it from my home and office, I'll have to look it up.

I'll just ask again, but this is so weird that I must: are you absolutely sure that with the [lastest nightly](http://mirrors.kodi.tv/nightlies/windows/win64/master/) and installing only the `Amazon VOD` plugin without touching any file from kodi it still doesn't work? (You can backup `%AppData%\Kodi` in an archive somewhere and then clear everything in it, to ensure there isn't something wrong somewhere in the settings or other plugins).

**Comment by oomek** [comment] 2018-04-25 17:50
I'm on the latest nightly. The libcurl.dll shipped with Kodi for some reason refuses to work on my machine so I use this one:
https://curl.haxx.se/download.html
Win64 - Generic: Win64 x86_64 CAB

It does not matter If I run clean with renamed Kodi folder from appdata or not I've tried that many times.
It's an absolute mystery to me.

**Comment by Varstahl** [comment] 2018-04-25 18:46
Ah, k, glad you somehow solved it or at least pin-pointed the problem to a specific machine. Best of luck.
