### ISSUE TITLE
Since a few days Amazon VOD does not start- only the busy circle is shown 

### ISSUE THREAD

**Issue by cow-crash** [Sandmann79/xbmc#695] opened 2023-06-30 10:27 UTC
**Addon used**
- [x] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 0.9.8

**Account type**
- [ ] primevideo.com
- [x] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: raspberry pi 3
- OS version: LibreELEC 9.2.8
- Kodi version number: 18.9

**Upload Logs**

**Describe the bug**
Since a few days after starting the plugin the busy circle appear and noting else happens.
here's the kodi.log:
....
2023-06-30 12:10:31.888 T:1397486464  NOTICE: [Amazon VOD] Version: 0.9.8
2023-06-30 12:10:31.889 T:1397486464  NOTICE: [Amazon VOD] Unicode filename support: False
2023-06-30 12:10:31.890 T:1397486464  NOTICE: [Amazon VOD] Locale: en-us / Language: de
2023-06-30 12:10:31.938 T:1937553856 WARNING: CGUIMediaWindow::OnMessage - updating in progress
2023-06-30 12:10:32.148 T:1397486464   ERROR: [Amazon VOD] No JSON objects found in the page
2023-06-30 12:10:35.357 T:1410331520   ERROR: Previous line repeats 1 times.
2023-06-30 12:10:35.357 T:1410331520 WARNING: CPythonInvoker(7, /storage/.kodi/addons/plugin.video.amazon-test/default.py): the python script "/storage/.kodi/addons/plugin.video.amazon-test/default.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon7xbmcgui6DialogE,N9XBMCAddon9xbmcaddon5AddonE,N14PythonBindings31XBMCAddon_xbmc_Monitor_DirectorE
2023-06-30 12:10:35.366 T:1422893952   ERROR: GetDirectory - Error getting plugin://plugin.video.amazon-test/
2023-06-30 12:11:18.377 T:1937553856  NOTICE: Samba is idle. Closing the remaining connections

**Comment by Sandmann79** [comment] 2023-07-29 12:34
Duplicate of #696 .
Try the current beta from here: https://github.com/Sandmann79/xbmc/issues/696#issuecomment-1653343463

**Closed by Sandmann79** 2023-07-29 12:34 UTC
