### ISSUE TITLE
Automaticaly export Amazon Vod

### ISSUE THREAD

**Issue by Faren81** [Sandmann79/xbmc#333] opened 2019-10-15 07:46 UTC
Hi All,
how it 's going ?

i'm not sure what that I'm writing an issue or not. I'm having problem to understand how to export the content and create an strm or simililary to add it to the library of kodi.
All options of the addon are on and the settings if the default.

Many thanks in advance for you help,
Enrico

**Comment by Varstahl** [comment] 2019-10-15 09:56
No worries. If I remember correctly library export in Amazon VOD for PrimeVideo.com is not done yet. It's one of the features that keep getting delayed. There are other addons that can export to library for it, although at this moment I don't recall the names.

**Comment by TehTux** [comment] 2019-10-22 18:25
> There are other addons that can export to library for it, although at this moment I don't recall the names.

OSMOSIS?

**Comment by Varstahl** [comment] 2019-10-24 05:58
The name rings a bell, but I'm not sure, although there should be at least a couple working fine. I read of people talking about it [in this Kodi forum](https://forum.kodi.tv/showthread.php?tid=331136), you might find your answer there, if you didn't find it already.

**Comment by TehTux** [comment] 2019-10-24 09:37
I use OSMOSIS for Amazon VOD and it works very well! :)

**Comment by Faren81** [comment] 2019-10-24 11:07
Hi All,
i'm trying Osmosis and work fine...but i don't undenstand if the configuration on DB work really.

Thanks

**Comment by Varstahl** [comment] 2019-11-15 20:09
Closing this as dupe of #150

**Closed by Varstahl** 2019-11-15 20:09 UTC
Labels: duplicate
