### ISSUE TITLE
Sign in works in LibreELEC but not in Kodi with Raspbian on Pi 4

### ISSUE THREAD

**Issue by tech-avid** [Sandmann79/xbmc#403] opened 2020-01-24 18:50 UTC
Amazon VOD sign in works fine on LibreELEC Leia on Raspberry Pi 4.
Amazon VOD sign in stuck on spinning wheel in Kodi Leia in Raspbian on Pi 4.

**Addon used**
- [x ] Amazon VOD (plugin.video.amazon-test)
- [ ] Amazon (plugin.video.amazon)
- [ ] Browser Launcher (plugin.program.browser.launcher)
- Addon Version [e.g. 0.7.5]

**Prime Video Account (select one)**
- [ ] primevideo.com
- [ x] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: [e.g. RPi]
- OS Version: [e.g. Windows 10]
- Kodi Version [e.g. 18.4]

**Upload Logs**
Upload `kodi.log` somewhere and post the link here. If you need help finding it, [read the appropriate entry in the FAQs](https://github.com/Sandmann79/xbmc/wiki/FAQ#what-is-debug-logging--how-can-i-enable-debug-logging-in-kodi).
For Login issues, enable advanced logging in the settings, upload the `(amazon/avod)-login` files from the [Kodi Home](https://kodi.wiki/view/Special_protocol) folder, and paste the link here, as well.

**Describe the bug**

**Comment by Varstahl** [comment] 2020-01-24 19:23
The issue is not properly compiled, vital information are missing, along with the full log. Closing this soon unless more info are provided.

**Comment by tech-avid** [comment] 2020-01-24 20:49
I am using a Raspberry Pi 4 with Raspbian Buster.
Here is the kodi.log
[kodi.log](https://github.com/Sandmann79/xbmc/files/4110634/kodi.log)

**Comment by Varstahl** [comment] 2020-01-25 13:59
```
 ERROR: [Amazon VOD] Error reason: HTTPSConnectionPool(host='na.api.amazonvideo.com', port=443): Max retries exceeded with url: /cdp/usage/v2/GetAppStartupConfig?deviceTypeID=A28RQHJKHM2A2W&deviceID=b363b4fb2c55fb81f0e4628e35eaaa9caa5d65ebaa3d010b9408865f&firmware=1&version=1&format=json (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl_choose_client_version', 'unsupported protocol')],)",),)) (SSLError)
```

na.api.amazonvideo.com supports only TLS v1, debian enforces TLS v1.2+ [ref](https://github.com/Sandmann79/xbmc/issues/326#issuecomment-546262203).

**Closed by Varstahl** 2020-01-25 13:59 UTC
Labels: duplicate, invalid
