### ISSUE TITLE
getURL spams kodi.log 

### ISSUE THREAD

**Issue by mlc42** [Sandmann79/xbmc#330] opened 2019-10-02 19:10 UTC
Last version seem to work fine but every 5 minutes this entry appears: 

2019-10-02 20:54:20.248 T:1508897664  NOTICE: [Amazon] getURL: https://atv-ps-eu.amazon.de/cdp/catalog/Browse?firmware=fmw:17-app:2.0.45.1210&deviceTypeID=A2M4YX06LWP8WI&deviceID=8a753b09edf940f0aa8de0d08f39f4cb20b7f824cc0a1e875820aced&format=json&StartIndex=980&NumberOfResults=140&ContentType=TVEpisode&RollUpToSeason=T&OrderBy=Title&OfferGroups=B0043YVHMY&ContractID=UX*&IncludeBlackList=T&HideNum=T&AID=1&IncludeNonWeb=T&IncludeAll=T&version=2
2019-10-02 20:54:20.602 T:1508897664  NOTICE: Previous line repeats 3 times.
2019-10-02 20:54:20.602 T:1508897664  NOTICE: [Amazon] Waiting 5min

**Comment by Sandmann79** [comment] 2019-10-03 15:10
Duplicate of #320

**Closed by Sandmann79** 2019-10-03 15:10 UTC
