### ISSUE TITLE
Kodi locks up when playing Prime Movie

### ISSUE THREAD

**Issue by satmandu** [Sandmann79/xbmc#226] opened 2018-12-29 03:17 UTC
Kodi playing Prime TV shows just fine.

When playing a Prime move (Movies -> Best of Prime Movies -> Any movie on this list) Kodi freezes.

I have to remote in to restart Kodi at this point.

log:
http://paste.ubuntu.com/p/WDDRJXtPhF/

The problem here isn't that it isn't able to play the video. The problem is that an unplayable video should not cause Kodi to freeze.

Running a current version of the plugin on official kodi 18 nightly on ubuntu.

**Comment by Varstahl** [comment] 2018-12-29 13:35
I'm sorry but I honestly don't really see the problem. Skimming through the logs:
```
 ERROR: [Amazon VOD] Cannot complete request. (prs.norights.notowned)
 DEBUG: [Amazon VOD] Playing Dummy Video
  INFO: ffmpeg[7F0CC75AE700]: Input #0, avi, from '[…]/resources/dummy.avi'
NOTICE: CVideoPlayer::CloseFile()
NOTICE: VideoPlayer: waiting for threads to exit
```
If we can't reproduce the stream, in order to avoid annoying popups and error triggers for the user, we just play a small video, and then signal to close it. Kodi received all the instructions and the "stop playback" signal sent by the addon correctly, and began its own thread signaling about stopping reproduction.

Whatever it is, it's not the addon that's hanging Kodi, is Kodi that's hanging itself, for whatever reason.

Also, I wanted to point out that `prs.norights.notowned`, which means you can't actually watch those movies. If you can watch them in a browser, maybe you logged in a different linked account?

Anyway, closing the issue as there's nothing wrong from the addon itself, you must bring this issue to Kodi devs if anything.

**Closed by Varstahl** 2018-12-29 13:35 UTC
