### ISSUE TITLE
Video not working on a raspberry pi 3 bash/script

### ISSUE THREAD

**Issue by Buisson** [Sandmann79/xbmc#134] opened 2018-06-11 23:04 UTC
Hi I am trying to read video from your plugin, I tried to use my own script : 

```
#!/bin/sh
/usr/bin/chromium $2
```

This is the error message in log when I choose a video from a list: (I am in France maybe it is the problem)

```
01:02:06.149 T:1319998208  NOTICE: [Amazon VOD] Using Host: Level3
01:02:06.154 T:1319998208  NOTICE: [Amazon VOD] getURL: https://12s3.lvlt.dash.row.aiv-cdn.net/d/2$j1noK1R4I_3f4TawFJdVZCKBNds~/prod/dub/075a/8159/56a6/45df-bea0-634e1c413649/68aede4e-679d-49af-97ec-7f6dba593f9a_corrected.mpd
01:02:06.827 T:1319998208  NOTICE: [Amazon VOD] Executing: /home/osmc/lancerChromium.sh 23.976 "https://www.primevideo.com/dp/0RV4ZK2B4LQJJH2MS1D2JKP44O/?autoplay=1"
01:02:06.879 T:1319998208  NOTICE: [Amazon VOD] Run command: xdotool mousemove 9999 540
01:02:06.940 T:1319998208  NOTICE: [Amazon VOD] Returncode: 127
01:02:06.942 T:1319998208  NOTICE: [Amazon VOD] Starting Thread
01:02:08.036 T:1585443584  NOTICE: [Amazon VOD] Stopping Thread
01:02:08.117 T:1926228480  NOTICE: VideoPlayer: Opening: /home/osmc/.kodi/addons/plugin.video.amazon-test/resources/dummy.avi
01:02:08.118 T:1926228480 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
01:02:08.118 T:1585443584  NOTICE: Creating InputStream
01:02:08.121 T:1585443584  NOTICE: Creating Demuxer
01:02:08.122 T:1585443584  NOTICE: Opening stream: 0 source: 256
01:02:08.122 T:1585443584  NOTICE: Creating video codec with codec id: 14
01:02:08.123 T:1585443584   ERROR: CMMALVideo::Open : Video codec unknown: e
01:02:08.123 T:1585443584  NOTICE: CDVDVideoCodecFFmpeg::Open() Using codec: raw video
01:02:08.123 T:1585443584  NOTICE: Creating video thread
01:02:08.123 T:1480811264  NOTICE: running thread: video_thread
01:02:08.123 T:1585443584  NOTICE: CVideoPlayer::OnExit()
01:02:08.124 T:1585443584  NOTICE: VideoPlayer: eof, waiting for queues to empty
01:02:08.124 T:1585443584  NOTICE: Closing stream player 2
01:02:08.124 T:1585443584  NOTICE: waiting for video thread to exit
01:02:08.127 T:1480811264   ERROR: Got MSGQ_ABORT or MSGO_IS_ERROR return true
01:02:08.127 T:1480811264  NOTICE: thread end: video_thread
01:02:08.127 T:1585443584  NOTICE: deleting video codec
01:02:08.208 T:1926228480  NOTICE: CVideoPlayer::CloseFile()
01:02:08.208 T:1926228480  NOTICE: VideoPlayer: waiting for threads to exit
01:02:08.208 T:1926228480  NOTICE: VideoPlayer: finished waiting
01:02:08.208 T:1926228480  NOTICE: CVideoPlayer::CloseFile()
01:02:08.208 T:1926228480  NOTICE: VideoPlayer: waiting for threads to exit
01:02:08.208 T:1926228480  NOTICE: VideoPlayer: finished waiting
```

Thank for your help :)

**Comment by Varstahl** [comment] 2018-06-12 10:39
It shouldn't be a problem. Kodi expects a video played in these cases, but since it's managed externally we start a dummy avi. Since it's an uncompressed video, it just reads it raw `FFmpeg::Open() Using codec: raw video`. It's all normal.

Unless you have a specific problem those are just kodi log/debug messages, nothing out of the ordinary.

**Comment by Buisson** [comment] 2018-06-12 12:23
I just get a message telling me something went wrong in french and I have to check the log file for more information. Do you think it is because I am using chromium ?

the problem is maybe that line : 

`ERROR: Got MSGQ_ABORT or MSGO_IS_ERROR return true`

I don't know how to fix it :(

**Comment by Varstahl** [comment] 2018-06-12 12:43
> I am on kodi 17 Krypton maybe here is the problem

It's possible. Most of our tests are with IS.A and Kodi 18, and I've only started developing with Leia. I'm not familiar enough with Kodi ran on Rasps, so I personally don't really know how to help you, when the problem is outside the addon itself.

**Comment by Buisson** [comment] 2018-06-12 13:51
I'll try on a Kodi 18 tonight. 

I'll keep you informed.

**Comment by Buisson** [comment] 2018-06-13 08:11
I have tried to install Kodi 18 on my OSMC but after multiple try I've give up. 

I tried that : https://discourse.osmc.tv/t/testing-kodi-18-leia-builds-for-raspberry-pi/20631

**Comment by Buisson** [comment] 2018-06-13 09:03
@Sandmann79 : 

> Did you started Chromium outside from Kodi, to test if it works?
How can I do that ?

> With this one liner in your script, you can bypass the script and add the following line as script path at settings. /usr/bin/chromium {u}

Ok I'll try that

> Btw, on Kodi 18 you can use Inputstream as playback method.

Yes but I do not understand how to upgrade to Kodi 18 on my raspberry pi 3 with osmc. :/ if someone know how to do it :) .

**Comment by Varstahl** [comment] 2018-06-13 09:18
> Yes but I do not understand how to upgrade to Kodi 18 on my raspberry pi 3 with osmc

There's [this thread](https://forum.kodi.tv/showthread.php?tid=298775) on Kodi forums. Seems pretty legit. 

The guide you were using is 2 years old and no longer accurate.

**Comment by Sandmann79** [comment] 2018-06-13 10:56
@Buisson just use the command line. Look here how to access: https://osmc.tv/wiki/general/accessing-the-command-line/

**Comment by Buisson** [comment] 2018-06-13 12:54
@Varstahl 

> The guide you were using is 2 years old and no longer accurate.

Yes but your guide do the same things as mine :/ .


@Sandmann79 : 

On command line I run chromium ? And after ?

**Comment by Varstahl** [comment] 2018-06-13 13:10
> Yes but your guide do the same things as mine :/

Whops, you're absolutely correct, my bad.

> On command line I run chromium ? And after ?

It's just a test to see if chromium is actually starting correctly. You can try running `/usr/bin/chromium www.primevideo.com` from the shell, and see if the process ends with an error or opens the page successfully.

**Comment by Varstahl** [comment] 2018-08-02 10:43
@Buisson any update on the issue?

**Comment by Varstahl** [comment] 2018-10-03 20:58
Closing the issue as there have been no updates in the past 4 months.

**Closed by Varstahl** 2018-10-03 20:58 UTC
