### ISSUE TITLE
No sound in some films or series (v.0.7.1 on kodi 18.1)

### ISSUE THREAD

**Issue by isard** [Sandmann79/xbmc#297] opened 2019-04-17 18:14 UTC
I have a Raspberry Pi 3 with LibreELEC 9.0.1 (kernel Linux 4.19.23, Kodi 18.1 Git: newclock5_18.1-Leia). Sometimes (without a known pattern) Amazon VOD does not play audio although video is perfect (good definition, fluid), sometimes it works perfectly.

I tried rebooting and reinstalling Amazon VOD, I searched through FAQs and Issues but... couldn't find a solution.

Any help is apreciated.

**Comment by Varstahl** [comment] 2019-04-17 18:24
Duplicate of #164, reasons unknown, no known solutions.

**Closed by Varstahl** 2019-04-17 18:24 UTC
