### ISSUE TITLE
The watchlist is not working with Prime Video Spain

### ISSUE THREAD

**Issue by Paco8** [Sandmann79/xbmc#225] opened 2018-12-27 20:30 UTC
My watchlist is empty. Using the refresh option does nothing.

The log:

18:07:28.698 T:200148174064   DEBUG: [Amazon VOD] {'path': 'root-//-Watchlist', 'mode': 'PrimeVideo_Refresh'}
18:07:28.726 T:200148174064  NOTICE: [Amazon VOD] getURL: https://www.primevideo.com/watchlist/
18:07:29.759 T:200148174064    INFO: CPythonInvoker(4, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.amazon-test/default.py): script successfully run

I guess Amazon is using a different format for the watchlist page and the addon fails to find the information of the videos.

I attach the page source of the watchlist.

[watchlist.zip](https://github.com/Sandmann79/xbmc/files/2713304/watchlist.zip)

**Comment by Varstahl** [comment] 2018-12-28 03:33
Noticed today as well, I think they changed the watchlist page again. I was currently looking to crack 4k resolutions, so I didn't touch it yet. I'll look at it as soon as I can (or as soon as I remember to).

**Comment by Varstahl** [comment] 2018-12-28 14:03
Why have meaningful names for classes that were previously used for Watchlist, when you can have deep names like `_2aLlvK`, `_1p2QcZ`, `_28FDFY`, `_3twHsa`. I hate Amazon, really. And I'm writing it down, here, lest we forget.

**Comment by Varstahl** [comment] 2018-12-28 15:33
Fixed in 9d3ae584b7a97c1e3b75941219c1db9e7b0a3498, but I failed hard on the commit text, so I'm closing manually.

**Comment by Paco8** [comment] 2018-12-29 21:31
The movie folder works, but when I try to enter in the TV shows there's an error and the folder doesn't open.

This is the log:

```
22:11:48.744 T:205971248368  NOTICE: [Amazon VOD] getURL: https://www.primevideo.com/watchlist/tv/ref=atv_wtlp_tv?page=1&amp;sort=DATE_ADDED_DESC
22:11:49.317 T:205971248368   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: u'mediatype'
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.amazon-test/default.py", line 5, in <module>
                                                EntryPoint()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.amazon-test/resources/lib/startup.py", line 83, in EntryPoint
                                                g.pv.Browse(None if 'path' not in args else args['path'])
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.amazon-test/resources/lib/primevideo.py", line 189, in Browse
                                                self._LazyLoad(node, nodeName)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.amazon-test/resources/lib/primevideo.py", line 458, in _LazyLoad
                                                if ('unavailable' not in self._videodata[refUrn]['metadata']) and ('season' == self._videodata[refUrn]['metadata']['videometa']['mediatype']):
                                            KeyError: u'mediatype'
                                            -->End of Python script error report<--
```

**Comment by Varstahl** [comment] 2018-12-29 21:44
That's possibly corruption of the video data. Try to backup and remove the *.pvcp and *.pvdp, then try again.

**Comment by Paco8** [comment] 2018-12-29 23:57
It works now. Thank you.

**Comment by Paco8** [comment] 2019-01-02 09:49
I had the same problem again, same error. Deleting those files fixed it, but I guess there's something that corrupts the data.

**Comment by Paco8** [comment] 2019-01-07 18:11
I keep having this problem once and again, so I tried to debug it.
I think this happens because one of the TV shows in my watchlist is not available anymore, so the 'mediatype' for this show in primevideo.py in line 491 doesn't exist, and makes that code to crash.
It would great if you can a test for that condition to prevent the crash.

**Comment by Varstahl** [comment] 2019-01-07 18:47
It shouldn't, but I'll check.

**Comment by Varstahl** [comment] 2019-01-09 18:47
@Paco8 I checked again and as I suspected, even with seasons that are not available anymore, there is no problem whatsover. The unavailable seasons are correctly ignored. As it stands I can't help you because I can't reproduce the error.

If you want you can reopen Kodi [with debug logging enabled (ref.)](https://github.com/Sandmann79/xbmc/wiki/FAQ#what-is-debug-logging--how-can-i-enable-debug-logging-in-kodi), make it crash on the watchlist, then close it and zip together the log and the cache files. You can attach the zip to a reply here, so I can take a look.

**Comment by Paco8** [comment] 2019-01-11 20:33
I attach the requested files.

This is a more detailed explanation of the problem. My watchlist includes a TV show (0JKSXG4UZH269AUAAEQOZ3BTSS) with no episodes available.

When I delete the cache files the addon downloads the information about all TV shows from my watchlist and everything works fine, no crash. That show with no episodes is not shown in the list (I guess this is correct).

Everything works fine for some time until the cache expires, then I guess it tries to update the list and this is when the crash happens. 

I added some Log calls in primevideo.py to try to figure out what the code is doing. I even managed to export the pvcp and pvdp files to json so I could take a look at the information stored.

I think the catalog doesn't have any information about that show. The videodata does, but it's almost empty. 

```
    "0JKSXG4UZH269AUAAEQOZ3BTSS": {
        "children": [], 
        "metadata": {
            "videometa": {}
        }
    }, 
```

The crash happens in the line 491 when the code tries to read videodata[refUrn]['metadata']['videometa']['mediatype'] but mediatype doesn't exist for that show.

I couldn't figure out why this happens. Maybe it couldn't parse the data from the web page or it discarted it since there are no episodes available.

I added this line before line 491 to prevent the crash, and so far I think it's working well:

`if (not 'mediatype' in self._videodata[refUrn]['metadata']['videometa']): continue;`

Maybe not related but I also noticed something strange in the data in the catalog, some season titles have html tags attached. For example:

`"Temporada 1</span>\n <div class=\"av-badges\">\n <span data-automation-id=\"release-year-badge\" class=\"av-badge-text\">2016</span><span data-automation-id=\"maturity-rating-badge\" class=\"av-badge-text\">SC</span><a href=\"#btf-product-details\"><span data-automation-id=\"subtitles-and-cc-badge\" class=\"av-icon av-icon--subtitles\" title=\"Subtítulos y subtítulos para personas con problemas de audición\"><span class=\"avu-screen-reader-only\">Subtítulos y subtítulos para personas con problemas de audición</span></span>"`

[files.zip](https://github.com/Sandmann79/xbmc/files/2751055/files.zip)

**Comment by Varstahl** [comment] 2019-01-17 16:43
Sorry man, also for the wait. I took your files, embedded and tested them, but it just doesn't crash. I'm unable to make it crash anywhere, everything seems correct, even in the catalog. Loaded up the catalog, Went into Watchlist and TV series, everything works correctly.

Also I just noticed that the line numbers don't quite match. It seems to me you're using a way old version, which might include a number of fixes, and could also explain why I'm not witnessing any problem.

> `"Temporada 1</span>\n <div class=\"av-badges\">\n <span data-automation-id=\"release-year-badge\" class=\"av-badge-text\">2016</span><span data-automation-id=\"maturity-rating-badge\" class=\"av-badge-text\">SC</span><a href=\"#btf-product-details\"><span data-automation-id=\"subtitles-and-cc-badge\" class=\"av-icon av-icon--subtitles\" title=\"Subtítulos y subtítulos para personas con problemas de audición\"><span class=\"avu-screen-reader-only\">Subtítulos y subtítulos para personas con problemas de audición</span></span>"`

This should also absolutely not happen in any circumstance, which means that something's very wrong in your installation _or_ (more probable) on Amazon's servers. The only explanation I could find is that some of the content it's matching, by chance, is broken onto multiple lines by mistake. I've added a fix in a commit that will get pushed shortly.

**Comment by Varstahl** [comment] 2019-01-17 16:51
And, you can believe it or not, but after restoring my cache and going for my own TV series, it crashed. I'm on the case.

**Closed** 2019-01-17 17:20 UTC
Labels: bug

**Comment by Paco8** [comment] 2019-01-17 17:25
I'm using version 0.6.5 which I believe it's the latest one.

The problem happens to me in both Windows 10 and Nvidia Shield, and it's very consistent. The first time when the *.pvcp and *.pvdp files don't exist everything works fine, it downloads the info about the shows, everything is ok. When the cache expires the crash happens. I delete the cache files, works fine again, when the cache expires it crashes again.
