### ISSUE TITLE
Most of my watchlist is missing

### ISSUE THREAD

**Issue by nandbert** [Sandmann79/xbmc#658] opened 2022-11-23 16:54 UTC
**Addon used**
- [x] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 0.9.5+matrix.1

**Account type**
- [ ] primevideo.com
- [x] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: Pi4
- OS version: LibreElec 10.0.2
- Kodi version number: 19.4 Matrix

**Upload Logs**

not yet

**Describe the bug**

I fill my watchlist in a browser on my PC and use Kodi to watch movies from the list. I recently realized that a lot of movies that are on the list do not show up on the Kodi (Not sure since when this happens, the list was full enough :-) ). I have randomly deleted movies and added new ones on the PC. It seems the deleted ones disappear, but only very few of the added ones make it to the Kodi.

Not sure what I can do to help debugging this issue.

I did quite some googling already, and came across the statement that there is a context menu to refresh the watchlist. I cannot find this context menu. What needs to be selected to show the menu on right click?

**Comment by MrCoolAndroid** [comment] 2022-11-23 17:02
When adding TV shows you should add all the seasons, and with Movies that's weird and yes there is a refresh button, in my case (with a keyboard) just long click (with enter) on the watchlist and it should show a list with the button ”Refresh"

**Comment by Varstahl** [comment] 2022-11-23 17:05
There might also be a few differences, for example you may have stuff in your Watchlist that's gone out of catalog, and that may be filtered, although it usually should match 1:1, unless they changed everything again, which is possible.

**Comment by MrCoolAndroid** [comment] 2022-11-23 17:10
Or probably i don't think but, a Movie or TV Show from another region

**Comment by nandbert** [comment] 2022-11-23 17:44
Hi guys, thanks for the quick response!

a) I am talking about movies.
b) the discrepancy is really big, so I don't think it can be explained with movies that went out of catalog
c) I don't have the Refresh button. Either long Enter on Keyboard (with Watchlist seletected
![image](https://user-images.githubusercontent.com/12516199/203614106-28db1ad4-683d-4b67-b695-a958366052f4.png)
) or right click with mouse. This is how it looks. Weird ...

**Comment by MrCoolAndroid** [comment] 2022-11-23 18:03
> Hi guys, thanks for the quick response!
> 
> a) I am talking about movies. b) the discrepancy is really big, so I don't think it can be explained with movies that went out of catalog c) I don't have the Refresh button. Either long Enter on Keyboard (with Watchlist seletected) or right click with mouse. This is how it looks. Weird ...
> 
> ![image](https://user-images.githubusercontent.com/12516199/203614106-28db1ad4-683d-4b67-b695-a958366052f4.png)

Hmmm, do you have the latest version? And I'm not home to check how to refresh the list right now, so if you wait until I get home I can guide you

**Comment by nandbert** [comment] 2022-11-24 13:29
@MrCoolAndroid : I have 0.9.5+matrix.1 which I thought is the latest. Any guidance is very welcome ;-)

**Comment by MrCoolAndroid** [comment] 2022-11-25 23:18
> @MrCoolAndroid : I have 0.9.5+matrix.1 which I thought is the latest. Any guidance is very welcome ;-)

Sorry for late response, i forgot to answer
![16694182138419044762570900460883](https://user-images.githubusercontent.com/63800330/204062555-61191a91-7747-4304-a6af-d18e9a388225.jpg)
As you can see i hold click on the Watchlist and i get the Refresh button, unless you try to reinstall the add-on I'm out of ideas

**Comment by nandbert** [comment] 2022-11-26 11:41
@MrCoolAndroid Which version do you have?

**Comment by MrCoolAndroid** [comment] 2022-11-26 12:17
> @MrCoolAndroid Which version do you have?

I have the latest one the same you have, what i think now that it's possible because of different account types, mine is primevideo.com and yours is amazon(.com/.co.uk, etc) so the structure is different maybe

**Comment by Varstahl** [comment] 2022-11-28 10:09
I tried to investigate but can't reproduce it on my end. I don't have a German PrimeVideo account, so I'm not able to provide more help on the subject. I'll label it accordingly and keep it open, in case someone is able to provide further help.

**Comment by Ronny-nerd** [comment] 2022-11-28 18:10
It must be your hardware or your operating system...nandbert.
I have no problems to update the watchlist or for example to update movies or series in it...for me it looks like MrCoolAndroid but in german language.

My hardware: 
Nvidia Shield TV Pro 2019 (Android11)
PC (Windows 10 Pro)
Kodi19.4 and Nexus 20 Beta

**Comment by nandbert** [comment] 2022-11-28 19:55
Hmmm, thanks for your advice everybody, will do a LibreELEC install from scratch next weekend or so and see what happens. :+1:

**Comment by nandbert** [comment] 2022-12-09 22:16
Now that I finally found this WebAPI setting (dont ask :roll_eyes: ) I have enabled it, and everything looks fine now. Even "The Rings of Power" is appearing on my watchlist. As the old API is currently broken anyway (? #660 #662) this seems to be the way to go? So I would be fine with closing this issue.

**Comment by MrCoolAndroid** [comment] 2022-12-09 22:23
I guess you can close it heh

**Closed** 2022-12-09 22:26 UTC
Labels: amazon.tld
