### ISSUE TITLE
NullPointerException when selecting 'Children' menu item

### ISSUE THREAD

**Issue by HpNoTiQ56** [Sandmann79/xbmc#104] opened 2018-03-14 20:22 UTC
Duplicates from #101 but for children (has updated to last beta : Films and series are working).

Moreover, how i can auto switch audio language when playing films series? It's playing with random audio but I have to manually select french for every films/series.

20:48:23.893 T:1839186816   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: u'ao\xfbt'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/default.py", line 3283, in <module>
                                                PrimeVideo_Browse(None if 'path' not in args else args['path'])
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/default.py", line 461, in PrimeVideo_Browse
                                                PrimeVideo_LazyLoad(node, nodeName)
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/default.py", line 783, in PrimeVideo_LazyLoad
                                                if None is not res[3]: meta['videometa']['premiered'] = DelocalizeDate(amzLang, res[3])
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/default.py", line 595, in DelocalizeDate
                                                p[dateParserData[lang]['month']] = dateParserData[lang]['months'][p[dateParserData[lang]['month']]]
                                            KeyError: u'ao\xfbt'
                                            -->End of Python script error report<--
20:48:24.094 T:1941851776   ERROR: GetDirectory - Error getting plugin://plugin.video.amazon-test/?mode=PrimeVideo_Browse&path=root-%2f%2f-Enfants
20:48:24.100 T:1941851776   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.amazon-test/?mode=PrimeVideo_Browse&path=root-%2f%2f-Enfants) failed
20:53:28.389 T:1797649280   ERROR: CCurlFile::FillBuffer - Failed: Timeout was reached(28)
20:53:28.389 T:1797649280 WARNING: CCurlFile::FillBuffer - Reconnect, (re)try 1

**Comment by Varstahl** [comment] 2018-03-14 21:17
This looks like a different issue, I'll have to investigate it when I can. It looks like something wierd happened with the dates.

> Moreover, how i can auto switch audio language when playing films series? It's playing with random audio but I have to manually select french for every films/series.

The languages are defined in Kodi's player settings. From there you can define your preferred audio language and subtitle language.

**Comment by Varstahl** [comment] 2018-03-17 18:14
I'm unable to reproduce the issue. If this was a problem on amazon's end it doesn't seem like it's still broken anymore. Can you confirm you are still experiencing issues?

**Comment by Varstahl** [comment] 2018-03-30 11:54
I'm still unable to reproduce this problem, it probably must have been a temporary mistake on their servers. I'm closing this for the time being.

**Closed by Varstahl** 2018-03-30 11:54 UTC
Labels: bug, primevideo
