### ISSUE TITLE
xmbc.python 3.0.0 version can not be satisfied.

### ISSUE THREAD

**Issue by shnkreddy98** [Sandmann79/xbmc#527] opened 2020-12-24 08:23 UTC
**Addon used**
- [x] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 

**Account type**
- [ ] primevideo.com
- [ ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware:
- OS version:
- Kodi version number:

**Upload Logs**

**Describe the bug**

I have installed the repo from the zip file and when i try to install the amazon VOD video add-on, i get this "The dependency on xmbc.python version 3.0.0 could not be satisfied". I think the "MechanicalSoup" dependencies is causing this problem. Can anyone help me with this

**Comment by Varstahl** [comment] 2020-12-24 09:52
Duplicate of #498, you installed the wrong repository. You're using Kodi Leia (18) and installed Sandmann79 Matrix repository (19). Uninstall the wrong repo, download and install the one for Kodi 18 from the release page.

**Closed by Varstahl** 2020-12-24 09:52 UTC
Labels: duplicate
