### ISSUE TITLE
Occasional crashes when starting a show

### ISSUE THREAD

**Issue by DevilBlackDeath** [Sandmann79/xbmc#716] opened 2023-12-01 12:41 UTC
**Addon used**
- [X] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: latest

**Account type**
- [X] primevideo.com
- [ ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: Raspberry Pi 4 2GB
- OS version: LibreElec 11.0.3
- Kodi version number: 20.2

**Upload Logs**

[01_KODI.log](https://github.com/Sandmann79/xbmc/files/13526584/01_KODI.log)
[01_KODI_CRASH.log](https://github.com/Sandmann79/xbmc/files/13526585/01_KODI_CRASH.log)

**Describe the bug**

When starting shows Kodi will sometimes crash. It does restart without having to reboot the whole system. However when the bug appears it will usually stay for some amount of time until it works again without doing much. I joined the Kodi crash log as I think it will contain more pertinent information (I'm not sure the latest crash was actually recorded in the normal Kodi log, it's probably the new one from post-restart). Might be a settings that's wrong, but I'm unsure from looking at the log.

**Comment by sideshowbob84** [comment] 2023-12-05 08:05
**Addon used**
- [X] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: latest


**Account type**
- [ ] primevideo.com
- [X] amazon.(com/co.uk/de/jp)


**System Setup (please provide the following information):**
- Hardware: Raspberry Pi 3 and a 4 with 4GB
- OS version: LibreElec 11.0.3 and LibreElec 12
- Kodi version number: 20.2

**Upload Logs**


i uploaded my logs too. My logs are debug logs. Maybe they are more helpful.
[01_KODI_CRASH.log](https://github.com/Sandmann79/xbmc/files/13556855/01_KODI_CRASH.log)
[01_KODI.log](https://github.com/Sandmann79/xbmc/files/13556857/01_KODI.log)

**Describe the bug**

I have the same problem. I have a Raspi 4 and 3 and a sql server for my database. I tried many different things. I tried without the sql server. I tried LibreElec 11.0.3 i tried the last 5 LibreElec 12 nightlys. I made a complete reset and startet from scratch on both Raspis.

**Comment by DevilBlackDeath** [comment] 2023-12-06 12:32
If it helps some episodes seem to be able to reproduce it pretty consistently ! One of them is "Fun House" from "The Middle" Season 1 (I think it's episode 17 or 18. And an episode of the Mentalist in the last season does it too (I don't have the number off the top of my head, I'll try to find it later today and post it here, I'd say it's episode 7 on a whim but really not sure).

@sideshowbob84 Would you be able to confirm if that episode from The Middle causes the crash too for you (well if The Middle is available on Prime where you live that is)

**Comment by sideshowbob84** [comment] 2023-12-09 11:07
yes it happens for me too at episode 17 of the middle. But in my case many videos are affected. For example i am unable to watch big bang theory further. In season 7 episode 22 the error is happening reproducible too.

**Comment by DevilBlackDeath** [comment] 2023-12-10 11:17
Yeah so it's definitely a problem on some episodes, not per-machine. Some also do crash before working after a while on my end.

**Comment by Targunitoth** [comment] 2023-12-18 15:14
Raspberry Pi 4 1GB here.
For me, it feels like a 50% chance to crash kodi while starting a film or series over Amazon VOD.
But for series e.g. 4 Blocks (S3E2) it crashes 100% after the first logo is shown, maybe a bug with the "skip review" and "skip into" option?

**Comment by DevilBlackDeath** [comment] 2023-12-19 15:17
Ok so the issue definitely comes from InputStream Adaptive ! Go in InputStream Adaptive, disable Auto Update, then change the version to 20.3.11 (no need to use another depo, the depo already includes older versions). Now everything works smoothly for me). I'll let you both confirm this works for you but if it does I'll close the bug report and we'll have to file one on the InputStream github instead.

**Comment by thenomadbeyond** [comment] 2023-12-19 18:27
> Ok so the issue definitely comes from InputStream Adaptive ! Go in InputStream Adaptive, disable Auto Update, then change the version to 20.3.11 (no need to use another depo, the depo already includes older versions). Now everything works smoothly for me). I'll let you both confirm this works for you but if it does I'll close the bug report and we'll have to file one on the InputStream github instead.

I can confirm. This works.

**Comment by sideshowbob84** [comment] 2023-12-22 13:56
Thanks a lot i had to make a complete new setup with Libreelec 11, since i was already on 12. I can confirm the fix! Thanks a lot!

**Comment by fivebanger** [comment] 2023-12-23 11:12
I can confirm this issue:

Amazon streams often crashes on start. LibreELEC re-starts without a reboot. Issue remains after LibreELEC re-start.

Setup:

Raspberry Pi 4
LibreELEC v11.03

Amazon VOD v1.0.2+matrix.1

InputStream Adaptiv = v20.3.11.1 -> plays without problems
InputStream Adaptiv > v20.3.11.1 -> crashes often when starting a stream

**Comment by rptaylor** [comment] 2024-02-13 23:34
This looks like it could be the same as https://github.com/xbmc/inputstream.adaptive/issues/1394 so it may also be fixed by https://github.com/xbmc/inputstream.adaptive/pull/1464

**Comment by Sandmann79** [comment] 2024-05-05 19:00
Thanks at all for reporting and testing. This issue is not Addon related and has been already fixed at Inputstream Addon. Closing.

**Closed by Sandmann79** 2024-05-05 19:00 UTC
