### ISSUE TITLE
Some titles are only available in German

### ISSUE THREAD

**Issue by 0anth** [Sandmann79/xbmc#145] opened 2018-07-03 15:25 UTC
Hello,

Some titles (example American Gods) only display Arabic and German language options.

I am logging in with an Australian prime account and only speak English, so this is an issue.

Running on OSMC.

**Comment by Varstahl** [comment] 2018-07-03 15:38
If you're using the Amazon VOD addon, verify on PrimeVideo.com that American Gods is available in English in your region. If you can find see it on the PrimeVideo.com website in english, verify that there aren't multiple versions of the same TV series, as sometimes Amazon has the same series listed with 2/3 different IDs, thumbnails and description for the same series.

**Comment by 0anth** [comment] 2018-07-03 15:42
Yep I'm using Amazon VOD addon. I checked primevideo.com and confirmed American Gods is there and available in a whole heap of languages including English. There also appears to be only one American Gods on the list in the addon.

I tried Grand Tour and that had English and German languages available.

It's like its defaulting to a German stream or something?

**Comment by Varstahl** [comment] 2018-07-03 15:52
Unlikely by itself. Did you set the language and subtitle settings for kodi and the addon? You can find a short description on how to configure it [here](https://github.com/Sandmann79/xbmc/issues/123#issuecomment-388550806). It mainly focuses on subtitles, but the audio language is too in `Kodi Settings > Player > Language`, and get set up in a similar fashion.

In any case, regardless of your language choices, all the languages should be available using the stream language selector, although you might scroll the list quite a bit to find the correct one. If you set up the language correctly in Kodi, it should automatically select it if available.

**Comment by 0anth** [comment] 2018-07-03 16:15
I just checked, default language was set to content original. I changed it to English but there was no change. 

1-9 are Arabic and 10-17 are German. Picture of streams available: http://i.imgur.com/cg0GhXO.jpg

And yes I'm on Kodi 18.

**Comment by Varstahl** [comment] 2018-07-03 16:38
Can you provide a screenshot of the American Gods page on primevideo.com, and Kodi.log on pastebin or similar?

**Comment by 0anth** [comment] 2018-07-03 16:49
Screenshot: https://i.imgur.com/uKJq69b.png
Log: https://pastebin.com/htLU8R1H

Hopefully that's enough of the log. It's from idle to asking it to play a a video twice.

**Comment by Varstahl** [comment] 2018-07-03 17:06
I'll be honest, I don't know how to help you. Everything looks in order, the series ID is the same for the european one…

There have been a few severe changes lately with Kodi, are you running a fairly recent version? At the moment everything seems in order with Kodi 18 Alpha 3 (from July 1st) and InputStream.Adaptive v2.2.24.

Additionally/alternatively you might try to upgrade the addon to the latest development version, by replacing the `default.py` with the [most recent one](https://raw.githubusercontent.com/Sandmann79/xbmc/master/plugin.video.amazon-test/default.py).

**Comment by 0anth** [comment] 2018-07-04 12:48
Yeah I'm on 18 Alpha 3 and InputStream.Adaptive v2.2.24.

I updated the default.py and now I can see 2 channel AAC and 6 channel DD+, but again still only in Arabic or German for American Gods.

I guess I'll just leave this open in case any one else in a similar situation comes up with something.

Thanks

**Comment by Varstahl** [comment] 2018-07-04 13:48
That is weird as hell. If you try to go through all the audio languages, from the selector, regardless of what it says, are all languages heard german/arabic, or they're just mislabeled as such? It might be a CDN problem…

In the Amazon VOD settings there's a section specific to the "Preferred host" for Amazon's CDN. Maybe you can try switching that to a different CDN than what found in the logs, remove the catalog cache (`~/.kodi/userdata/addon_data/plugin.video.amazon-test/PVCatalogA3K6Y4MI8GDYMT.pvcp`) and relaunch the addon. It's really weird but without other aussie input and/or a Fiddler/Charles HTTPs traffic log I can't help much, seems like a problem on their end.

**Comment by Varstahl** [comment] 2018-07-04 13:57
I just noticed I didn't ask the all too common question: are you by chance using proxies (transparent or not) and/or VPNs? It already happened that users experiencing similar issues had their Kodi traffic routed through VPNs unbeknownst to them.

**Comment by 0anth** [comment] 2018-07-04 14:18
The only VPN on the network is on an unrelated virtual machine.

Out of curiousity, I updated my windows version of Kodi to the latest v18 nightly, installed Amazon VOD and set it to use inputstream. On Windows, the correct audio sources are shown (https://i.imgur.com/3OLnErQ.png).  From what I can tell in the log, it appears to be the same CDN source: https://pastebin.com/7adsAVdP

I will try checking the audio streams on OSMC again, but I think I checked a couple last night and they were indeed German. I will try force changing the CDN and deleting the cache too.

**Comment by Varstahl** [comment] 2018-07-04 14:28
Hmm… then it might just be that the version shipped with OSMC is just a bugged alpha nightly build. The addon is the same and platform agnostic, so if it works on one machine and not on the other, there's either something wrong with the connection or the Kodi build itself.

**Comment by 0anth** [comment] 2018-07-04 14:28
It didn't like me deleting that pvcp file, It no longer launches and this error is in the log:

`22:23:44.127 T:4069860912   ERROR: Control 50 in window 10025 has been asked to focus, but it can't
22:23:46.441 T:3868193520   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named future.builtins
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.amazon-test/default.py", line 33, in <module>
                                                import pyxbmct
                                              File "/home/osmc/.kodi/addons/script.module.pyxbmct/lib/pyxbmct/__init__.py", line 12, in <module>
                                                from .addonwindow import *
                                              File "/home/osmc/.kodi/addons/script.module.pyxbmct/lib/pyxbmct/addonwindow.py", line 14, in <module>
                                                from future.builtins import range
                                            ImportError: No module named future.builtins
                                            -->End of Python script error report<--
22:23:46.611 T:3949982448   ERROR: GetDirectory - Error getting plugin://plugin.video.amazon-test/
22:23:46.627 T:4069860912   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.amazon-test/) failed`

**Comment by Varstahl** [comment] 2018-07-04 14:29
Huh, if you were inside the tree just go back out and reload the plugin, it should rebuild the root catalogue and go from there.

**Comment by 0anth** [comment] 2018-07-04 14:40
I had to reboot to fix the error.

I changed the source to level3, but it's still showing Cloudfront in the log. You can see in the log I flicked through several audio streams. They were indeed all either Arabic or German.

https://pastebin.com/YqEtG3nL

**Comment by Varstahl** [comment] 2018-07-04 14:53
Yeah, with CDNs is pretty hit or miss, not all of them are available in every region. At this point I'm afraid it's a bad Kodi build. It's still alpha, after all.

**Comment by 0anth** [comment] 2018-07-04 14:59
I will wait for OSMC to use an updated nightly build and report back if that made any changes when that happens.

**Comment by Varstahl** [comment] 2018-08-02 10:35
@0anth any update on the issue?

**Comment by 0anth** [comment] 2018-08-05 08:42
The last few latest builds have been buggy, so I'm still on the same release at the moment.

**Comment by mymo1982** [comment] 2018-10-07 12:13
I am going through a similar issue as the OP: when I switch the input stream from "automatic" to "manual", it gives me an array of 17 tracks to choose from, but it's all German.

This doesn't happen when input stream is set on "automatic" (all languages are displayed correctly) and on Windows 10, but it is only related to Android and CoreElec.

**Comment by lioneld** [comment] 2018-10-07 12:30
Hi there,

I'm running Kodi 18 on Ubuntu 18.04, and I was facing the same issue. 
I was only able to select Arabic and German language on most streams. I'm located in Belgium and logged with a french Amazon account.
But after updating the lib widevine with this one : https://dl.google.com/widevine-cdm/1.4.9.1088-linux-x64.zip, the issue seems to be solved.
(the lib must be place into the ~/.kodi/cdm folder, don't forget to remove the link in that folder)
I'm now able to select all the other languages.

Regards,
Lionel

**Comment by Varstahl** [comment] 2018-10-07 12:50
Issue confirmed on LibreELEC with manual stream selection, does not appear with automatic stream selection.

Widevine 1.4.9.1088 is already installed and does not affect the issue.

**Comment by Varstahl** [comment] 2018-10-09 14:50
So, I forgot, a little recap update. Long story short: I found the "bug" but nobody cares. If what they've told me is true, manual stream selection in input stream has been used only for debugging purposes, and will not be fixed because nobody cares. Also, it will be stripped from InputStream.Adaptive at some point in the future.

So, yeah. Just don't use manual stream selection and you'll be peachy.

**Comment by mymo1982** [comment] 2018-10-09 17:21
Thank you for letting us know.
I disagree with the fact manual stream is useless: when I set automatic stream the application picks the right resolution/bitrate according to network speed. Having used this add-on through Wi-Fi on an Android box I can tell network reception can be quite moody so the add-on tends to choose among the lowest ranking available streams when the network speed is not that great at that given moment. Through manual stream we can force the stream quality of our choice (sometimes -but not necessarily- to the detriment of stream  stability)

**Comment by Varstahl** [comment] 2018-10-09 18:04
You can achieve the same with automatic pick and min/max bandwidth. You can tell IS.A never to go below a certain bandwidth, even if that means buffering, and it will achieve the same thing without having to pick up manually. I mean, it makes a lot of sense, it's what all the streaming applications do nowadays, it's just that when it comes to certain platforms there's an overwhelming plethora of streams to pick from, but it's possible to pick whatever you need with min/max.

I guess (and it's pretty much an unfounded speculation) that whatever Manual selection was, would be probably available inside Kodi's stream selection at some point, just like audio tracks. At least, that's what I'd do if it was up to me.

**Comment by mymo1982** [comment] 2018-10-09 18:29
Thanks, I will do as you suggested when the stream quality is too low. Hopefully it's a good work around.

**Comment by Varstahl** [comment] 2018-10-19 11:35
Closing this issue as this is out of scope

**Closed by Varstahl** 2018-10-19 11:35 UTC
Labels: invalid
