### ISSUE TITLE
Add-on stopped working without a particular reason

### ISSUE THREAD

**Issue by volkhen** [Sandmann79/xbmc#533] opened 2021-01-23 21:09 UTC
**Addon used**
- [X] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 0.9.0

**Account type**
- [X] primevideo.com
- [ ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: Pi 4b
- OS version: 9.2.6
- Kodi version number: 18.9 

**Upload Logs**

`2021-01-23 21:37:23.277 T:3011444752   DEBUG: ProcessMouse: trying mouse action leftclick
2021-01-23 21:37:23.278 T:3011444752   DEBUG: CGUIMediaWindow::GetDirectory (plugin://plugin.video.amazon-test/)
2021-01-23 21:37:23.278 T:3011444752   DEBUG:   ParentPath = [addons://sources/video]
2021-01-23 21:37:23.279 T:2880512880   DEBUG: Thread waiting start, auto delete: false
2021-01-23 21:37:23.283 T:3001021296   DEBUG: libinput: event0  - debounce state: DEBOUNCE_STATE_RELEASE_WAITING → DEBOUNCE_EVENT_TIMEOUT_SHORT → DEBOUNCE_STATE_RELEASED
2021-01-23 21:37:23.311 T:3001021296   DEBUG: libinput: event0  - debounce state: DEBOUNCE_STATE_RELEASED → DEBOUNCE_EVENT_TIMEOUT → DEBOUNCE_STATE_IS_UP
2021-01-23 21:37:23.329 T:2870825840   DEBUG: CAddonDatabase::SetLastUsed[plugin.video.amazon-test] took 51 ms
2021-01-23 21:37:23.330 T:2880512880   DEBUG: StartScript - calling plugin Amazon VOD('plugin://plugin.video.amazon-test/','6','','resume:false')
2021-01-23 21:37:23.330 T:2599908208   DEBUG: Thread LanguageInvoker start, auto delete: false
2021-01-23 21:37:23.330 T:2599908208    INFO: initializing python engine.
2021-01-23 21:37:23.330 T:2599908208   DEBUG: CPythonInvoker(8, /storage/.kodi/addons/plugin.video.amazon-test/default.py): start processing
2021-01-23 21:37:23.353 T:2599908208   DEBUG: -->Python Interpreter Initialized<--
2021-01-23 21:37:23.353 T:2599908208   DEBUG: CPythonInvoker(8, /storage/.kodi/addons/plugin.video.amazon-test/default.py): the source file to load is "/storage/.kodi/addons/plugin.video.amazon-test/default.py"
2021-01-23 21:37:23.356 T:2599908208   DEBUG: CPythonInvoker(8, /storage/.kodi/addons/plugin.video.amazon-test/default.py): setting the Python path to /storage/.kodi/addons/plugin.video.amazon-test:/storage/.kodi/addons/script.module.beautifulsoup4/lib:/storage/.kodi/addons/script.module.certifi/lib:/storage/.kodi/addons/script.module.chardet/lib:/storage/.kodi/addons/script.module.idna/lib:/storage/.kodi/addons/script.module.inputstreamhelper/lib:/storage/.kodi/addons/script.module.kodi-six/libs:/storage/.kodi/addons/script.module.mechanicalsoup/lib:/storage/.kodi/addons/script.module.pyautogui/lib:/storage/.kodi/addons/script.module.pyxbmct/lib:/storage/.kodi/addons/script.module.requests/lib:/storage/.kodi/addons/script.module.six/lib:/storage/.kodi/addons/script.module.urllib3/lib:/usr/lib/python27.zip:/usr/lib/python2.7:/usr/lib/python2.7/plat-linux2:/usr/lib/python2.7/lib-tk:/usr/lib/python2.7/lib-old:/usr/lib/python2.7/lib-dynload:/usr/lib/python2.7/site-packages:/usr/lib/python2.7/site-packages/gtk-2.0
2021-01-23 21:37:23.356 T:2599908208   DEBUG: CPythonInvoker(8, /storage/.kodi/addons/plugin.video.amazon-test/default.py): entering source directory /storage/.kodi/addons/plugin.video.amazon-test
2021-01-23 21:37:23.356 T:2599908208   DEBUG: CPythonInvoker(8, /storage/.kodi/addons/plugin.video.amazon-test/default.py): instantiating addon using automatically obtained id of "plugin.video.amazon-test" dependent on version 2.24.0 of the xbmc.python api
2021-01-23 21:37:23.379 T:3011444752   DEBUG: ------ Window Init (DialogBusy.xml) ------
2021-01-23 21:37:24.078 T:2599908208   DEBUG: CAddonSettings[plugin.video.amazon-test]: loading setting definitions
2021-01-23 21:37:24.078 T:2599908208   DEBUG: CAddonSettings[plugin.video.amazon-test]: trying to load setting definitions from old format...
2021-01-23 21:37:24.082 T:2599908208   DEBUG: CAddonSettings[plugin.video.amazon-test]: loading setting values
2021-01-23 21:37:24.151 T:2599908208  NOTICE: [Amazon VOD] startup.py:40 Requested {}
2021-01-23 21:37:24.184 T:2599908208  NOTICE: [Amazon VOD] startup.py:65 Version: 0.9.0
2021-01-23 21:37:24.184 T:2599908208  NOTICE: [Amazon VOD] startup.py:66 Unicode filename support: False
2021-01-23 21:37:24.185 T:2599908208  NOTICE: [Amazon VOD] startup.py:67 Locale: en-us / Language: en
2021-01-23 21:37:24.193 T:2599908208  NOTICE: [Amazon VOD] network.py:144 getURL: https://www.primevideo.com
2021-01-23 21:37:25.246 T:2599908208  NOTICE: [Amazon VOD] network.py:225 Download Time: 1.05182409286
2021-01-23 21:37:25.399 T:2599908208 WARNING: [Amazon VOD] network.py:770 Collision detected during JSON objects merging on key “pageType”, overwriting and praying (type: <type 'unicode'>)
2021-01-23 21:37:25.404 T:2599908208   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: u'name'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/default.py", line 5, in <module>
                                                EntryPoint()
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/startup.py", line 69, in EntryPoint
                                                g.pv.BrowseRoot()
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/primevideo.py", line 366, in BrowseRoot
                                                if not self.BuildRoot():
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/primevideo.py", line 378, in BuildRoot
                                                self._UpdateProfiles(home)
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/primevideo.py", line 265, in _UpdateProfiles
                                                'title': p['name'],
                                            KeyError: u'name'
                                            -->End of Python script error report<--
2021-01-23 21:37:25.404 T:2599908208   DEBUG: onExecutionDone(8, /storage/.kodi/addons/plugin.video.amazon-test/default.py)
2021-01-23 21:37:25.405 T:3011444752   DEBUG: ------ Window Init (DialogNotification.xml) ------
2021-01-23 21:37:25.504 T:2599908208 WARNING: CPythonInvoker(8, /storage/.kodi/addons/plugin.video.amazon-test/default.py): the python script "/storage/.kodi/addons/plugin.video.amazon-test/default.py" has left several classes in memory that we couldn't clean up. The classes include: N14PythonBindings31XBMCAddon_xbmc_Monitor_DirectorE,N9XBMCAddon9xbmcaddon5AddonE,N9XBMCAddon7xbmcgui6DialogE
2021-01-23 21:37:25.504 T:2599908208    INFO: Python interpreter stopped
2021-01-23 21:37:25.505 T:2599908208   DEBUG: Thread LanguageInvoker 2599908208 terminating
2021-01-23 21:37:25.523 T:2880512880   ERROR: GetDirectory - Error getting plugin://plugin.video.amazon-test/
2021-01-23 21:37:25.523 T:2880512880   DEBUG: Thread waiting 2880512880 terminating
2021-01-23 21:37:25.537 T:3011444752   DEBUG: ------ Window Deinit (DialogBusy.xml) ------
2021-01-23 21:37:25.538 T:3011444752   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.amazon-test/) failed
2021-01-23 21:37:25.538 T:3011444752   DEBUG: CGUIMediaWindow::GetDirectory (addons://sources/video)
2021-01-23 21:37:25.538 T:3011444752   DEBUG:   ParentPath = []
2021-01-23 21:37:25.539 T:2880512880   DEBUG: Thread waiting start, auto delete: false
2021-01-23 21:37:25.548 T:2880512880   DEBUG: Thread waiting 2880512880 terminating
2021-01-23 21:37:25.551 T:2880512880   DEBUG: Thread BackgroundLoader start, auto delete: false
`

**Describe the bug**

I had problems with logging in but this was saved by update then I tried to open some video and there was a prompt to update Widevine CDM which was extracted successfully. After that the Add-on stopped working with an error while opening.
Amazon VOD Error (log above).

I tried to unninstall and reinstall again from zip file but it's still the same...
Any idea what's the issue?

**Comment by volkhen** [comment] 2021-01-23 21:10
Sorry one correction. After the CDM update I clicked on the video and it wasn't playing, just running circle and that's all, shortly after that the add-on stopped opening completely.

**Comment by Sandmann79** [comment] 2021-01-23 21:17
Duplicate of #516. As workaround and if you don't use profiles, just disable it addon settings and this error should be gone.

**Closed by Sandmann79** 2021-01-23 21:17 UTC

**Comment by volkhen** [comment] 2021-01-24 12:28
Disabling profiles didn't help.

I've found two things. 

1. my profile name on PrimeVideo was blank - so I changed it to something
2. Yesterday was the payment day and I didn't have enough money on the account - after transfering the money the payment was automatically done and it started to work.

I don't know which of the two above helped. 

Sorry for bothering.

**Comment by Sandmann79** [comment] 2021-01-24 13:40
I think renaming have done the trick. The empty profile name raises this error.
