### ISSUE TITLE
Playback fails when trying to play next episode in a season.

### ISSUE THREAD

**Issue by spedicy853** [Sandmann79/xbmc#650] opened 2022-09-18 16:02 UTC
When watching any TV show the addon fails to play the next episode in the season after the current one has finished playing. The addon attempts to play the next episode three time (showing the loading circle 3 times) before Kodi gives up and displays a prompt stating that one or more item failed to play.

**Comment by Varstahl** [comment] 2022-11-28 10:25
I'm not sure if you're referring to the `Play from here` functionality of Kodi, but I can't reproduce the issue.

You've also ignored all the details required to provide you support, so I'm gonna close the issue down. Feel free to reopen and provide full logs and details as requested, thanks.

**Closed by Varstahl** 2022-11-28 10:25 UTC
