### ISSUE TITLE
Addon stuck "Loading page x..."

### ISSUE THREAD

**Issue by nhermosilla14** [Sandmann79/xbmc#440] opened 2020-04-06 22:45 UTC
**Addon used**
- [x] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)
- Addon Version [0.8.2]

**Prime Video Account (select one)**
- [x] primevideo.com
- [ ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: [Ryzen 5 2500u + Vega 8, Acer Aspire 3 laptop]
- OS Version: [Arch Linux]
- Kodi Version [18.6]

**Describe the bug**
Not sure if it's a bug or the intended functionality, but for me it just keeps loading pages for a long, long time, and sometimes it's so long that I have to manually stop it. It shows several notifications, beginning with "Loading page 2..." and increasing the number of page indefinitely (I've kept waiting until page 20, with no signs of stopping anytime soon). Maybe I'm doing something wrong, but anyway, could use some help. Thanks anyway for your time and efforts.

**Comment by Varstahl** [comment] 2020-04-07 07:20
Long story short, yes, it's normal. In order to provide results in a better way than what is usually returned by Amazon I created it this way to scrape in a run the entire list and sort the entries in a more sensible way.

Yesterday I tried some scraping on an Orange Pi PC 2. While after the initial scraping it takes significantly less time, it can be unbearably slow on some machines.

The fix for this has been in the queue since forever, but I didn't find the time to work on it yet. Until I can properly get around to it, I suggest you leave it scraping the main categories once to cache most of the video data it needs, so that the next time you load Kodi most of the work has been already done.

**Comment by nhermosilla14** [comment] 2020-04-07 19:20
Thanks for the fast answer, I'll do as you say. I haven't done any
development related to Kodi, but I'm pretty fluent using Python and C.
If there's some way to help, please let me know. With some guidance,
I'm pretty sure I can get some work done. Thanks again, cheers!

**Comment by vercinstex** [comment] 2020-04-16 18:41
Same "issue" on rpi3
Absolutely loooooooo......ong loading time...

**Comment by gideon793** [comment] 2020-04-20 17:00
It is unbearably long on a rpi4 as well.

**Comment by MichielioZ** [comment] 2020-04-29 17:56
> 
> 
> Same "issue" on rpi3
> Absolutely loooooooo......ong loading time...

Same here, I actually go make some coffee, wait untill it's done, come back with my mug to see it's still busy. The "reorganizing" of the stuff Amazon sends back should be a setting that could be turned off and on. I get that things might look weird for a list of different series, but once you dive into a season, I couldn't care less if episode 13 shows up first (as long as it's numbered) if it makes this plugin usable again...

**Comment by Varstahl** [comment] 2020-04-29 18:27
That's not what this addon is doing, at all. It's just scraping data. On an average PC it takes 30 seconds top, I have no idea why it takes so damn much on RPis, but it is what it is until I can work on it.

**Comment by marcoboutch** [comment] 2020-04-30 20:05
Hi :) thank for this addon but same for me on PC i5 / Win 10 / canada... Really long to load and scraping pages. Maybe is good idea to check for use API or xml get query to local tree structure fast. I not checked your code but i can confirm is really long to load. Have nice day ;)

**Comment by Varstahl** [comment] 2020-04-30 20:15
We're already using APIs wherever possible. 1:1 results like in PrimeVideo will be the next major thing I do for the addon, I've just been overwhelmed with other work/life related issues.

**Comment by marcoboutch** [comment] 2020-04-30 20:36
yes i understand ;) i not really use PrimeVideo and is my first try of 30 days free... that's why I discovered your addon today. I know really nothing on PrimeVideo or your addon but good luck for this project :) whitout this slow issue , you addon look really perfect ;) Thank again for your effort.

**Comment by Varstahl** [comment] 2020-04-30 20:50
You will see it speed up significantly on PC after the first initial scraping. Most of the data gets cached, just the beginning is a bit too brutal, but the more it caches the faster it gets. Also, to avoid those problems, somebody uses a browser to put stuff in the watchlist and then just access the Watchlist from Kodi, to speed things up.

Enjoy your free trial, there's a loot of good stuff :)

**Comment by marcoboutch** [comment] 2020-04-30 20:59
OMG ok so true, i see ;) haha, sorry my bad ;) niceee!!!
I checked your code really fast and maybe you just need RegEx optimisation for speed. I dont know if RegEx speed is your issue but i know is possible to optimize speed like this https://www.loggly.com/blog/five-invaluable-techniques-to-improve-regex-performance/

But finally is cool if is only the first scraping ;) sorry for my bad english i talk only little bit

**Comment by Varstahl** [comment] 2020-04-30 21:03
For the most part we use JSON data parsing, except for dates, which amazon doesn't provide in any sane format. Like, any would be fine, but no, they fucked up their API endpoints badly, and they're a mess. Other than that it's just a bit of JSON data merging and pruning, some processing and then caching.

The big problem for the loading times is that the first time, since Amazon doesn't provide fundamental information, we need to grab them with expensive secondary or tertiary queries.

**Closed** 2020-05-14 21:18 UTC
Labels: primevideo
