### ISSUE TITLE
Adding Support for Canadian Accounts 

### ISSUE THREAD

**Issue by abralski** [Sandmann79/xbmc#77] opened 2018-02-02 00:58 UTC
Are there any plans on adding support for Canadian accounts? The AmazonPrime VOD service is now available here in Canada, and having this Addon working in Kodi would be great. 
Thanks for all the good work,
Andrew

**Comment by Varstahl** [comment] 2018-02-02 09:02
Duplicate of #22, it already does. The update for PrimeVideo support will be pushed in a few days, we are currently fixing the last couple things.

**Closed by Varstahl** 2018-02-02 09:02 UTC
