### ISSUE TITLE
Double quotes error

### ISSUE THREAD

**Issue by MadMal** [Sandmann79/xbmc#710] opened 2023-10-25 13:03 UTC
**Addon used**
- [X] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 

**Account type**
- [ ] primevideo.com
- [X] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: RPi4
- OS version: OSMC
- Kodi version number: v20.2

**Upload Logs**

**Describe the bug**

Crashes on starting with the error "Amazon VOD error" check the logs.

Have tried uninstalling and reinstalling, etc .. 

Started last night between watching shows ... 

[kodi.log](https://github.com/Sandmann79/xbmc/files/13166177/kodi.log)

**Comment by Sandmann79** [comment] 2023-10-25 18:30
Duplicate of #709 
Amazon changed something shortly after i pushed the stable release. Strange...

**Closed by Sandmann79** 2023-10-25 18:30 UTC

**Comment by MadMal** [comment] 2023-10-26 11:37
Thanks - I wasnt sure if what I saw was different to the other recent issues ..

Good luck with the fix!
