### ISSUE TITLE
AMAZON VOD addon keeps on updating programs and movies

### ISSUE THREAD

**Issue by Tarun75** [Sandmann79/xbmc#304] opened 2019-05-04 07:52 UTC
Hi ,

I am in India ,I started facing the issue couple of days back. I have installed AMAZON VOD on Kodi 18, LibreElec 9.0 version, update #209 from Millhouse 9. I am using Rpi 3+ platform .When I click TV programs folder, the AMAZON VOD  displays message on top Right corner of Screen "Found XXXXX" , seems it tries to updated program list. But this goes on and I am not able to explore any programs and movies in the folder.
Please help .

**Comment by Varstahl** [comment] 2019-05-04 13:28
Just let it finish?

**Comment by Tarun75** [comment] 2019-05-04 16:12
left it for hours but still the same.

**Comment by Varstahl** [comment] 2019-05-04 16:45
If anything went wrong you can back out, close kodi, [delete the .pvcp file (**not the .pvdp**)](https://github.com/Sandmann79/xbmc/wiki/FAQ#where-are-kodis-logs--where-are-the-addons-cache-files) file and try again.

**Comment by Tarun75** [comment] 2019-05-04 18:28
Deleted .pvcp file but the problem persists.

**Comment by Varstahl** [comment] 2019-05-04 19:34
You can press Escape at any time and go back.

**Comment by sheldonmaschmeyer** [comment] 2019-05-09 22:47
In Canada at least, every time I click something, such as "Action and adventure movies" it starts the Amazon VOD Found... notifications which can take some time. It would be nice to have an option to pre-download all the information at once, perhaps in the background, and have it update at a predefined time such as daily, every three days, once a week or, manually. Kinda like a database. It is a great add-on app otherwise but, not as quick as the YouTube or Netflix apps. Just needs download scheduling similar to a TV guide update.

**Comment by Varstahl** [comment] 2019-05-10 12:10
Technically it's planned, but at the moment there are other priorities.

Also, it's easy with YouTube and Netflix, because the way they sort stuff around makes actual sense, contrary to what Amazon provides.

**Comment by Nautigsam** [comment] 2019-06-29 12:51
Well... I'm afraid that you don't understant that this makes the plugin completely unusable so maybe it should be of higher priority.

**Comment by Varstahl** [comment] 2019-06-29 13:02
Well, I'm afraid that you don't understand that I'm the only developer keeping the addon alive to the best of my abilities with the little time I have at my disposal, so maybe you should just use a browser. Just sayin'.

There have been several changes in the amazon backend, last of which happened a week ago or so, it *literally makes no sense* to fix this issue that admittedly plagues a small number of users, when most of the scraping has to be completely thrown out of the window. I was planning to do it from quite a while, but since Amazon started blocking legitimate PC users from watching anything 720p and up, I kind of let this in maintenance mode, especially since I'm the last dev standing.

So, sorry if my/the project priorities are not aligned with yours, but that's how it is.

**Comment by Varstahl** [comment] 2019-07-08 23:22
If someone feels brave enough to try, I have a (mostly) working PoC live on my fork. You can grab [primevideo.py](https://github.com/Varstahl/xbmc/blob/add-pv-api/plugin.video.amazon-test/resources/lib/primevideo.py) from here and replace it in your addon installation. You should probably backup your cache files as well if you want to be able to revert, since the new version will wipe out all cache.

Some numbers (which I'm quite proud of):
* 2 minutes to load 14 pages of results with 247 non cached movies
* 7 seconds to load 14 pages of results with 247 cached movies

In the worst case scenario, you're still looking at improvements by at least an order of magnitude.

The prototype is still rough around the edges, for some reason I appear to have broken the Watchlist, but everything else should be working fine and the loading speed are so faster it's insane. Feedback about current problems with it is very welcome.

**Comment by marcoss9** [comment] 2019-07-09 02:02
You did an excellent job, the loading speed is so fast for me.

**Comment by marcoss9** [comment] 2019-07-09 15:20
I found two minor problems, the episodes in some TV series are not in the right order like in "The Big C" and "Good Omens", and in some TV series we get the seasons of the TV series inside the season like in "Fear The Walking Dead".

![1](https://user-images.githubusercontent.com/52233859/60900812-1fca5700-a26d-11e9-831b-1a3d6676b21e.png)

![2](https://user-images.githubusercontent.com/52233859/60900932-5607d680-a26d-11e9-8428-3e1d83abd60a.png)


![3](https://user-images.githubusercontent.com/52233859/60901014-7df73a00-a26d-11e9-9068-10b727f3ee5c.png)

**Comment by Varstahl** [comment] 2019-07-09 15:29
Interesting. Didn't happen for me but I guess a few of the problems I solved in the previous version and decided not to address in this one could cause issues, or maybe it's just a metadata parsing problem. I'll check when I can, thanks for reporting.

**Comment by irfus** [comment] 2019-07-23 16:43
Replacing with the [primevideo.py](https://github.com/Varstahl/xbmc/blob/add-pv-api/plugin.video.amazon-test/resources/lib/primevideo.py) fails, with the following errors in the log, when searching or listing any page.

`2019-07-23 22:05:09.760 T:1151357808   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: u'type'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/default.py", line 5, in <module>
                                                EntryPoint()
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/startup.py", line 57, in EntryPoint
                                                if 'search' == verb: g.pv.Search()
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/primevideo.py", line 545, in Search
                                                self.Browse('search', xbmcplugin.SORT_METHOD_NONE)
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/primevideo.py", line 389, in Browse
                                                node, breadcrumb = self._TraverseCatalog(path)
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/primevideo.py", line 312, in _TraverseCatalog
                                                self._LazyLoad(node[nodeName], pathList[0:1 + i])
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/primevideo.py", line 993, in _LazyLoad
                                                page = next((x['href'] for x in cnt['pagination']['paginator'] if x['type'] == 'NextPage'), None)
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/primevideo.py", line 993, in <genexpr>
                                                page = next((x['href'] for x in cnt['pagination']['paginator'] if x['type'] == 'NextPage'), None)
                                            KeyError: u'type'
                                            -->End of Python script error report<--
2019-07-23 22:05:10.024 T:1151357808 WARNING: CPythonInvoker(17, /storage/.kodi/addons/plugin.video.amazon-test/default.py): the python script "/storage/.kodi/addons/plugin.video.amazon-test/default.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon4xbmc7MonitorE,N9XBMCAddon9xbmcaddon5AddonE,N9XBMCAddon7xbmcgui6DialogE`

**Comment by Varstahl** [comment] 2019-07-23 16:48
You need to delete both caches, *.pvcp and *.pvdp from addon data.

**Comment by irfus** [comment] 2019-07-24 10:35
Happens with a fresh install of the addon, replacing the file before first use.

**Comment by Varstahl** [comment] 2019-07-24 10:47
Well, it will be fixed in time, it's pre-alpha for a reason :D

**Comment by irfus** [comment] 2019-07-24 10:49
I can post debug logs, if required.

**Comment by Varstahl** [comment] 2019-07-24 11:41
Won't be useful, I might have already fixed it on changes I didn't publish yet, will ask if needed.

**Closed** 2019-11-15 19:51 UTC
Labels: non-issue

**Comment by harshgandhi** [comment] 2019-12-07 07:17
Hi. Installed the plugin today. Using Indian prime video. Opening any Section such as Movies starts loading pages. I get a notification 'loading page xx'. Keeps doing this for a few hours. Haven't got till the end as I'm currently at page 30. Is this a known issue? Can this be bypassed?

**Comment by Varstahl** [comment] 2019-12-07 13:20
Ugh, must be a bad connection. There are several methods planned but didn't make the cut yet. The next feature will be proper pagination, so that will reduce the strain heavily.

**Comment by federicodisante** [comment] 2019-12-30 15:38
Hi @Varstahl. I was experiencing the same problem of @harshgandhi. I'm from Italy. I installed the add on in LibreElec 9.2 from @Sandmann79 repository. Follows the head of the addon.xml file.

<addon id="plugin.video.amazon-test"
       name="Amazon VOD"
       version="0.8.1"
       provider-name="Sandmann79, Varstahl"

**Comment by Varstahl** [comment] 2019-12-30 15:50
@federicodisante as I said on new installations there's some heavy caching to do, so it's relatively normal that loading new sections, especially with lots of results, takes a bit of time. On slow ADSL connections, it can take __a lot__ of time, the first time around, but from the second run forth it should be faster. Atm there's no way around it, until I code something for slower connections.

Unless no results show and "eventually" everything gets loaded (even if on slow connections you might need to enter the directory twice) then it's working as intended.

**Comment by federicodisante** [comment] 2019-12-30 15:59
@Varstahl Thank you for your work on the add on and for you quick replay! Have a good 2020 !
