### ISSUE TITLE
Audio tracks missing, max 31 visibles

### ISSUE THREAD

**Issue by Balteck** [Sandmann79/xbmc#406] opened 2020-01-27 21:59 UTC
Hello, I've started with a fresh installation of LE 9.2.0 on Raspberry 3 B+ with latest version of Amazon VOD.

I'm using the Amazon Prime from Italy, but I have some issues with italian audio tracks.

I notice that if I select a movie or TV show with few audio tracks, the addon finds the correct audio track (in DD+) as set on Kodi settings (Italian for language and force only for subtitles).

But If I select a movie with a lot of audio tracks (for example Barnyard) the addon selects the first track (Danish DD+) because italian is missing.
To be clear, it finds 31 tracks and the last one is Indonesian, so no more audio tracks like italian, korean, russian and others that I see on mobile app.
inputstream adaptive is set on auto (no manual selection of streams)
Kodi is set on Italian language for GUI, audio tracks and subtitles.

I also tried an italian only movie (Arrivano i prof) and addon finds audio tracks, but the DD+ track is marked as unknown and now italian, like the AAC 2 channel one.

**Comment by Varstahl** [comment] 2020-01-27 23:07
That only happend on "Manual Stream Selection" from InputStream.Adaptive. Recheck the settings, provide screenshots as well, of both IS.A and of the movie audio tracks.

**Comment by Balteck** [comment] 2020-01-28 12:05
I did some screenshot of my settings.

InputStream.Adaptive
![20200128_123709](https://user-images.githubusercontent.com/19212662/73262471-82b21a00-41ce-11ea-865c-af0f9071e67f.jpg)

Amazon VOD

![20200128_123746](https://user-images.githubusercontent.com/19212662/73262498-91003600-41ce-11ea-9037-ae3ebccededc.jpg)

List of Movies, where the date is always 1969 that is wrong
![20200128_124018](https://user-images.githubusercontent.com/19212662/73262515-a37a6f80-41ce-11ea-961c-13886b89845e.jpg)

Barnyard audio tracks:
![20200128_124119](https://user-images.githubusercontent.com/19212662/73262541-b9883000-41ce-11ea-9346-c0bf29c37f5d.jpg)
![20200128_124133](https://user-images.githubusercontent.com/19212662/73262546-bd1bb700-41ce-11ea-8741-03255c636ec2.jpg)
![20200128_124144](https://user-images.githubusercontent.com/19212662/73262549-c016a780-41ce-11ea-8579-ea619f4f3a5a.jpg)
![20200128_124157](https://user-images.githubusercontent.com/19212662/73262555-c3119800-41ce-11ea-8294-1bbca5210115.jpg)

Arrivano i Prof audio tracks
![20200128_125110](https://user-images.githubusercontent.com/19212662/73262573-cdcc2d00-41ce-11ea-86c6-534b7f10c7bb.jpg)

Kodi regional settings
![20200128_125340](https://user-images.githubusercontent.com/19212662/73262591-dae91c00-41ce-11ea-933a-ab6970b0c9ab.jpg)

**Comment by Varstahl** [comment] 2020-01-29 09:17
Confirmed both, this is pretty strange, got to check the MPDs, I'm not sure what's going on.

**Comment by Balteck** [comment] 2020-01-29 13:33
maybe is it possible that plugin gets only 31 audio tracks at maximum?

**Comment by Varstahl** [comment] 2020-01-29 13:45
I disabled the Proxy MPD alteration but yields no difference. It might be a Kodi bug or an InputStream.Adaptive bug, but I don't have time to test it right now, as I'm preparing for the incoming Global Game Jam.

Next week I'll take a look at the inners of Kodi/IS.A to find out why this is happening, In the meanwhile I'll mark this as invalid since it's not an issue with the addon which is working correctly.

**Comment by Varstahl** [comment] 2020-01-29 13:50
Well, I guess that won't be necessary, since [I found this](https://github.com/peak3d/inputstream.adaptive/issues/365). Max Adaptation Sets is 32, so yeah, it's a limitation between Kodi and IS.A. Don't know the details though yet, I'll investigate later, as I said before.

**Comment by Balteck** [comment] 2020-01-29 13:54
Very well. Maybe is there a workaround that filters out unnecessary tracks to IS.A?

I think something like a whitelist of allowed languages...

**Comment by Varstahl** [comment] 2020-01-29 13:56
It was in the talks but was deemed too complicated for the time so we didn't actually implement it yet. Admittedly the number of videos with more than 30 audio tracks are not many. There could be a temporary workaround but it'd be hit and miss, not sure it's gonna work, and even if it does if the stream doesn't have italian (like animes) it would be without any audio tracks to boot.

**Comment by Balteck** [comment] 2020-01-29 20:36
Also if I seem egoist, No audio or other language instead of Italian audio is the same for my family. 

May you give me some information to try and to test this workaround?

**Comment by Varstahl** [comment] 2020-01-29 23:42
Technically the GPR endpoint should be able to accept one of the language descriptors provided from the CDP endpoint (sort of? am I mixing stuff?). So, you could try to modify the `resources/lib/proxy.py` to force feed the language parameter. But I don't recall the parameter name or the accepted format for language code, you'll have to set up a SSL Proxy like Fiddler, sniff the traffic and then patch proxy.py accordingly.

**Comment by Balteck** [comment] 2020-01-30 08:17
Too complicated for me. I will wait when you have time to resolve/create a workaround

**Comment by Knives79** [comment] 2020-02-08 11:13
Hi, I am also an Italian user and I have a related problem. Whenever I want to view an episode of a TV series or a movie, I have to play it at least twice, since the first time it cannot load the audio track and only the second time (but not always) it works.
I have noticed this behavior for some time now, especially in the past few weeks.
By the way, thanks for this great plugin and best regards.

**Comment by Varstahl** [comment] 2020-02-08 13:22
@Knives79 that might be due to the MPD Proxy Alteration, disable it in VOD settings and you shouldn't experience the problem.

**Comment by Varstahl** [comment] 2020-05-07 17:12
Fixed in https://github.com/xbmc/xbmc/commit/9a78b27adcf5b1995c4e2ce40f52703f18a79ffa

**Closed by Varstahl** 2020-05-07 17:12 UTC
Labels: invalid
