### ISSUE TITLE
Not able to open watch list

### ISSUE THREAD

**Issue by ddmakadia1699** [Sandmann79/xbmc#468] opened 2020-05-09 14:38 UTC
**Addon used**
- [x] Amazon VOD (plugin.video.amazon-test)
- [x] Browser Launcher (plugin.program.browser.launcher)
- Addon Version [e.g. 0.7.5]

**Prime Video Account (select one)**
- [x] primevideo.com
- [ ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: [e.g. RPi]
- OS Version: [e.g. Windows 10]
- Kodi Version [e.g. 18.4]

**Upload Logs**
Upload `kodi.log` somewhere and post the link here. If you need help finding it, [read the appropriate entry in the FAQs](https://github.com/Sandmann79/xbmc/wiki/FAQ#what-is-debug-logging--how-can-i-enable-debug-logging-in-kodi).
For Login issues, enable advanced logging in the settings, upload the `(amazon/avod)-login` files from the [Kodi Home](https://kodi.wiki/view/Special_protocol) folder, and paste the link here, as well.

**Describe the bug**
not able to open watch list.

2020-05-09 21:02:09.913 T:1764750048  NOTICE: [Amazon VOD] Version: 0.8.4
2020-05-09 21:02:09.915 T:1764750048  NOTICE: [Amazon VOD] Unicode filename support: False
2020-05-09 21:02:09.929 T:1764750048  NOTICE: [Amazon VOD] Locale: en-gb / Language: en
2020-05-09 21:02:29.310 T:1764750048   ERROR: [Amazon VOD] Error reason: 404 error (NoRetries)
2020-05-09 21:02:29.323 T:1764750048   ERROR: [Amazon VOD] Unable to fetch the url: /api/watchlist/ref=atv_wtlp_mv?startIndex=0&sort=DATE_ADDED_DESC&contentType=MOVIE&primeOnly=false
2020-05-09 21:02:32.897 T:1764750048   ERROR: [Amazon VOD] Error reason: 404 error (NoRetries)
2020-05-09 21:02:32.898 T:1764750048   ERROR: [Amazon VOD] Unable to fetch the url: /api/watchlist/ref=atv_wtlp_mv?startIndex=0&sort=DATE_ADDED_DESC&contentType=MOVIE&primeOnly=false
2020-05-09 21:02:34.265 T:1764750048   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: string indices must be integers
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.amazon-test/default.py", line 5, in <module>
                                                EntryPoint()
                                              File "/home/osmc/.kodi/addons/plugin.video.amazon-test/resources/lib/startup.py", line 63, in EntryPoint
                                                elif 'browse' == verb: g.pv.Browse(path)
                                              File "/home/osmc/.kodi/addons/plugin.video.amazon-test/resources/lib/primevideo.py", line 468, in Browse
                                                entry = node[key]
                                            TypeError: string indices must be integers
                                            -->End of Python script error report<--
2020-05-09 21:02:34.451 T:1764750048 WARNING: CPythonInvoker(9, /home/osmc/.kodi/addons/plugin.video.amazon-test/default.py): the python script "/home/osmc/.kodi/addons/plugin.video.amazon-test/default.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE,N14PythonBindings31XBMCAddon_xbmc_Monitor_DirectorE,N9XBMCAddon7xbmcgui6DialogE
2020-05-09 21:02:34.462 T:1482674912   ERROR: GetDirectory - Error getting plugin://plugin.video.amazon-test/pv/browse/root/Watchlist/MOVIE/lazyLoadURL
2020-05-09 21:02:34.464 T:1915409968   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.amazon-test/pv/browse/root/Watchlist/MOVIE/lazyLoadURL) failed

**Comment by dfdario** [comment] 2020-05-09 15:06
Same here. Following relevant part of log
2020-05-09 16:58:53.734 T:140418243094272 WARNING: CPythonInvoker(7, /home/mymedia/.kodi/addons/plugin.video.amazon-test/default.py): the python script "/home/mymedia/.kodi/addons/plugin.video.amazon-test/default.py" has left se│
│2020-05-09 16:58:53.741 T:140418570245888   ERROR: GetDirectory - Error getting plugin://plugin.video.amazon-test/pv/browse/root/I+miei+video/ALL/lazyLoadURL                                                                         │
│2020-05-09 16:58:53.742 T:140419694861504   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.amazon-test/pv/browse/root/I+miei+video/ALL/lazyLoadURL) failed                                                                │
│2020-05-09 16:58:58.378 T:140418243094272   ERROR: [Amazon VOD] Error reason: 404 error (NoRetries)                                                                                                                                   │
│2020-05-09 16:58:58.382 T:140418243094272   ERROR: [Amazon VOD] Unable to fetch the url: /api/watchlist/ref=atv_wtlp_all?startIndex=0&sort=DATE_ADDED_DESC&contentType=ALL&primeOnly=false                                            │
│2020-05-09 16:58:59.088 T:140418243094272   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--                                                                                │
│                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!                                                                                                                                          │
│                                            Error Type: <type 'exceptions.TypeError'>                                                                                                                                                 │
│                                            Error Contents: string indices must be integers                                                                                                                                           │
│                                            Traceback (most recent call last):                                                                                                                                                        │
│                                              File "/home/mymedia/.kodi/addons/plugin.video.amazon-test/default.py", line 5, in <module>                                                                                             │
│                                                EntryPoint()                                                                                                                                                                          │
│                                              File "/home/mymedia/.kodi/addons/plugin.video.amazon-test/resources/lib/startup.py", line 63, in EntryPoint                                                                            │
│                                                elif 'browse' == verb: g.pv.Browse(path)                                                                                                                                              │
│                                              File "/home/mymedia/.kodi/addons/plugin.video.amazon-test/resources/lib/primevideo.py", line 468, in Browse                                                                            │
│                                                entry = node[key]                                                                                                                                                                     │
│                                            TypeError: string indices must be integers                                                                                                                                                │
│                                            -->End of Python script error report<--

**Comment by Varstahl** [comment] 2020-05-09 15:41
Thanks for the report, I'll close this as dupe of #466, but I'm aware of the new issues.

**Closed by Varstahl** 2020-05-09 15:41 UTC
