### ISSUE TITLE
Amazon VOD Audio/Video out of sync RPi3

### ISSUE THREAD

**Issue by pmrosado** [Sandmann79/xbmc#60] opened 2018-01-04 01:21 UTC
Hi,
I am experiencing bad lag with audio and video being out of sync on videos 720p or above.
I have tried different tvshows eg. Grand Tour, Parks and Rec, etc. all with the same result.
When selecting streams under 720p all plays fine.
Is this a known issue? Anything I can do to improve?
720p videos play fine on other plug-ins and I have a 70Mbps down 20Mbps up connection.
Also, I am using the latest Millhouse build on a RPi3.
Many thanks,

Pedro

**Comment by pmrosado** [comment] 2018-01-10 15:04
This seems to happen only on DRM protected video.

**Comment by Sandmann79** [comment] 2018-01-20 12:30
This caused by the limitation of the RPi CPU. The DRM protected content can only be software decrypted without hardware acceleration. 
You can try to raise the maximal Bandwidth at Inputstream Addon to 4000000. For some people this helped. But an resolution bigger than 720p is not possible on your device. 
Or you overclock your device with this recommendation from Millhouse:https://forum.kodi.tv/showthread.php?tid=298461&pid=2659751#pid2659751

**Comment by Sandmann79** [comment] 2018-03-14 12:12
This issue is hardware depended and not Addon related. Closing.

**Closed by Sandmann79** 2018-03-14 12:12 UTC
