### ISSUE TITLE
Support for Amazon Prime India account

### ISSUE THREAD

**Issue by suds7** [Sandmann79/xbmc#33] opened 2017-08-01 11:18 UTC
Hi Sandmann

Your addon works fine for the amazon US but i'm not able to use my Indian account Amazon Prime India account . It is very frustrating to not having support for Indian account

Do you plan to add the support in future.   I have Amazon prime India account if you need anything to add support for Indian account, please feel free to ask.

**Comment by vijayg78** [comment] 2017-08-16 15:32
+1, could you please add country India to the plugin?

**Comment by mirh** [comment] 2017-09-07 22:50
Duplicate of #22

**Comment by Sandmann79** [comment] 2017-09-17 16:12
Right, i close this

**Closed by Sandmann79** 2017-09-17 16:12 UTC
