### ISSUE TITLE
cannot login to Amazon prime Germany 

### ISSUE THREAD

**Issue by christophjodexnus** [Sandmann79/xbmc#665] opened 2022-12-17 15:31 UTC
**Addon used**
- [ x] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 0.9.6+matrix.1

**Account type**
- [ ] primevideo.com
- [x ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware:PC
- OS version: Windows 10
- Kodi version number:19.4

**Upload Logs**

Log
https://paste.kodi.tv/fivicozovu.kodi

Login log
https://paste.kodi.tv/isibemocuv.kodi

**Describe the bug**

I am logged in (user name shown in settings as locked in) but when I start the addon I get prime video error.
Using location Germany in setting cause it is German account

**Comment by GitMensch** [comment] 2022-12-22 19:31
Same here... but should be closed as it is a duplicate of #660

**Closed** 2023-04-25 19:37 UTC
