### ISSUE TITLE
Won't list any titles in Movies, TV Shows, etc.

### ISSUE THREAD

**Issue by rollnthndr** [Sandmann79/xbmc#373] opened 2019-11-29 03:43 UTC
**Addon used**
- [x] Amazon VOD (plugin.video.amazon-test)
- [ ] Amazon (plugin.video.amazon)
- [ ] Browser Launcher (plugin.program.browser.launcher)
- Addon Version 0.8.0~beta

**Prime Video Account (select one)**
- [x] primevideo.com
- [ ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: RPi3
- OS Version: OSMC
- Kodi Version 18.5

**Upload Logs**
[Kodi Log](https://paste.osmc.tv/viqefuseso)

**Describe the bug**
Go directly to TV shows, click on a category and nothing shows up. Kodi informs user of an Amazon VOD error.

**Comment by Varstahl** [comment] 2019-11-29 13:02
Duplicate of #365

**Closed by Varstahl** 2019-11-29 13:02 UTC
Labels: duplicate, primevideo
